local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-road-access", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("AxialPassengerStairsSnappyEdgeName"),
			description = _("AxialPassengerStairsSnappyEdgeDesc"),
			icon = "ui/lollo_freestyle_train_station/axialStairsExitWithSnappyEdge2m.tga"
		},
		metadata = { },
		order = {
			value = 11,
		},
		type = _constants.axialPassengerEdgeModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			return moduleHelpers.axialAreas.exitWithEdgeModule_updateFn(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams, true)
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/open_stairs/bridge_chunk_2m.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
