local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-road-access", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("FlatPassengerStairsSnappyEdgeName"),
			description = _("FlatPassengerStairsSnappyEdgeDesc"),
			icon = "ui/lollo_freestyle_train_station/openStairsExitWithSnappyEdge2m.tga"
		},
		metadata = { },
		order = {
			value = 10,
		},
		type = _constants.flatPassengerEdgeModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			return moduleHelpers.flatAreas.exitWithEdgeModule_updateFn(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams, true)
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/railroad/flatSides/passengers/era_c_stairs_edge.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
