local _constants = require('lollo_freestyle_train_station.constants')
local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local slotHelpers = require('lollo_freestyle_train_station.slotHelpers')
local transfUtils = require('lollo_freestyle_train_station.transfUtils')


function data()
	local generatedData = {
		["main"] = {
			models = {
				["station/rail/era_c/station_1.mdl"] = {
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000 },
				},
			},
		},
		["assets"] = {
			models = {
--[[
				["station/rail/asset/era_c_street_pillar.mdl"] = {
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -5.00000, -16.30000, 0.00000, 1.00000 },
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -3.00000, -16.30000, 0.00000, 1.00000 },
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, -11.05000, 0.00000, 1.00000 },
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -1.00000, -16.30000, 0.00000, 1.00000 },
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 1.00000, -16.30000, 0.00000, 1.00000 },
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 2.50000, -11.05000, 0.00000, 1.00000 },
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -2.50000, -11.05000, 0.00000, 1.00000 },
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 3.00000, -16.30000, 0.00000, 1.00000 },
					{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 5.00000, -16.30000, 0.00000, 1.00000 },
				},
]]
			},
		},
	}
	return {
		availability = {
			yearFrom = _constants.eras.era_c.startYear,
			yearTo = 0
		},
		category = {
			categories = { "passenger-road-access", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("Small side building"),
			description = _("Small side building with street access for passenger stations. Provides capacity for 20 passengers."),
			icon = "ui/construction/station/rail/modular_station/side_building_1_era_c.tga",
		},
		metadata = {
			-- nEvenSegmentPairs = 1,
			-- nSegments2Minus = 1,
			-- nSegments2Plus = 1,
			moreCapacity = {
				cargo = 0,
				passenger = 20
			},
		},
		order = {
			value = 41,
		},
		type = _constants.flatPassengerStation0MModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf(params, slotId, slotTransf)
			local buildingTransf = transfUtils.getTransf_ZRotated_Shifted(zAdjustedTransf, math.pi * 0.5, {-2.5, 0, -0.8})

			local eraPrefix = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)

			local myGroundFacesFillKey = _constants[eraPrefix .. 'groundFacesFillKey']

			local modelId = 'lollo_freestyle_train_station/railroad/flatSides/passengers/era_c_small/lollo_side.mdl'
			result.models[#result.models + 1] = {
				id = modelId,
				slotId = slotId,
				transf = buildingTransf,
				tag = tag
			}
			moduleHelpers.flatAreas.addPassengerLaneToSelf(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)
			result.models[#result.models + 1] = {
				id = 'lollo_freestyle_train_station/railroad/flatSides/passengers/passenger_waiting_area_station_9x6.mdl',
				slotId = slotId,
				transf = transfUtils.getTransf_Shifted(buildingTransf, {0, -3.2, _constants.stairsAndRampHeight + 0.8}),
				tag = slotHelpers.mangleModelTag(nTerminal, false),
			}
--[[
			if result.terminateConstructionHookInfo.underpassPositionsOnGround[nTerminal] == nil then
				result.terminateConstructionHookInfo.underpassPositionsOnGround[nTerminal] = {}
			end
			table.insert(
				result.terminateConstructionHookInfo.underpassPositionsOnGround[nTerminal],
				{
					t = nTerminal,
					lanePosTanX2 = cpl.posTanX2,
					pos2Link = transfUtils.transf2Position(
						transfUtils.getTransf_Shifted(
							buildingTransf,
							{9, -3.5, _constants.subwayPos2LinkZ}
						)
					)
				}
			)
]]
			table.insert(result.slots, {
				id = result.mangleId(nTerminal, nTrackEdge, _constants.idBases.passengerStationSquareOuterSlotId),
				shape = 1,
				spacing = {-1, 4, 4, 4},
				transf = transfUtils.getTransf_ZRotatedM90_Shifted(
					buildingTransf,
					{0, -13.2, 0}
				),
				type = _constants.passengerStationSquareModuleType,
			})

			local groundFace = {
				{-1, -5.6, -0.8, 1},
				{-1, 5.6, -0.8, 1},
				{11.5, 5.6, -0.8, 1},
				{11.5, -5.6, -0.8, 1},
			}
			modulesutil.TransformFaces(zAdjustedTransf, groundFace)
			table.insert(
				result.groundFaces,
				{
					face = groundFace,
					modes = {
						{
							type = 'FILL',
							key = myGroundFacesFillKey
						},
						{
							type = 'STROKE_OUTER',
							key = myGroundFacesFillKey
						}
					}
				}
			)

			local terrainAlignmentList = {
				faces = { groundFace },
				optional = true,
				slopeHigh = _constants.slopeHigh,
				slopeLow = _constants.slopeLow,
				type = 'EQUAL',
			}
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList

			-- constructionutil.addModels(generatedData["clock"], result.models, buildingTransf, tag)
			-- constructionutil.addModels(generatedData["assets"], result.models, buildingTransf, tag)
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/railroad/flatSides/passengers/era_c_small/lollo_side.mdl',
					transf = { 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  20, 20, 0, 1 },
				},
				moduleHelpers.flatAreas.getPreviewIcon(params),
			}
		end
	}
end
