local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-road-access", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("FlatCargoRampUpSmoothName"),
			description = _("FlatCargoRampUpSmoothDesc"),
			icon = "ui/lollo_freestyle_train_station/flatCargoRampUpSmooth.tga"
		},
		metadata = { },
		order = {
			value = 17,
		},
		type = _constants.flatCargoRampModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			-- LOLLO NOTE tag looks like '__module_201030', never mind what you write into it, the game overwrites it
			-- in base_config.lua
			-- Set it into the models, so the game knows what module they belong to.

			local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf(params, slotId, slotTransf)

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)

			local myGroundFacesFillKey = _constants[era .. 'groundFacesFillKey']
			local myModelId = _constants[era .. 'flatCargoRampUpSmoothModelFileName']

			result.models[#result.models + 1] = {
				id = myModelId,
				slotId = slotId,
				transf = zAdjustedTransf,
				tag = tag
			}

			moduleHelpers.flatAreas.addCargoLaneToStreet(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)

			local groundFace = {
				{-1, -2, 0, 1},
				{-1, 2, 0, 1},
				{3.5, 2, 0, 1},
				{3.5, -2, 0, 1},
			}
			modulesutil.TransformFaces(zAdjustedTransf, groundFace)
			result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, myGroundFacesFillKey)

			local terrainAlignmentList = {
				faces = {
					{
						{-1, -2, _constants.platformSideBitsZ, 1},
						{-1, 2, _constants.platformSideBitsZ, 1},
						{0.0, 2, _constants.platformSideBitsZ, 1},
						{0.0, -2, _constants.platformSideBitsZ, 1},
					},
					{
						{0.0, -2, _constants.platformSideBitsZ, 1},
						{0.0, 2, _constants.platformSideBitsZ, 1},
						{3.5, 2, _constants.stairsAndRampHeight, 1},
						{3.5, -2, _constants.stairsAndRampHeight, 1},
					}
				},
				optional = true,
				slopeHigh = _constants.slopeHigh,
				slopeLow = _constants.slopeLow,
				type = 'EQUAL',
			}
			for _, face in pairs(terrainAlignmentList.faces) do
				modulesutil.TransformFaces(zAdjustedTransf, face)
			end
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList
		end,

		getModelsFn = function(params)
			return {
				{
					id = _constants.era_c_flatCargoRampUpSmoothModelFileName,
					transf = _constants.idTransf,
				},
				moduleHelpers.flatAreas.getPreviewIcon(params),
			}
		end
	}
end
