local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = moduleHelpers.eras.era_b.startYear,
		yearTo = 0
	},
	category = {
		categories = { "passenger-road-access", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("FlatPassengerStation0MName"),
		description = _("FlatPassengerStation0MDesc"),
		icon = "ui/lollo_freestyle_train_station/flatPassengerStation0M.tga"
	},
	metadata = { },
	order = {
		value = 21,
	},
	type = _constants.flatPassengerStation0MModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not nTrackEdge or not baseId then return end

		local buildingTransf = transfUtilsUG.mul(
			slotTransf,
			{ 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 }
		)

		local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
        local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)

		local myGroundFacesFillKey = _constants[era .. 'groundFacesFillKey']

		local stationModelId = nil
		if era == moduleHelpers.eras.era_c.prefix then
			stationModelId = 'lollo_freestyle_train_station/lift/side_lifts_9_5_0.mdl'
		else
			stationModelId = 'lollo_freestyle_train_station/lift/era_b_side_lifts_9_5_0.mdl'
		end
		result.models[#result.models + 1] = {
			id = stationModelId,
			slotId = slotId,
			transf = buildingTransf,
			tag = tag
		}

		table.insert(result.slots, {
			id = result.mangleId(nTerminal, nTrackEdge, _constants.idBases.stationSquareOuterSlotId),
			shape = 1,
			spacing = {-1, 4, 4, 4},
			transf = transfUtilsUG.mul(
				buildingTransf,
				{ 0, -1, 0, 0,  1, 0, 0, 0,  0, 0, 1, 0,  0, -4.75, -_constants.stairsAndRampHeight, 1 }
			),
			type = _constants.passengerStationSquareModuleType,
		})

		local groundFace = { -- the ground faces ignore z, the alignment lists don't
			{-1, -6.2, -_constants.stairsAndRampHeight, 1},
			{-1, 6.2, -_constants.stairsAndRampHeight, 1},
			{6.0, 6.2, -_constants.stairsAndRampHeight, 1},
			{6.0, -6.2, -_constants.stairsAndRampHeight, 1},
		}
		modulesutil.TransformFaces(slotTransf, groundFace)
		table.insert(
			result.groundFaces,
			{
				face = groundFace,
				modes = {
					{
						type = 'FILL',
						key = myGroundFacesFillKey
					},
					{
						type = 'STROKE_OUTER',
						key = myGroundFacesFillKey
					}
				}
			}
		)

		local terrainAlignmentList = {
			faces = { groundFace },
			optional = true,
			slopeHigh = _constants.slopeHigh,
			slopeLow = _constants.slopeLow,
			type = 'EQUAL',
		}
		result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList
	end,

	getModelsFn = function(params)
		return {
			{
				id = 'lollo_freestyle_train_station/lift/side_lifts_9_5_0.mdl',
				transf = { 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 },
			},
		}
	end
}

end
