local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "cargo-road-access", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("FlatCargoStationLower8x10Name"),
		description = _("FlatCargoStationLower8x10Desc"),
		icon = "ui/lollo_freestyle_train_station/flatCargoStationLower8x10.tga"
	},
	metadata = { },
	order = {
		value = 22,
	},
	type = _constants.flatCargoArea8x10ModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not baseId then return end

		local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf_Limited(params, slotId, slotTransf)

		result.models[#result.models + 1] = {
			id = _constants.flatCargoStationLower8x10ModelFileName,
			slotId = slotId,
			transf = zAdjustedTransf,
			tag = tag
		}

		moduleHelpers.flatAreas.addLaneToStreet(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)

		local groundFace = {
			{-5.5, -6, 0, 1},
			{-5.5, 6, 0, 1},
			{8.5, 6, 0, 1},
			{8.5, -6, 0, 1},
		}
		modulesutil.TransformFaces(zAdjustedTransf, groundFace)
		result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, _constants.groundFacesFillKey)

		local terrainAlignmentList = {
			faces = {
				{
					{-5, -6, _constants.platformSideBitsZ, 1},
					{-5, 6, _constants.platformSideBitsZ, 1},
					{0, 6, -_constants.stairsAndRampHeight, 1},
					{0, -6, -_constants.stairsAndRampHeight, 1},
				},
				{
					{0, -6, -_constants.stairsAndRampHeight, 1},
					{0, 6, -_constants.stairsAndRampHeight, 1},
					{8.5, 6, -_constants.stairsAndRampHeight, 1},
					{8.5, -6, -_constants.stairsAndRampHeight, 1},
				}
			},
			optional = true,
			slopeHigh = _constants.slopeHigh,
			slopeLow = _constants.slopeLow,
			type = 'EQUAL',
		}
		for _, face in pairs(terrainAlignmentList.faces) do
			modulesutil.TransformFaces(zAdjustedTransf, face)
		end
		result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList
	end,

	getModelsFn = function(params)
		return {
			{
				id = _constants.flatCargoStationLower8x10ModelFileName,
				transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
