local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-road-access", "cargo-road-access-axial", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("FlatCargoStationLower10x10Name"),
			description = _("FlatCargoStationLower10x10Desc"),
			icon = "ui/lollo_freestyle_train_station/flatCargoStationLower8x10.tga"
		},
		metadata = {
			moreCapacity = {
				cargo = 20,
				passenger = 0
			},
			stationSquareShift_XYZ_rotZ = {
				x = 10.0,
				y = 0.0,
				z = -_constants.stairsAndRampHeight,
				rotZ = 0.0
			}
		},
		order = {
			value = 32,
		},
		type = _constants.flatCargoArea8x10ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
			local zAdjustedTransf = transfUtils.getTransf_XShifted(
				moduleHelpers.flatAreas.getMNAdjustedTransf(params, slotId, slotTransf),
				5
			)

			local cpl = _terminalData.centrePlatformsRelative[nTrackEdge]
			local _eraPrefix = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)

			local myGroundFacesFillKey = moduleHelpers.getGroundFacesFillKey_cargo(result, nTerminal, _eraPrefix)
			local myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_c_station10x10_lower.mdl'
			if _eraPrefix == moduleHelpers.eras.era_a.prefix then
				myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_a_station10x10_lower.mdl'
			elseif _eraPrefix == moduleHelpers.eras.era_b.prefix then
				myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_b_station10x10_lower.mdl'
			end

			result.models[#result.models + 1] = {
				id = myModelId,
				slotId = slotId,
				transf = zAdjustedTransf,
				tag = tag
			}

			if baseId == _constants.idBases.axialStation0MSlotId then
				moduleHelpers.axialAreas.addCargoLaneToSelf(result, zAdjustedTransf, tag, slotId, params, nTerminal, _terminalData, nTrackEdge)
			else
				moduleHelpers.flatAreas.addCargoLaneToSelf(result, zAdjustedTransf, tag, slotId, params, nTerminal, _terminalData, nTrackEdge)
			end

			local groundFace = {
				{-5.5, -6, 0, 1},
				{-5.5, 6, 0, 1},
				{8.5, 6, 0, 1},
				{8.5, -6, 0, 1},
			}
			modulesutil.TransformFaces(zAdjustedTransf, groundFace)
			result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, myGroundFacesFillKey)

			local terrainAlignmentList = {
				faces = {
					{
						{-5, -6, _constants.platformSideBitsZ, 1},
						{-5, 6, _constants.platformSideBitsZ, 1},
						{-1, 6, -_constants.stairsAndRampHeight, 1},
						{-1, -6, -_constants.stairsAndRampHeight, 1},
					},
					{
						{-1, -6, -_constants.stairsAndRampHeight, 1},
						{-1, 6, -_constants.stairsAndRampHeight, 1},
						{8.5, 6, -_constants.stairsAndRampHeight, 1},
						{8.5, -6, -_constants.stairsAndRampHeight, 1},
					}
				},
				optional = true,
				slopeHigh = _constants.slopeHigh,
				slopeLow = _constants.slopeLow,
				type = 'EQUAL',
			}
			for _, face in pairs(terrainAlignmentList.faces) do
				modulesutil.TransformFaces(zAdjustedTransf, face)
			end
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList

			if baseId ~= _constants.idBases.axialStation0MSlotId then
				table.insert(result.slots, {
					id = result.mangleId(nTerminal, nTrackEdge, _constants.idBases.cargoStationSquareOuterSlotId),
					shape = 1,
					spacing = {1, 1, 2, 2},
					-- transf = transfUtilsUG.mul(
					-- 	zAdjustedTransf,
					-- 	{ 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  5.0, 0, -_constants.stairsAndRampHeight, 1 }
					-- ),
					transf = transfUtils.getTransf_Shifted(
						zAdjustedTransf,
						{5.0, 0, -_constants.stairsAndRampHeight}
					),
					type = _constants.cargoStationSquareModuleType,
				})
			end
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_c_station10x10_lower.mdl',
					transf = _constants.idTransf,
				},
				moduleHelpers.flatAreas.getPreviewIcon(params),
			}
		end
	}
end
