local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-road-access", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("FlatCargoStation20x20Name"),
			description = _("FlatCargoStation20x20Desc"),
			icon = "ui/lollo_freestyle_train_station/flatCargoStation20x20.tga"
		},
		metadata = {
			isOccupyM1 = true,
			isOccupyP1 = true,
			moreCapacity = {
				cargo = 80,
				passenger = 0
			}
		},
		order = {
			value = 35,
		},
		type = _constants.flatCargoArea8x10ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf_Limited(params, slotId, slotTransf)

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			local eraPrefix = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)

			local myGroundFacesFillKey = _constants[eraPrefix .. 'groundFacesFillKey']
			local myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_c_station_20x20.mdl'
			if eraPrefix == moduleHelpers.eras.era_b.prefix then
				myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_b_station_20x20.mdl'
			elseif eraPrefix == moduleHelpers.eras.era_a.prefix then
				myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_a_station_20x20.mdl'
			end

			result.models[#result.models + 1] = {
				id = myModelId,
				slotId = slotId,
				transf = zAdjustedTransf,
				tag = tag
			}

			moduleHelpers.flatAreas.addCargoLaneToStreet(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)

			local groundFace = {
				{-5.5, -10.5, _constants.platformSideBitsZ, 1},
				{-5.5, 10.5, _constants.platformSideBitsZ, 1},
				{18.5, 10.5, _constants.platformSideBitsZ, 1},
				{18.5, -10.5, _constants.platformSideBitsZ, 1},
			}
			modulesutil.TransformFaces(zAdjustedTransf, groundFace)
			result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, myGroundFacesFillKey)

			local terrainAlignmentList = {
				faces = {
					groundFace,
				},
				optional = true,
				slopeHigh = _constants.slopeHigh,
				slopeLow = _constants.slopeLow,
				type = 'EQUAL',
			}
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList

			table.insert(result.slots, {
				id = result.mangleId(nTerminal, nTrackEdge, _constants.idBases.cargoStationSquareOuterSlotId),
				shape = 1,
				spacing = {1, 1, 2, 2},
				transf = transfUtilsUG.mul(
					zAdjustedTransf,
					{ 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  17, 0, 0, 1 }
				),
				type = _constants.cargoStationSquareModuleType,
			})
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_a_station_20x20.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
