local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-road-access", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("FlatPassengerStairsFlatName"),
			description = _("FlatPassengerStairsFlatDesc"),
			icon = "ui/lollo_freestyle_train_station/flatPassengerStairsFlat.tga"
		},
		metadata = { },
		order = {
			value = 15,
		},
		type = _constants.flatPassengerStairsModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			-- LOLLO NOTE tag looks like '__module_201030', never mind what you write into it, the game overwrites it
			-- in base_config.lua
			-- Set it into the models, so the game knows what module they belong to.

			local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf(params, slotId, slotTransf)

			local eraPrefix = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
			local myGroundFacesFillKey = _constants[eraPrefix .. 'groundFacesFillKey']
			local myModelId = _constants[eraPrefix .. 'flatPassengerStairsFlatModelFileName']

			result.models[#result.models + 1] = {
				id = myModelId,
				slotId = slotId,
				transf = zAdjustedTransf,
				tag = tag
			}

			moduleHelpers.flatAreas.addExitPole(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)
			moduleHelpers.flatAreas.addPassengerLaneToStreet(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			if result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal] == nil then
				result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal] = {}
			end
			table.insert(
				result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal],
				{
					t = nTerminal,
					-- lanePosTanX2 = cpl.posTanX2,
					pos = transfUtils.transf2Position(transfUtilsUG.mul(zAdjustedTransf, {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  2.5, 0, 0, 1}))
				}
			)

			local groundFace = { -- groundFaces ignore z, terrainAlignmentLists don't
				{-1, -2, _constants.platformSideBitsZ, 1},
				{-1, 2, _constants.platformSideBitsZ, 1},
				{3.5, 2, _constants.platformSideBitsZ, 1},
				{3.5, -2, _constants.platformSideBitsZ, 1},
			}
			modulesutil.TransformFaces(zAdjustedTransf, groundFace)
			result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, myGroundFacesFillKey)

			local terrainAlignmentList = {
				faces = { groundFace },
				optional = true,
				slopeHigh = _constants.slopeHigh,
				slopeLow = _constants.slopeLow,
				type = 'EQUAL',
			}
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList
		end,

		getModelsFn = function(params)
			return {
				{
					id = _constants.era_c_flatPassengerStairsFlatModelFileName,
					transf = _constants.idTransf,
				},
				moduleHelpers.flatAreas.getPreviewIcon(params),
			}
		end
	}
end
