local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require 'constructionutil'
local logger = require('lollo_freestyle_train_station.logger')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require 'modulesutil'
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require 'transf'

-- LOLLO OBSOLETE we don't need this
function data()
	return {
		availability = {
			yearFrom = -1,
			yearTo = -1
		},
		category = {
			categories = { 'cargo-road-access', },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _('FlushCargoExitOuterName'),
			description = _('FlushCargoExitOuterDesc'),
			icon = 'ui/lollo_freestyle_train_station/flushCargoExitOuter.tga'
		},
		metadata = { },
		order = {
			value = 12,
		},
		type = _constants.flushCargoExitModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			-- LOLLO NOTE tag looks like '__module_201030', never mind what you write into it, the game overwrites it
			-- in base_config.lua
			-- Set it into the models, so the game knows what module they belong to.

			local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf(params, slotId, slotTransf)

			moduleHelpers.flatAreas.addExitPole(result, slotTransf, tag, slotId, params, nTerminal, nTrackEdge)
			moduleHelpers.flatAreas.addCargoLaneToSelf(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/asset/cargo_perron_number.mdl',
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  -1, 0, 0, 1},
				},
				moduleHelpers.flatAreas.getPreviewIcon(params),
			}
		end
	}
end
