local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require 'constructionutil'
local logger = require('lollo_freestyle_train_station.logger')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require 'modulesutil'
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require 'transf'


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { 'cargo-road-access', },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _('FlushCargoExitOuterName'),
			description = _('FlushCargoExitOuterDesc'),
			icon = 'ui/lollo_freestyle_train_station/flushCargoExitOuter.tga'
		},
		metadata = { },
		order = {
			value = 12,
		},
		type = _constants.flushCargoExitModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			-- LOLLO NOTE tag looks like '__module_201030', never mind what you write into it, the game overwrites it
			-- in base_config.lua
			-- Set it into the models, so the game knows what module they belong to.

			local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf_Cycling(params, slotId, slotTransf)

			moduleHelpers.flatAreas.addExitPole(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)
			-- moduleHelpers.flatAreas.addPassengerLaneToStreet(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			if result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal] == nil then
				result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal] = {}
			end

			-- result.models[#result.models + 1] = {
			-- 	id = 'lollo_freestyle_train_station/icon/blue.mdl',
			-- 	slotId = slotId,
			-- 	transf = transfUtils.getTransfZShiftedBy(zAdjustedTransf, nTerminal),
			-- 	tag = tag
			-- }

			table.insert(
				result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal],
				{
					t = nTerminal,
					-- lanePosTanX2 = cpl.posTanX2,
					pos = transfUtils.transf2Position(zAdjustedTransf),
				}
			)
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/asset/cargo_perron_number.mdl',
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  -1, 0, 0, 1},
				},
				moduleHelpers.flatAreas.getPreviewIcon(params),
			}
		end
	}
end
