local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	local _nAdjustableSteps = 4
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-road-access", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("FlushPassengerExitAdjustableName"),
			description = _("FlushPassengerExitAdjustableDesc"),
			icon = "ui/lollo_freestyle_train_station/flushPassengerExitAdjustable.tga"
		},
		metadata = { },
		order = {
			value = 13,
		},
		type = _constants.flushPassengerExitModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			-- LOLLO NOTE tag looks like '__module_201030', never mind what you write into it, the game overwrites it
			-- in base_config.lua
			-- Set it into the models, so the game knows what module they belong to.
			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			local crossConnectorPosTanX2 = params.terminals[nTerminal].crossConnectorsRelative[nTrackEdge].posTanX2
			local yShift = cpl.width
			local platformBorderPosTanX2 = transfUtils.getExtrapolatedPosTanX2Continuation(crossConnectorPosTanX2, yShift)
			local myTransfAlongPlatformBorder = transfUtils.getTransf_ZShifted(
				moduleHelpers.getPlatformObjectTransf_AlwaysVertical(platformBorderPosTanX2),
				result.laneZs[nTerminal]
			)
			local step0To1 = moduleHelpers.flatAreas.getMNAdjustedValue_0To1_Cycling(params, slotId, _nAdjustableSteps)
			local xAdjustedTransf = slotTransf
			for n = 13, 15, 1 do
				xAdjustedTransf[n] = slotTransf[n] + (myTransfAlongPlatformBorder[n] - slotTransf[n]) * step0To1
			end

			moduleHelpers.flatAreas.addExitPole(result, xAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)
			moduleHelpers.flatAreas.addPassengerLaneToStreet(result, xAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)

			if result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal] == nil then
				result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal] = {}
			end
			table.insert(
				result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal],
				{
					t = nTerminal,
					-- lanePosTanX2 = cpl.posTanX2,
					pos = transfUtils.transf2Position(xAdjustedTransf),
				}
			)
		end,

		getModelsFn = function(params)
			local variant = (params ~= nil and type(params.variant) == 'number') and params.variant or 0
			local deltaX = moduleHelpers.flatAreas.getFromVariant_0_to_1(variant, _nAdjustableSteps)
			-- local arrowModelId = 'lollo_freestyle_train_station/icon/square_blue.mdl'
			local arrowModelId = 'lollo_freestyle_train_station/icon/arrows_mid_blue.mdl'
			local arrowModelTransf = {0, 0, 1, 0,  0, 1, 0, 0,  -1, 0, 0, 0,  2, 2, 0, 1}
			if deltaX < 0 then
				arrowModelId = 'lollo_freestyle_train_station/icon/arrow_blue.mdl'
				arrowModelTransf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  1, 0, 0, 1}
			elseif deltaX > 0 then
				arrowModelId = 'lollo_freestyle_train_station/icon/arrow_blue.mdl'
				arrowModelTransf = {-1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1, 0,  -1, 0, 0, 1}
			end
			return {
				{
					id = 'lollo_freestyle_train_station/asset/era_c_perron_number.mdl',
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  -1, 0, 0, 1},
				},
				{
					id = arrowModelId,
					transf = arrowModelTransf,
				},
			}
		end
	}
end
