local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-road-access", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("FlushPassengerExitOuterName"),
			description = _("FlushPassengerExitOuterDesc"),
			icon = "ui/lollo_freestyle_train_station/flushPassengerExitOuter.tga"
		},
		metadata = { },
		order = {
			value = 11,
		},
		type = _constants.flushExitModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			-- LOLLO NOTE tag looks like '__module_201030', never mind what you write into it, the game overwrites it
			-- in base_config.lua
			-- Set it into the models, so the game knows what module they belong to.

			local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf_Limited(params, slotId, slotTransf)

			moduleHelpers.flatAreas.addExitPole(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)
			moduleHelpers.flatAreas.addPassengerLaneToStreet(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			if result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal] == nil then
				result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal] = {}
			end
			table.insert(
				result.terminateConstructionHookInfo.autoStitchablePositions[nTerminal],
				{
					t = nTerminal,
					lanePosTanX2 = cpl.posTanX2,
					pos = transfUtils.transf2Position(zAdjustedTransf),
				}
			)
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/asset/era_c_perron_number.mdl',
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  -1, 0, 0, 1},
				},
			}
		end
	}
end
