local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local logger = require('lollo_freestyle_train_station.logger')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local slotHelpers = require('lollo_freestyle_train_station.slotHelpers')
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "passenger-road-access", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("PassengerStationSquareName"),
		description = _("PassengerStationSquareDesc"),
		icon = "ui/lollo_freestyle_train_station/passengerStationSquare.tga"
	},
	metadata = { },
	order = {
		value = 1, -- LOLLO NOTE put this first to speed up station configuration, since it has very few slots
	},
	type = _constants.passengerStationSquareModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not nTrackEdge or not baseId then return end

		local platformLiftId = slotHelpers.mangleId(nTerminal, nTrackEdge, _constants.idBases.platformLiftSlotId)
		local sideLiftId = slotHelpers.mangleId(nTerminal, nTrackEdge, _constants.idBases.sideLiftSlotId)
		local buildingHeight = (params.modules[platformLiftId] ~= nil or params.modules[sideLiftId] ~= nil)
			and moduleHelpers.lifts.tryGetLiftHeight(params, nTerminal, nTrackEdge, slotId)
			or 0
		if not(buildingHeight) then return end
		logger.print('buildingHeight =', buildingHeight)

		local eraPrefix = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
		local modelId = nil
		if eraPrefix == moduleHelpers.eras.era_a.prefix then
			modelId = 'lollo_freestyle_train_station/lift/era_a_station_square.mdl'
		elseif eraPrefix == moduleHelpers.eras.era_b.prefix then
			modelId = 'lollo_freestyle_train_station/lift/era_b_station_square.mdl'
		else
			modelId = 'lollo_freestyle_train_station/lift/station_square.mdl'
		end
		result.models[#result.models + 1] = {
			id = modelId,
			slotId = slotId,
			transf = transfUtilsUG.mul(
				slotTransf,
				{ 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, -buildingHeight, 1 }
			),
			tag = tag
		}

		moduleHelpers.lifts.doTerrain4SideLifts(buildingHeight, slotTransf, result,
		_constants.era_c_groundFacesFillKey, _constants.era_c_groundFacesStrokeOuterKey)
	end,

	getModelsFn = function(params)
		return {
			{
				id = 'lollo_freestyle_train_station/lift/station_square.mdl',
				transf = { 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 },
			},
		}
	end
}

end
