local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local logger = require('lollo_freestyle_train_station.logger')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local slotHelpers = require('lollo_freestyle_train_station.slotHelpers')
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "passenger-road-access", "passenger-road-access-axial", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("PassengerStationSquarePlainName"),
		description = _("PassengerStationSquarePlainDesc"),
		icon = "ui/lollo_freestyle_train_station/passengerStationSquarePlain.tga"
	},
	metadata = { },
	order = {
		value = 2, -- LOLLO NOTE put this first to speed up station configuration, since it has very few slots
	},
	type = _constants.passengerStationSquareModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not nTrackEdge or not baseId then return end

		local eraPrefix = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
		local groundFacesFillKey = nil
		local groundFacesStrokeOuterKey = nil
		local modelId = nil
		if eraPrefix == moduleHelpers.eras.era_a.prefix then
			groundFacesFillKey = _constants.era_a_groundFacesFillKey
			groundFacesStrokeOuterKey = _constants.era_a_groundFacesStrokeOuterKey
			modelId = 'lollo_freestyle_train_station/lift/era_a_station_square_plain.mdl'
		elseif eraPrefix == moduleHelpers.eras.era_b.prefix then
			groundFacesFillKey = _constants.era_b_groundFacesFillKey
			groundFacesStrokeOuterKey = _constants.era_b_groundFacesStrokeOuterKey
			modelId = 'lollo_freestyle_train_station/lift/era_b_station_square_plain.mdl'
		else
			groundFacesFillKey = _constants.era_c_groundFacesFillKey
			groundFacesStrokeOuterKey = _constants.era_c_groundFacesStrokeOuterKey
			modelId = 'lollo_freestyle_train_station/lift/station_square_plain.mdl'
		end
		result.models[#result.models + 1] = {
			id = modelId,
			slotId = slotId,
			-- transf = transfUtilsUG.mul(
			-- 	slotTransf,
			-- 	{ 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 }
			-- ),
			transf = transfUtils.getTransf_ZRotatedP90(slotTransf),
			tag = tag
		}

		moduleHelpers.flatAreas.doTerrain4StationSquare(0, slotTransf, result, groundFacesFillKey, groundFacesStrokeOuterKey)
	end,

	getModelsFn = function(params)
		return {
			{
				id = 'lollo_freestyle_train_station/lift/station_square_plain.mdl',
				transf = { 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 },
			},
		}
	end
}

end
