local _constants = require('lollo_freestyle_train_station.constants')
-- local colliderutil = require "colliderutil"
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "street access", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("FlatPassengerArea5x5Name"),
		description = _("FlatPassengerArea5x5Desc"),
		icon = "ui/construction/station/street/cargo_area_inner_12x12.tga"
	},
	metadata = { },
	order = {
		value = 11,
	},
	-- skipCollision = true,
	type = _constants.flatPassengerArea5x5ModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not baseId then return end

		result.models[#result.models + 1] = {
			id = _constants.flatPassengerArea5x5ModelFileName,
			slotId = slotId,
			transf = slotTransf,
			tag = _constants.terminalModelTag
		}
		-- result.models[#result.models + 1] = {
		-- 	id = 'lollo_freestyle_train_station/icon/green.mdl',
		-- 	slotId = slotId,
		-- 	transf = slotTransf,
		-- 	tag = _constants.terminalModelTag
		-- }

		local groundFace = {
			{-3, -3.5, 0, 1},
			{-3, 3.5, 0, 1},
			{6, 3.5, 0, 1},
			{6, -3.5, 0, 1},
		}
		modulesutil.TransformFaces(slotTransf, groundFace)
		result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, 'shared/asphalt_01.gtex.lua')

		local terrainAlignmentList = {
			faces = {
				{
					{-2.5, -3.5, 0, 1},
					{-2.5, 3.5, 0, 1},
					{1, 3.5, 0, 1},
					{1, -3.5, 0, 1},
				},
				{
					{1, -3.5, 0, 1},
					{1, 3.5, 0, 1},
					{6, 3.5, -1.2, 1},
					{6, -3.5, -1.2, 1},
				}
			},
			optional = true,
        	slopeHigh = 10, --99,
        	slopeLow = 0.9, --0.1,
			type = 'EQUAL',
		}
		for _, face in pairs(terrainAlignmentList.faces) do
			modulesutil.TransformFaces(slotTransf, face)
		end
		-- result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(terrainFaces, 0)
		result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList

		-- LOLLO TODO add colliders to flat and sloped areas, using the model colliders.
		-- If you don't define them, they won't work and you won't be able to configure the station.
		-- If you define them, it won't work anyway, unless you set skipCollision = true in the construction
		-- Perhaps you bury them into the ground, like with the lorry station?
	end,

	getModelsFn = function(params)
		return {
			{
				id = _constants.flatPassengerArea5x5ModelFileName,
				transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
