local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "stairs-to-road", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("FlatStairsSteepName"),
		description = _("FlatStairsSteepDesc"),
		icon = "ui/lollo_freestyle_train_station/stairs_steep.tga"
	},
	metadata = { },
	order = {
		value = 1,
	},
	type = _constants.flatStairsModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not baseId then return end

		local zAdjustedTransf = moduleHelpers.flatAreas.getMNAdjustedTransf_Limited(params, slotId, slotTransf)

		result.models[#result.models + 1] = {
			id = _constants.flatStairsSteepModelFileName,
			slotId = slotId,
			transf = zAdjustedTransf,
			tag = tag
		}

		moduleHelpers.flatAreas.addLaneToStreet(result, zAdjustedTransf, tag, slotId, params, nTerminal, nTrackEdge)

		local groundFace = {
			{-1, -2, 0, 1},
			{-1, 2, 0, 1},
			{2.25, 2, 0, 1},
			{2.25, -2, 0, 1},
		}
		modulesutil.TransformFaces(zAdjustedTransf, groundFace)
		result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, 'shared/asphalt_01.gtex.lua')

		local terrainAlignmentList = {
			faces = {
				-- {
				-- 	{-2, -2, 0, 1},
				-- 	{-2, 2, 0, 1},
				-- 	{-1, 2, 0, 1},
				-- 	{-1, -2, 0, 1},
				-- },
				{
					{-1, -2, 0, 1},
					{-1, 2, 0, 1},
					{2.25, 2, -_constants.stairsHeight, 1},
					{2.25, -2, -_constants.stairsHeight, 1},
				}
			},
			optional = true,
        	slopeHigh = 10, --99,
			slopeLow = 0.9, --0.1,
			type = 'EQUAL',
		}
		for _, face in pairs(terrainAlignmentList.faces) do
			modulesutil.TransformFaces(zAdjustedTransf, face)
		end
		-- result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(terrainFaces, 0)
		result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList
	end,

	getModelsFn = function(params)
		return {
			{
				id = _constants.flatStairsSteepModelFileName,
				transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
