local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "street access", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("PassengerStationSquarePlainName"),
		description = _("PassengerStationSquarePlainDesc"),
		icon = "ui/construction/station/street/cargo_area_inner_12x12.tga"
	},
	metadata = { },
	order = {
		value = 1,
	},
	type = _constants.passengerStationSquareModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not nTrackEdge or not baseId then return end

		local buildingHeight, buildingModelId = moduleHelpers.tryGetSideLiftProperties(params, nTerminal, nTrackEdge)
		if not(buildingHeight) then return end

		result.models[#result.models + 1] = {
			id = 'lollo_freestyle_train_station/lift/station_square_plain.mdl',
			slotId = slotId,
			transf = transfUtilsUG.mul(
				slotTransf,
				{ 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, -buildingHeight - 0.8, 1 }
			),
			tag = tag
		}

		moduleHelpers.doTerrain4SideLifts(buildingHeight, slotTransf, result)
	end,

	getModelsFn = function(params)
		return {
			{
				id = 'lollo_freestyle_train_station/lift/station_square_plain.mdl',
				transf = { 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 },
			},
		}
	end
}

end
