local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = -1,
		yearTo = -1
	},
	cost = {
		price = 0,
	},
	category = {
		-- categories = { "cargo", },
	},
	description = {
		name = _("Terminal"),
		description = _("Terminal, can only be deleted, build this with the waypoints"),
		icon = "ui/construction/station/street/cargo_area_inner_12x12.tga"
	},
	metadata = { },
	order = {
		value = 1,
	},
	skipCollision = true,
	type = _constants.passengerTerminalModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not baseId then return end

		-- print('LOLLO passenger terminal module received slotId, nTerminal, nTrackEdge, baseId = ', slotId, nTerminal, nTrackEdge, baseId)
		-- print('LOLLO result =') debugPrint(result)
		-- print('slotTransf =') debugPrint(slotTransf) -- LOLLO NOTE we only use slotTransf to place the slot! The coords are absolute.
		-- print('params =') debugPrint(params)
		-- params are the station params
		-- addModelFn(_constants.cargoAreaInner12x12ModelFileName, transf.transl(vec3.new(0, 0, 0)), modelTag)
		local mainTransf = params.mainTransf
		local inverseMainTransf = transfUtils.getInverseTransf(mainTransf)

		result.models[#result.models + 1] = {
			id = 'lollo_freestyle_train_station/asset/terminal_signal.mdl',
			slotId = slotId,
			transf = slotTransf,
			tag = _constants.terminalModelTag
		}
		-- result.models[#result.models + 1] = {
		-- 	id = 'lollo_freestyle_train_station/icon/green.mdl',
		-- 	slotId = slotId,
		-- 	transf = slotTransf,
		-- 	tag = _constants.terminalModelTag
		-- }

		-- start from 3 to avoid deco peeping out of the platform
		local isTrackOnPlatformLeft = params.terminals[nTerminal].isTrackOnPlatformLeft
		local xShift = 2
		for i = 3, #params.terminals[nTerminal].centrePlatforms, _constants.terminalAssetStep do
			local cpl = params.terminals[nTerminal].centrePlatforms[i]
			local platformWidth = params.terminals[nTerminal].centrePlatforms[i].width
			local yShift = isTrackOnPlatformLeft and platformWidth * 0.2 + 0.9 or -platformWidth * 0.2 - 0.9
			local posTanX2 = transfUtils.getPosTanX2Transformed(cpl.posTanX2, inverseMainTransf)
			local transf = moduleHelpers.getTerminalDecoTransf(posTanX2)
			result.models[#result.models + 1] = {
				-- LOLLO TODO display the correct station name. With cargo + passenger stations, this is broken
				id = 'lollo_freestyle_train_station/asset/era_c_station_name.mdl',
				slotId = slotId,
				transf = transfUtilsUG.mul(transf, { 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  xShift, yShift, 3.9, 1 }),
				tag = _constants.terminalModelTag
			}
			result.models[#result.models + 1] = {
				id = 'lollo_freestyle_train_station/asset/era_c_perron_pillar.mdl',
				slotId = slotId,
				transf = transfUtilsUG.mul(transf, { 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1.2, 0,  xShift, yShift, 0.4, 1 }),
				tag = _constants.terminalModelTag
			}
		end
		for i = 4, #params.terminals[nTerminal].centrePlatforms, _constants.terminalAssetStep do
			-- these must avoid the underpass buildings
			local cpl = params.terminals[nTerminal].centrePlatforms[i]
			local platformWidth = params.terminals[nTerminal].centrePlatforms[i].width
			local yShift = isTrackOnPlatformLeft and platformWidth * 0.2 + 0.9 or -platformWidth * 0.2 - 0.9
			local posTanX2 = transfUtils.getPosTanX2Transformed(cpl.posTanX2, inverseMainTransf)
			local transf = moduleHelpers.getTerminalDecoTransf(posTanX2)
			result.models[#result.models + 1] = {
				id = 'lollo_freestyle_train_station/asset/era_c_perron_number_single.mdl',
				slotId = slotId,
				transf = isTrackOnPlatformLeft
					and transfUtilsUG.mul(transf, { 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  xShift, yShift, 4.6, 1 })
					or transfUtilsUG.mul(transf, { 1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1, 0,  xShift, yShift, 4.6, 1 }),
				tag = _constants.terminalModelTag
			}
			-- the model index must be in base 0 !
			result.labelText[#result.models - 1] = { tostring(nTerminal), tostring(nTerminal)}
			result.models[#result.models + 1] = {
				id = 'lollo_freestyle_train_station/asset/era_c_perron_pillar.mdl',
				slotId = slotId,
				transf = transfUtilsUG.mul(transf, { 1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1.2, 0,  xShift, yShift, 0.4, 1 }),
				tag = _constants.terminalModelTag
			}
		end
		for i = 2, #params.terminals[nTerminal].centrePlatforms, _constants.terminalAssetStep do
			local cpl = params.terminals[nTerminal].centrePlatforms[i]
			local platformWidth = params.terminals[nTerminal].centrePlatforms[i].width
			local yShift = isTrackOnPlatformLeft and platformWidth * 0.2 + 0.9 or -platformWidth * 0.2 - 0.9
			local posTanX2 = transfUtils.getPosTanX2Transformed(cpl.posTanX2, inverseMainTransf)
			local transf = moduleHelpers.getTerminalDecoTransf(posTanX2)
			result.models[#result.models + 1] = {
				-- id = 'lollo_freestyle_train_station/asset/tabellone_standing.mdl',
				id = 'lollo_freestyle_train_station/asset/arrivi.mdl',
				slotId = slotId,
				transf = transfUtilsUG.mul(transf, { 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0.7 + xShift, yShift, 1.1, 1 }),
				tag = _constants.terminalModelTag
			}
			result.models[#result.models + 1] = {
				-- id = 'lollo_freestyle_train_station/asset/tabellone_standing.mdl',
				id = 'lollo_freestyle_train_station/asset/partenze.mdl',
				slotId = slotId,
				transf = transfUtilsUG.mul(transf, { 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  -0.7 + xShift, yShift, 1.1, 1 }),
				tag = _constants.terminalModelTag
			}
		end
	end,

	getModelsFn = function(params)
		return {
			{
				id = _constants.terminalModelFileName,
				transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
