local _constants = require('lollo_freestyle_train_station.constants')

function data()
	return {
		availability = {
			yearFrom = _constants.eras.era_b.startYear,
			yearTo = 0
		},
		category = {
			categories = { "deco", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _('PlatformEraASwitcherName'),
			description = _('PlatformEraASwitcherDesc'),
			icon = "ui/lollo_freestyle_train_station/PlatformEraASwitcher.tga"
		},
		metadata = { },
		order = {
			value = 31,
		},
		type = _constants.era_a_platformModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			-- print('trackSpeedUndefined.module.updateFn ending')
			-- result.models[#result.models + 1] = {
			-- 	id = _constants.emptyModelFileName,
			-- 	slotId = slotId,
			-- 	transf = slotTransf,
			-- 	tag = tag
			-- }
		end,

		getModelsFn = function(params)
			return {
				-- {
				-- 	id = _constants.emptyModelFileName,
				-- 	transf = _constants.idTransf,
				-- },
			}
		end
	}
end
