local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"

function data()

return { 
	availability = {
		yearFrom = 1920,
		yearTo = 0,
	},
	cost = {
		price = 25000,
	},
	description = {
		name = _("Lollo Standard tracks"),
		description = _("Standard tracks with catenary and limited speed capabilities."),
		icon = "ui/construction/station/rail/modular_station/track_catenary.tga"
	},
	category = {
		categories = { "tracks", },
	},
	--buildMode = "MULTI",
	type = "track",
	order = {
		value = 260,
	},
	metadata = {
		track = true,
	},
	
    updateFn = function(result, transform, tag, slotId, addModuleFn, params)
        -- LOLLO TODO add something to result.edgeLists
	end,
	
	getModelsFn = function()
		
		local result = {
		}
		
		return result
	end
}

end
