local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "passenger-platform-extensions", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("SlopedPassengerArea1x5Name"),
		description = _("SlopedPassengerArea1x5Desc"),
		icon = "ui/lollo_freestyle_train_station/passenger_area_1x5.tga"
	},
	metadata = { },
	order = {
		value = 21,
	},
	type = _constants.slopedPassengerArea1x5ModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not nTrackEdge or not baseId then return end

		local paths = moduleHelpers.slopedAreas.getPaths(params, nTerminal, nTrackEdge, 5)
		-- print('paths =') debugPrint(paths)
		for ii = 1, #paths do
			local posTanX2 = transfUtils.getPosTanX2Transformed(paths[ii].posTanX2, result.inverseMainTransf)
			local myTransf = moduleHelpers.getPlatformObjectTransf_WithYRotation(posTanX2)
			result.models[#result.models+1] = {
				id = _constants.slopedPassengerArea1x5ModelFileName,
				transf = transfUtilsUG.mul(
					myTransf,
					{ 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, 0, _constants.platformSideBitsZ, 1 }
				),
				tag = tag
			}
		end

		if params.terminals[nTerminal].centrePlatforms[nTrackEdge].type == 0 then -- only align terrain if on ground
			local face = {
				{-3, -13.5, 0, 1},
				{-3, 13.5, 0, 1},
				{3, 13, 0, 1},
				{3, -13, 0, 1},
			}
			modulesutil.TransformFaces(slotTransf, face)
			result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(face, 'shared/asphalt_01.gtex.lua')
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(face, 0, 'EQUAL', 1, 0.5)
		end
	end,

	getModelsFn = function(params)
		local results = {}
		for y = -2, 2 do
			results[#results+1] = {
				id = _constants.slopedPassengerArea1x5ModelFileName,
				transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
			}
		end
		return results
	end
}

end
