local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local logger = require('lollo_freestyle_train_station.logger')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = -1,
			yearTo = -1
		},
		category = {
			categories = { "passenger-up-and-down", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SubwayName"),
			description = _("SubwayDesc"),
			icon = "ui/lollo_freestyle_train_station/subway.tga"
		},
		metadata = {
			-- no moreCapacity here, we do it differently
			-- moreCapacity = {
			-- 	cargo = 0,
			-- 	passenger = 20
			-- },
		},
		order = {
			value = 55,
		},
		type = _constants.subwayModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			-- local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			logger.infoOut('subway.module.updateFn starting')
			logger.infoOut('slotId =', slotId, 'subway.module.updateScriptParams =', updateScriptParams)
			-- logger.infoOut('params.subways =', params.subways})
			local subwayConFileName = params and params.subways and params.subways[slotId] and params.subways[slotId].subwayConFileName
			logger.infoOut('subwayConFileName =', subwayConFileName)

			-- test code BEGIN
			-- result.models[#result.models+1] = {
			-- 	id = 'lollo_freestyle_train_station/icon/blue_w_message.mdl',
			-- 	slotId = slotId,
			-- 	transf = slotTransf,
			-- 	tag = tag
			-- }
			-- result.labelText[#result.models - 1] = { tostring(slotId), tostring(slotId) }
			-- test code END

            local eraPrefix = moduleHelpers.getEraPrefix(params, 1, 1)
			if not(subwayConFileName) or subwayConFileName == ''
			or subwayConFileName == 'lollo_freestyle_train_station/subways/subway.con'
			or subwayConFileName == 'station/rail/lollo_freestyle_train_station/subway.con' -- OBSOLETE, it is here for compatibility with olde code
			then
				local modelId = nil
				if eraPrefix == moduleHelpers.eras.era_a.prefix then modelId = 'lollo_freestyle_train_station/subway/era_a_subway.mdl'
				elseif eraPrefix == moduleHelpers.eras.era_b.prefix then modelId = 'lollo_freestyle_train_station/subway/era_b_subway.mdl'
				else modelId = 'lollo_freestyle_train_station/subway/era_c_subway.mdl'
				end
				result.models[#result.models + 1] = {
					id = modelId,
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances = result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances + 10
				moduleHelpers.subways.doTerrain4Subways(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			elseif subwayConFileName == 'lollo_freestyle_train_station/subways/subwayHollowayMedium.con'
			or subwayConFileName == 'station/rail/lollo_freestyle_train_station/subwayHollowayMedium.con' -- OBSOLETE, it is here for compatibility with olde code
			then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/subway/holloway_9_5_8.mdl',
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				local modelId = 'lollo_freestyle_train_station/subway/holloway_signs_era_c.mdl'
				if eraPrefix == _constants.eras.era_a.prefix then
					modelId = 'lollo_freestyle_train_station/subway/holloway_signs_era_a.mdl'
				elseif eraPrefix == _constants.eras.era_b.prefix then
					modelId = 'lollo_freestyle_train_station/subway/holloway_signs_era_b.mdl'
				end
                result.models[#result.models + 1] = {
					id = modelId,
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances = result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances + 30
				moduleHelpers.subways.doTerrain4HollowayMedium(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			elseif subwayConFileName == 'lollo_freestyle_train_station/subways/subwayHollowayLarge.con'
			or subwayConFileName == 'station/rail/lollo_freestyle_train_station/subwayHollowayLarge.con' -- OBSOLETE, it is here for compatibility with olde code
			then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/subway/holloway_13_5_8.mdl',
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				local modelId = 'lollo_freestyle_train_station/subway/holloway_signs_era_c.mdl'
				if eraPrefix == _constants.eras.era_a.prefix then
					modelId = 'lollo_freestyle_train_station/subway/holloway_signs_era_a.mdl'
				elseif eraPrefix == _constants.eras.era_b.prefix then
					modelId = 'lollo_freestyle_train_station/subway/holloway_signs_era_b.mdl'
				end
                result.models[#result.models + 1] = {
					id = modelId,
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances = result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances + 40
				moduleHelpers.subways.doTerrain4HollowayLarge(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			elseif subwayConFileName == 'lollo_freestyle_train_station/subways/subwayClaphamLarge.con'
			or subwayConFileName == 'station/rail/lollo_freestyle_train_station/subwayClaphamLarge.con' -- OBSOLETE, it is here for compatibility with olde code
			then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/subway/clapham_13_4_8.mdl',
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				local modelId = 'lollo_freestyle_train_station/subway/clapham_signs_era_c.mdl'
				if eraPrefix == _constants.eras.era_a.prefix then
					modelId = 'lollo_freestyle_train_station/subway/clapham_signs_era_a.mdl'
				elseif eraPrefix == _constants.eras.era_b.prefix then
					modelId = 'lollo_freestyle_train_station/subway/clapham_signs_era_b.mdl'
				end
                result.models[#result.models + 1] = {
					id = modelId,
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances = result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances + 40
				moduleHelpers.subways.doTerrain4ClaphamLarge(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			elseif subwayConFileName == 'lollo_freestyle_train_station/subways/subwayClaphamMedium.con'
			or subwayConFileName == 'station/rail/lollo_freestyle_train_station/subwayClaphamMedium.con' -- OBSOLETE, it is here for compatibility with olde code
			then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/subway/clapham_10_3_8.mdl',
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				local modelId = 'lollo_freestyle_train_station/subway/clapham_medium_signs_era_c.mdl'
				if eraPrefix == _constants.eras.era_a.prefix then
					modelId = 'lollo_freestyle_train_station/subway/clapham_medium_signs_era_a.mdl'
				elseif eraPrefix == _constants.eras.era_b.prefix then
					modelId = 'lollo_freestyle_train_station/subway/clapham_medium_signs_era_b.mdl'
				end
                result.models[#result.models + 1] = {
					id = modelId,
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances = result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances + 30
				moduleHelpers.subways.doTerrain4ClaphamMedium(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			elseif subwayConFileName == 'lollo_freestyle_train_station/subways/subwayClaphamSmall.con'
			or subwayConFileName == 'station/rail/lollo_freestyle_train_station/subwayClaphamSmall.con' -- OBSOLETE, it is here for compatibility with olde code
			then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/subway/clapham_6_3_8.mdl',
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				local modelId = 'lollo_freestyle_train_station/subway/clapham_medium_signs_era_c.mdl'
				if eraPrefix == _constants.eras.era_a.prefix then
					modelId = 'lollo_freestyle_train_station/subway/clapham_medium_signs_era_a.mdl'
				elseif eraPrefix == _constants.eras.era_b.prefix then
					modelId = 'lollo_freestyle_train_station/subway/clapham_medium_signs_era_b.mdl'
				end
                result.models[#result.models + 1] = {
					id = modelId,
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances = result.terminateConstructionHookInfo.extraCapacityFromSubwayEntrances + 20
				moduleHelpers.subways.doTerrain4ClaphamSmall(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			end
			-- print('subway.module.updateFn ending')
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/subway/era_c_subway.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
