local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local logger = require('lollo_freestyle_train_station.logger')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = -1,
			yearTo = -1
		},
		category = {
			categories = { "passenger-up-and-down", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SubwayName"),
			description = _("SubwayDesc"),
			icon = "ui/lollo_freestyle_train_station/subway.tga"
		},
		metadata = { },
		order = {
			value = 55,
		},
		type = _constants.subwayModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			-- local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			logger.print('subway.module.updateFn starting')
			logger.print('slotId =') logger.debugPrint(slotId)
			logger.print('updateScriptParams =') logger.debugPrint(updateScriptParams)
			logger.print('params.subways =') logger.debugPrint(params.subways)
			local subwayConFileName = params and params.subways and params.subways[slotId] and params.subways[slotId].subwayConFileName
			logger.print('subwayConFileName =', subwayConFileName or 'NIL')

			if not(subwayConFileName) or subwayConFileName == '' or subwayConFileName == 'station/rail/lollo_freestyle_train_station/subway.con' then
				local era = moduleHelpers.getEraPrefix(params, 1, 1)
				local modelId = nil
				if era == moduleHelpers.eras.era_a.prefix then modelId = 'lollo_freestyle_train_station/subway/era_a_subway.mdl'
				elseif era == moduleHelpers.eras.era_b.prefix then modelId = 'lollo_freestyle_train_station/subway/era_b_subway.mdl'
				else modelId = 'lollo_freestyle_train_station/subway/era_c_subway.mdl'
				end
				result.models[#result.models + 1] = {
					id = modelId,
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}

				moduleHelpers.subways.doTerrain4Subways(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			elseif subwayConFileName == 'station/rail/lollo_freestyle_train_station/subwayHollowayMedium.con' then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/subway/holloway_9_5_8.mdl',
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				moduleHelpers.subways.doTerrain4HollowayMedium(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			elseif subwayConFileName == 'station/rail/lollo_freestyle_train_station/subwayHollowayLarge.con' then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/subway/holloway_13_5_8.mdl',
					slotId = slotId,
					transf = slotTransf,
					tag = tag
				}
				moduleHelpers.subways.doTerrain4HollowayLarge(result, slotTransf, _constants.era_c_groundFacesStrokeOuterKey)
			end
			-- print('subway.module.updateFn ending')
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/subway/era_c_subway.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
