local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = -1,
		yearTo = -1
	},
	cost = {
		price = 0,
	},
	category = {
		-- categories = { "cargo", },
	},
	description = {
		name = _("Terminal"),
		description = _("Terminal, can only be deleted, build this with the waypoints"),
		icon = "ui/construction/station/street/cargo_area_inner_12x12.tga"
	},
	metadata = {
		-- cargo = true,
	},
	order = {
		value = 1,
	},
	type = _constants.terminalModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not baseId then return end

		print('LOLLO terminal module received slotId, nTerminal, nTrackEdge, baseId = ', slotId, nTerminal, nTrackEdge, baseId)
		-- print('LOLLO result =') debugPrint(result)
		print('transform =') debugPrint(transform)
		-- print('params =') debugPrint(params)
		-- params are the station params
		-- addModelFn(_constants.cargoAreaInner12x12ModelFileName, transf.transl(vec3.new(0, 0, 0)), modelTag)

		local mainTransf = params.mainTransf
		local inverseMainTransf = transfUtils.getInverseTransf(mainTransf)

		-- LOLLO TODO instead of this peg, display a lot of platform signs, like with the waiting areas
		for i = 1, #params.terminals[nTerminal].waitingAreaPositions, _constants.terminalDecoStep do
			print('i =', i)
			local transf = moduleHelpers.getTerminalDecoTransf(
				params.terminals[nTerminal].waitingAreaPositions[i],
				inverseMainTransf
			)
			result.models[#result.models + 1] = {
				id = _constants.terminalModelFileName,
				slotId = slotId,
				transf = transfUtilsUG.mul(transf, transform),
				tag = _constants.terminalModelTag
			}
		end

		-- local face = {
		-- 	{-7, -7, 0, 1},
		-- 	{-7, 7, 0, 1},
		-- 	{7, 7, 0, 1},
		-- 	{7, -7, 0, 1},
		-- }
		-- modulesutil.TransformFaces(transform, face)
		-- result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(face, 'shared/asphalt_01.gtex.lua')
		-- result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(face)
	end,

	getModelsFn = function(params)
		return {
			{
				id = _constants.terminalModelFileName,
				transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
