local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local logger = require('lollo_freestyle_train_station.logger')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "track-crossings", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("TrackCrossingTwoStairsName"),
			description = _("TrackCrossingTwoStairsDesc"),
			icon = "ui/lollo_freestyle_train_station/trackCrossingTwoStairs.tga"
		},
		metadata = { },
		order = {
			value = 61,
		},
		type = _constants.trackCrossingModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local eraPrefix = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
			local modelId = nil
			if eraPrefix == moduleHelpers.eras.era_a.prefix then modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_a_trackCrossingTwoStairs.mdl'
			elseif eraPrefix == moduleHelpers.eras.era_b.prefix then modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_b_trackCrossingTwoStairs.mdl'
			else modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_c_trackCrossingTwoStairs.mdl'
			end
			result.models[#result.models + 1] = {
				id = modelId,
				slotId = slotId,
				transf = slotTransf,
				tag = tag
			}

			-- add link to platform
			local trackCrossingPos = transfUtils.getPositionRaisedBy(transfUtils.transf2Position(slotTransf), _constants.trackCrossingZ)
			if not(trackCrossingPos) then
				logger.warn('trackCrossingPos is NIL')
				return
			end
			local crossConnectorPos = params.terminals[nTerminal].crossConnectorsRelative[nTrackEdge].posTanX2[1][1]
			result.models[#result.models+1] = {
				id = _constants.passengerLaneModelId,
				transf = transfUtils.get1MLaneTransf(
					trackCrossingPos,
					transfUtils.getPositionRaisedBy(crossConnectorPos, result.laneZs[nTerminal])
				)
			}
			-- add link toward opposite platform
			local oppositeCrossConnectorPos = {
				trackCrossingPos[1] - crossConnectorPos[1] + trackCrossingPos[1],
				trackCrossingPos[2] - crossConnectorPos[2] + trackCrossingPos[2],
				trackCrossingPos[3] + result.laneZs[nTerminal] - _constants.trackCrossingZ,
			}
			result.models[#result.models+1] = {
				id = _constants.passengerLaneModelId,
				transf = transfUtils.get1MLaneTransf(
					trackCrossingPos,
					oppositeCrossConnectorPos
				)
			}

			if result.terminateConstructionHookInfo.trackCrossingOppositePositions[nTerminal] == nil then
				result.terminateConstructionHookInfo.trackCrossingOppositePositions[nTerminal] = {}
			end
			table.insert(
				result.terminateConstructionHookInfo.trackCrossingOppositePositions[nTerminal],
				{
					t = nTerminal,
					-- lanePosTanX2 = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge].posTanX2,
					pos = oppositeCrossConnectorPos,
					isProperLink = true, -- this is to avoid duplicate edges
				}
			)
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/railroad/trackCrossing/era_c_trackCrossingTwoStairs.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
