local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local logger = require('lollo_freestyle_train_station.logger')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "track-crossings", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("TrackCrossingTwoStairsName"),
			description = _("TrackCrossingTwoStairsDesc"),
			icon = "ui/lollo_freestyle_train_station/trackCrossingTwoStairs.tga"
		},
		metadata = { },
		order = {
			value = 61,
		},
		type = _constants.trackCrossingModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
			local _eraPrefix = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)
			local _laneZ = result.laneZs[nTerminal]
			local _isCargoTerminal = _terminalData.isCargo

			local modelId = nil
			if _laneZ > 0.9 then
				if _eraPrefix == moduleHelpers.eras.era_a.prefix then modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_a_trackCrossingTwoStairs.mdl'
				elseif _eraPrefix == moduleHelpers.eras.era_b.prefix then modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_b_trackCrossingTwoStairs.mdl'
				else modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_c_trackCrossingTwoStairs.mdl'
				end
			elseif _laneZ > 0.6 then
				if _eraPrefix == moduleHelpers.eras.era_a.prefix then modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_a_trackCrossingTwoStairs_low.mdl'
				elseif _eraPrefix == moduleHelpers.eras.era_b.prefix then modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_b_trackCrossingTwoStairs_low.mdl'
				else modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_c_trackCrossingTwoStairs_low.mdl'
				end
			else
				if _eraPrefix == moduleHelpers.eras.era_a.prefix then modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_a_trackCrossingTwoStairs_flat.mdl'
				elseif _eraPrefix == moduleHelpers.eras.era_b.prefix then modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_b_trackCrossingTwoStairs_flat.mdl'
				else modelId = 'lollo_freestyle_train_station/railroad/trackCrossing/era_c_trackCrossingTwoStairs_flat.mdl'
				end
			end
			result.models[#result.models + 1] = {
				id = modelId,
				slotId = slotId,
				transf = slotTransf,
				tag = tag
			}

			-- add link from platform border into track crossing
			local platformBorderPos = transfUtils.getPositionRaisedBy(
				_terminalData.crossConnectorsRelative[nTrackEdge].posTanX2[1][1],
				_laneZ
			)
			-- place this off the track centre so it won't overlap the track node (it happened!)
			local trackCrossingPos1 = transfUtils.getPositionRaisedBy(
				transfUtils.getExtrapolatedPosX2Continuation(
					_terminalData.crossConnectorsRelative[nTrackEdge].posTanX2[1][1],
					transfUtils.transf2Position(slotTransf),
					-1
				),
				_constants.trackCrossingZ
			)
			local trackCrossingPos2 = transfUtils.getPositionRaisedBy(
				transfUtils.getExtrapolatedPosX2Continuation(
					_terminalData.crossConnectorsRelative[nTrackEdge].posTanX2[1][1],
					transfUtils.transf2Position(slotTransf),
					1
				),
				_constants.trackCrossingZ
			)
			result.models[#result.models+1] = {
				id = _constants.passengerLaneModelId,
				transf = transfUtils.get1MLaneTransf(
					platformBorderPos,
					trackCrossingPos1
				)
			}
			result.models[#result.models+1] = {
				id = _constants.passengerLaneModelId,
				transf = transfUtils.get1MLaneTransf(
					trackCrossingPos1,
					trackCrossingPos2
				)
			}

			-- add link from track crossing to opposite platform border,
			-- where its cross connector would be, if they were perfectly regular
			-- and the opposite platform was facing mine (impossible coz two platforms cannot share the same track)
			-- With cargo, at present, we cannot get a full connection between far away station sides.
			local trackCentrePos = transfUtils.getPositionRaisedBy(transfUtils.transf2Position(slotTransf), _constants.trackCrossingZ)
			if not(trackCentrePos) then
				logger.warn('trackCrossingTwoStairs: trackCentrePos is NIL')
				return
			end
			local oppositeCrossConnectorPos = {
				trackCentrePos[1] - platformBorderPos[1] + trackCentrePos[1],
				trackCentrePos[2] - platformBorderPos[2] + trackCentrePos[2],
				trackCentrePos[3] + _laneZ - _constants.trackCrossingZ,
			}
			result.models[#result.models+1] = {
				id = _constants.passengerLaneModelId,
				transf = transfUtils.get1MLaneTransf(
					trackCrossingPos2,
					oppositeCrossConnectorPos
				)
			}

			-- mark positions along the border of the opposite platform, so they can be joined later
			if not(_isCargoTerminal) then
				if result.terminateConstructionHookInfo.trackCrossingOppositePositions[nTerminal] == nil then
					result.terminateConstructionHookInfo.trackCrossingOppositePositions[nTerminal] = {}
				end
				table.insert(
					result.terminateConstructionHookInfo.trackCrossingOppositePositions[nTerminal],
					{
						t = nTerminal,
						-- lanePosTanX2 = _terminalData.centrePlatformsRelative[nTrackEdge].posTanX2,
						pos = oppositeCrossConnectorPos,
						isProperLink = true, -- this is to avoid duplicate edges
					}
				)
			end
--[[
			-- only for cargo: link centre platforms to platform border
			local platformCentrePos
			if _isCargoTerminal then
				platformCentrePos = transfUtils.getPositionRaisedBy(
					_terminalData.crossConnectorsRelative[nTrackEdge].posTanX2[2][1],
					_laneZ
				)
				result.models[#result.models+1] = {
					id = _constants.passengerLaneModelId,
					transf = transfUtils.get1MLaneTransf(
						platformCentrePos,
						platformBorderPos
					)
				}
			end
]]
			if logger.isExtendedLog() then
--[[
				if platformCentrePos then
					result.models[#result.models+1] = {
						id = 'lollo_freestyle_train_station/icon/red.mdl',
						transf = {
							1, 0, 0, 0,
							0, 1, 0, 0,
							0, 0, nTerminal % 2 + 1, 0,
							platformCentrePos[1], platformCentrePos[2], platformCentrePos[3], 1
						}
					}
				end
]]
				result.models[#result.models+1] = {
					id = 'lollo_freestyle_train_station/icon/orange.mdl',
					transf = {
						1, 0, 0, 0,
						0, 1, 0, 0,
						0, 0, nTerminal % 2 + 1, 0,
						platformBorderPos[1], platformBorderPos[2], platformBorderPos[3], 1
					}
				}
				result.models[#result.models+1] = {
					id = 'lollo_freestyle_train_station/icon/yellow.mdl',
					transf = {
						1, 0, 0, 0,
						0, 1, 0, 0,
						0, 0, nTerminal % 2 + 1, 0,
						trackCrossingPos1[1], trackCrossingPos1[2], trackCrossingPos1[3], 1
					}
				}
				result.models[#result.models+1] = {
					id = 'lollo_freestyle_train_station/icon/blue.mdl',
					transf = {
						1, 0, 0, 0,
						0, 1, 0, 0,
						0, 0, nTerminal % 2 + 1, 0,
						trackCrossingPos2[1], trackCrossingPos2[2], trackCrossingPos2[3], 1
					}
				}
				result.models[#result.models+1] = {
					id = 'lollo_freestyle_train_station/icon/lilac.mdl',
					transf = {
						1, 0, 0, 0,
						0, 1, 0, 0,
						0, 0, nTerminal % 2 + 1, 0,
						oppositeCrossConnectorPos[1], oppositeCrossConnectorPos[2], oppositeCrossConnectorPos[3], 1
					}
				}
			end
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/railroad/trackCrossing/era_c_trackCrossingTwoStairs.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
