local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-up-and-down", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("TunnelStairsUpName"),
			description = _("TunnelStairsUpDesc"),
			icon = "ui/lollo_freestyle_train_station/tunnelStairsUp.tga"
		},
		metadata = { },
		order = {
			value = 50,
		},
		type = _constants.tunnelStairsUpModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
			local modelId = nil
			if era == moduleHelpers.eras.era_a.prefix then modelId = _constants.era_a_tunnelStairsUpModelId
			elseif era == moduleHelpers.eras.era_b.prefix then modelId = _constants.era_b_tunnelStairsUpModelId
			else modelId = _constants.era_c_tunnelStairsUpModelId
			end
			result.models[#result.models + 1] = {
				id = modelId,
				slotId = slotId,
				transf = slotTransf,
				tag = tag
			}
		end,

		getModelsFn = function(params)
			return {
				{
					id = _constants.era_c_tunnelStairsUpModelId,
					transf = _constants.idTransf,
				},
			}
		end
	}
end
