local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "passenger-up-and-down", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("TunnelStairsUpDownName"),
		description = _("TunnelStairsUpDownDesc"),
		icon = "ui/lollo_freestyle_train_station/tunnelStairsUpDown.tga"
	},
	metadata = { },
	order = {
		value = 51,
	},
	type = _constants.tunnelStairsUpDownModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not baseId then return end

		result.models[#result.models + 1] = {
			id = _constants.tunnelStairsUpDownModelId,
			slotId = slotId,
			transf = transfUtilsUG.mul(slotTransf, { 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 }),
			tag = tag
		}
	end,

	getModelsFn = function(params)
		return {
			{
				id = _constants.tunnelStairsUpDownModelId,
				transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
