local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "passenger-up-and-down", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("UnderpassName"),
		description = _("UnderpassDesc"),
		icon = "ui/lollo_freestyle_train_station/underpass.tga"
	},
	metadata = { },
	order = {
		value = 40,
	},
	type = _constants.underpassModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not nTrackEdge or not baseId then return end

		local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
		-- local era = cpl.era or moduleHelpers.eras.era_c.prefix
		local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
		local modelId = _constants.era_c_underpassBuilding10MModelFileName
		if era == moduleHelpers.eras.era_b.prefix then modelId = _constants.era_b_underpassBuilding10MModelFileName
		elseif era == moduleHelpers.eras.era_a.prefix then modelId = _constants.era_a_underpassBuilding10MModelFileName
		end
		-- if cpl.type == 1 then modelId = _constants.underpassBuildingWBottom10MModelFileName
		-- end
		result.models[#result.models + 1] = {
			id = modelId,
			slotId = slotId,
			transf = slotTransf,
			tag = tag
		}
	end,

	getModelsFn = function(params)
		return {
			{
				id = _constants.era_c_underpassBuilding10MModelFileName,
				transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
