local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-up-and-down", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("UnderpassStairsName"),
			description = _("UnderpassStairsDesc"),
			icon = "ui/lollo_freestyle_train_station/underpassStairs.tga"
		},
		metadata = {
			holeIIs = {
				-- 0, 1, 2, 3, 6, 7, 8, 9
				-- 0, 1, 2, 3, 8, 9
				0, 1, 2, 3, 4, 7, 8, 9
			},
		},
		order = {
			value = 41,
		},
		type = _constants.underpassModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
			local cpl = _terminalData.centrePlatformsRelative[nTrackEdge]
			local cplP1 = _terminalData.centrePlatformsRelative[nTrackEdge+1] or {}
			slotTransf = transfUtils.getTransf_ZShifted(
				moduleHelpers.getPlatformObjectTransf_WithYRotation(cpl.posTanX2),
				result.laneZs[nTerminal]
			)

			local era = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)
			local stairsModelId = nil
			if era == moduleHelpers.eras.era_a.prefix then stairsModelId = 'lollo_freestyle_train_station/underpass/era_a_underpass_stairs_10m.mdl'
			elseif era == moduleHelpers.eras.era_b.prefix then stairsModelId = 'lollo_freestyle_train_station/underpass/era_b_underpass_stairs_10m.mdl'
			else stairsModelId = 'lollo_freestyle_train_station/underpass/era_c_underpass_stairs_10m.mdl'
			end
			result.models[#result.models + 1] = {
				id = stairsModelId,
				slotId = slotId,
				transf = slotTransf,
				tag = tag
			}

			local floorModelId = 'lollo_freestyle_train_station/underpass/era_c_underpass_stairs_floor_10m.mdl'
			if era == moduleHelpers.eras.era_a.prefix then floorModelId = 'lollo_freestyle_train_station/underpass/era_a_underpass_stairs_floor_10m.mdl'
			elseif era == moduleHelpers.eras.era_b.prefix then floorModelId = 'lollo_freestyle_train_station/underpass/era_b_underpass_stairs_floor_10m.mdl'
			end
			-- exceptionally, underpasses need the paving material coz they are straight while curves are curvy
			if result.platformStyles[nTerminal] == _constants.platformStyles.era_b_db.moduleFileName then
				floorModelId = 'lollo_freestyle_train_station/underpass/era_b_db_underpass_stairs_floor_10m.mdl'
			elseif result.platformStyles[nTerminal] == _constants.platformStyles.era_c_db_1_stripe.moduleFileName then
				floorModelId = 'lollo_freestyle_train_station/underpass/era_b_db_underpass_stairs_floor_10m.mdl'
			elseif result.platformStyles[nTerminal] == _constants.platformStyles.era_c_fs_1_stripe.moduleFileName then
				floorModelId = 'lollo_freestyle_train_station/underpass/era_b_db_underpass_stairs_floor_10m.mdl'
			elseif result.platformStyles[nTerminal] == _constants.platformStyles.era_c_uk_2_stripes.moduleFileName then
				floorModelId = 'lollo_freestyle_train_station/underpass/era_b_db_underpass_stairs_floor_10m.mdl'
			elseif result.platformStyles[nTerminal] == _constants.platformStyles.era_c_db_2_stripes.moduleFileName then
				floorModelId = 'lollo_freestyle_train_station/underpass/era_c_db_2_stripes_underpass_stairs_floor_10m.mdl'
			end

			result.models[#result.models + 1] = {
				id = floorModelId,
				slotId = slotId,
				transf = slotTransf,
				tag = tag
			}

			if cpl.type ~= 1 and cplP1.type ~= 1 then -- skip it on bridges, otherwise it will make the underlying ground transparent. Interesting but unwanted.
				local groundFace = { -- the ground faces ignore z, the alignment lists don't
					{-4.5, -0.75, 0, 1},
					{-4.5, 0.75, 0, 1},
					{4.5, 0.75, 0, 1},
					{4.5, -0.75, 0, 1},
				}
				modulesutil.TransformFaces(slotTransf, groundFace)
				table.insert(
					result.groundFaces,
					{
						face = groundFace,
						loop = true,
						modes = {
							{
								-- key = 'lollo_freestyle_train_station/hole.lua',
								key = 'hole.lua',
								type = 'FILL',
							},
							-- {
							-- 	key = groundFacesStrokeOuterKey,
							-- 	type = 'STROKE_OUTER',
							-- }
						}
					}
				)
			end
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/underpass/era_c_underpass_stairs_10m.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
