local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-up-and-down", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("UnderpassName"),
			description = _("UnderpassDesc"),
			icon = "ui/lollo_freestyle_train_station/underpass.tga"
		},
		metadata = { },
		order = {
			value = 40,
		},
		type = _constants.underpassModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			local eraPrefix = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
			local modelId = _constants.era_c_underpassBuilding7MModelFileName
			if eraPrefix == moduleHelpers.eras.era_b.prefix then modelId = _constants.era_b_underpassBuilding7MModelFileName
			elseif eraPrefix == moduleHelpers.eras.era_a.prefix then modelId = _constants.era_a_underpassBuilding7MModelFileName
			end
			result.models[#result.models + 1] = {
				id = modelId,
				slotId = slotId,
				transf = slotTransf,
				tag = tag
			}

			local underpassFloorModelId = _constants.era_c_underpassGroundModelFileName
			if eraPrefix == moduleHelpers.eras.era_b.prefix then underpassFloorModelId = _constants.era_b_underpassGroundModelFileName
			elseif eraPrefix == moduleHelpers.eras.era_a.prefix then underpassFloorModelId = _constants.era_a_underpassGroundModelFileName
			end
			result.models[#result.models+1] = {
				id = underpassFloorModelId,
				transf = transfUtilsUG.mul(
					moduleHelpers.getPlatformObjectTransf_WithYRotation(cpl.posTanX2),
					{ 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, 0, result.laneZs[nTerminal] - 0.02, 1 }
				),
			}
		end,

		getModelsFn = function(params)
			return {
				{
					id = _constants.era_c_underpassBuilding7MModelFileName,
					transf = _constants.idTransf,
				},
			}
		end
	}
end
