local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local slotHelpers = require('lollo_freestyle_train_station.slotHelpers')
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "deco", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("WallIronGlassCopperName"),
			description = _("WallTIronGlassCopperDesc"),
			icon = "ui/lollo_freestyle_train_station/wallIronGlassCopper.tga"
		},
		metadata = { },
		order = {
			value = 32,
		},
		type = _constants.platformWallModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			moduleHelpers.deco.doPlatformWall(result, slotTransf, tag, slotId, params, nTerminal, nTrackEdge,
			'lollo_freestyle_train_station/platformWalls/iron_glass_copper/platformWall_2_5m.mdl', 'lollo_freestyle_train_station/platformWalls/iron_glass_copper/platformWall_5m.mdl',
			'lollo_freestyle_train_station/platformWalls/iron_glass_copper/platformWall_low_2_5m.mdl', 'lollo_freestyle_train_station/platformWalls/iron_glass_copper/platformWall_low_5m.mdl',
			_constants.platformWallIronGlassCopperPillar2_5MModelFileName, _constants.platformWallIronGlassCopperPillar5MModelFileName,
			true)
		end,

		getModelsFn = function(params)
			local results = {}
			for x = -2, 2 do
				results[#results+1] = {
					id = 'lollo_freestyle_train_station/platformWalls/iron_glass_copper/platformWall_2_5m.mdl',
					transf = {-1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1, 0,  x, 0, 0, 1},
				}
			end
			results[#results+1] = {
				id = _constants.platformWallIronGlassCopperPillar2_5MModelFileName,
				transf = {-1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1},
			}
			results[#results+1] = moduleHelpers.deco.getPreviewIcon(params)
			return results
		end
	}
end
