function data()
	-- local _constants = require('lollo_freestyle_train_station.constants') -- this won't work
	return {
		en = {
			["DESC"] = [[
A freestyle train station. It introduces some new special tracks, which will serve as platforms for cargo or passengers.

[h1]Instructions[/h1]
Lay platforms alongside normal tracks, then place a platform marker and a track marker where you want the platform and the track to end. Repeat at the other end.
WAIT A MOMENT and let the computer think.
Now you have built a terminal, trains will stop between your track markers.
Add more platforms, tracks and markers, a popup will ask you if you want to join your new terminal to the other ones. You can have up to 12 terminals in one station.

Now click your station to open the configuration menu and add some connections.
- Adjacent platforms are connected together automatically. If they are too far apart, connect them with exits, stairs or underpasses. You can also connect two bridge exits with a suitable path - or a stairs or lift asset.
- Every set of adjacent ground platforms requires street access, an underpass, a lift or stairs.
- Every set of adjacent bridge platforms requires a lift or an underpass.
- Every bridge level requires a lift, or an underpass close to a ground platform lift or stairs.
- Every set of adjacent underground platforms requires stairs.
- Every underground level requires an underground entrance, or a ground platform with an underpass, or a higher underground level with stairs down (if you have multiple underground levels, you can add stairs on the higher levels, to go down to the lower levels).

You can share a platform between two terminals, for example the first 100 metres with terminal 1 and the rest with terminal 2. If you do that, the heads will connect automatically if they are 7 metres apart or less. If they are farther, use end exits and connect them with a suitable path (street menu).
You cannot share one stretch of platform or track among multiple terminals.

When you bulldoze a terminal, the mod will try to rebuild the tracks as they were before, to make changes easy: bulldoze a terminal, change what you need, then rebuild it with the markers.
When you bulldoze the station, everything will be bulldozed.

Lifts, stairs and underground entrances are in the assets, search for "freestyle station".

[h1]Tips:[/h1]
- Platforms are tracks and they can also suffer from micro splits, very difficult to see.
- To visualise the lanes and the splits, start the game in debug mode and press <AltGr> + <L>. This is particularly useful with multi-level underground stations.
- To work underground, use <NumPad 4> or the "Look Underground" track construction.
- Platforms only carry passengers or cargo if they are part of a terminal.
- 2.5 m platforms do not agree with bridges and tunnels. My "no railing" bridges help, tunnels can't be helped.
- This mod adds bridges to help with elevated stations.
- Very thin paths help with certain setups: those are in my Street Fine Tuning mod.
- This mod adds pedestrian paths and bridges; some turn into bridges after placing them. For precision work, use the Street Fine Tuning "chunks" and "splitter" constructions.
- Sound effects for stations are in my dedicated mod.
- Sound effects for trains are in my dedicated mod.
- Extra ground textures are in my terrain tweaks mod.
- If you want different buildings, use assets. There are mods with those.
- This mod adds stairs and lifts as configurable assets; they can be used anywhere. My "Construction Mover" mod helps to place them easily. Still, the game does not handle them gracefully and <AltGr> + <L> will help you check if they snap to your network. Cycling between snappy and non-snappy roads or bridges in the parameter window might help.
- Use the track constructions "Track splitter" to do precision work.
- Upgrading tracks does all tracks at once.
- If you have too many track types, use the categories in the menu to make life easier.
- After a while, the area surrounding your station will have developped and might throw collision errors whenever you try to config the station. Patiently look for the guilty street, building or asset and remove it. If the worst comes to the worst, use the mod "build with collision" to remove colliding station modules.

[h1]Note:[/h1]
- Underground stations are now in the assets.
- Minor version 1.81 (31st August 2022) introduced important layout changes. Previously built terminals will keep working but might have some glitches. To benefit from the changes, remove them, wait for them to reappear and build them anew.
- Platforms do not connect automatically to adjacent roads, you must add an exit or a station.
- Minor version 1.99 (13th February 2023) makes existing walls invisible until you build a new one.
- Walls around tracks are only available on terminals built with version 1.99 or newer.

[h1]Known issues:[/h1]
- Module placement is rather free, the player is allowed to do some unrealistic things. Proper checks would be too expensive.
- Station naming does not work properly.
- 2.5 m platforms do not agree with bridges and tunnels. Ask UG to make trackDistance work.
- The bigger your station is, the longer it takes to add or remove a terminal. It can take over a minute. Just wait.
- Some modules can only be placed after some others, eg stairs exits after stairs, but the configuration menu does not refresh automatically. After placing the first set of stairs, you need to close and reopen the menu for stairs exits to appear.
- Some track and signal mods are incompatible. As a general rule, avoid mods that overwrite or disable stock game tracks. Chances are you won't miss them anyway.
			]],
			["NAME"] = "Freestyle train station",

			["AxialCargoRampFlatName"] = "Cargo exit",
			["AxialCargoRampFlatDesc"] = "Cargo exit, 2 m. Tilt with <m> and <n>.",
			["AxialCargoRampUpSmoothName"] = "Smooth cargo ramp up",
			["AxialCargoRampUpSmoothDesc"] = "Smooth cargo ramp leading outside and up, 2 m. Tilt with <m> and <n>.",
			["AxialCargoRampUpSteepName"] = "Steep cargo ramp up",
			["AxialCargoRampUpSteepDesc"] = "Steep cargo ramp leading outside and up, 2 m. Tilt with <m> and <n>.",
			["AxialCargoRampDownSmoothName"] = "Smooth cargo ramp down",
			["AxialCargoRampDownSmoothDesc"] = "Smooth cargo ramp leading outside and down, 2 m. Tilt with <m> and <n>.",
			["AxialCargoRampDownSteepName"] = "Steep cargo ramp down",
			["AxialCargoRampDownSteepDesc"] = "Steep cargo ramp leading outside and down, 2 m. Tilt with <m> and <n>.",
			["AxialPassengerStairsFlatName"] = "Flat passenger exit",
			["AxialPassengerStairsFlatDesc"] = "Flat passenger exit, 2 m. It connects automatically to nearby platforms or exits. Tilt with <m> and <n>.",
			["AxialPassengerStairsUpSmoothName"] = "Exit with smooth passenger stairs up",
			["AxialPassengerStairsUpSmoothDesc"] = "Smooth passenger stairs leading outside and up, 2 m. It connects automatically to nearby platforms or exits. Tilt with <m> and <n>.",
			["AxialPassengerStairsUpSteepName"] = "Exit with steep passenger stairs up",
			["AxialPassengerStairsUpSteepDesc"] = "Steep passenger stairs leading outside and up, 2 m. It connects automatically to nearby platforms or exits. Tilt with <m> and <n>.",
			["AxialPassengerStairsDownSmoothName"] = "Exit with smooth passenger stairs down",
			["AxialPassengerStairsDownSmoothDesc"] = "Smooth passenger stairs leading outside and down, 2 m. It connects automatically to nearby platforms or exits. Tilt with <m> and <n>.",
			["AxialPassengerStairsDownSteepName"] = "Exit with steep passenger stairs down",
			["AxialPassengerStairsDownSteepDesc"] = "Steep passenger stairs leading outside and down, 2 m. It connects automatically to nearby platforms or exits. Tilt with <m> and <n>.",
			["AxialFlushCargoExitName"] = "Flush cargo exit, platform end",
			["AxialFlushCargoExitDesc"] = "Flush cargo exit at a platform end. It can connect to nearby similar exits, roads, stairs and lift assets. Tilt with <m> and <n>.",
			["AxialPassengerStairsEdgeName"] = "Entrance to platform end with auto bridge",
			["AxialPassengerStairsEdgeDesc"] = "Connects a platform end to the road network. Link it to \"stairs\" assets, bridges or paths as required. Tilt with <m> and <n>. It will become snappy at the next config update.",
			["AxialPassengerStairsSnappyEdgeName"] = "Entrance to platform end with snappy auto bridge",
			["AxialPassengerStairsSnappyEdgeDesc"] = "Connects a platform end to the road network. Link it to \"stairs\" assets, bridges or paths as required. Tilt with <m> and <n>.",
			["AxialFlushPassengerExitName"] = "Flush passenger exit, platform end",
			["AxialFlushPassengerExitDesc"] = "Flush passenger exit at the platform end. It can connect to nearby similar exits, roads, stairs and lift assets. Tilt with <m> and <n>.",
			["CargoStationSquarePlainName"] = "Plain station square",
			["CargoStationSquarePlainDesc"] = "Plain square between cargo stations and the road. Repaint its ground with <shift> and a paint tool.",
			["CargoShelfIronName"] = "Cargo shelf",
			["CargoShelfIronDesc"] = "A shelf to store extra cargo",
			["FlatCargoRampDownSmoothName"] = "Smooth cargo ramp down",
			["FlatCargoRampDownSmoothDesc"] = "Smooth cargo ramp leading outside and down, 2 m. Adjust its height with <m> and <n>.",
			["FlatCargoRampDownSteepName"] = "Steep cargo ramp down",
			["FlatCargoRampDownSteepDesc"] = "Steep cargo ramp leading outside and down, 2 m. Adjust its height with <m> and <n>.",
			["FlatCargoRampFlatName"] = "Cargo exit",
			["FlatCargoRampFlatDesc"] = "Cargo exit, 2 m. Adjust its height with <m> and <n>.",
			["FlatPassengerStairsDownSmoothName"] = "Exit with smooth passenger stairs down",
			["FlatPassengerStairsDownSmoothDesc"] = "Smooth passenger stairs leading outside and down, 2 m. It connects automatically to nearby platforms or exits. Adjust their height with <m> and <n>.",
			["FlatPassengerStairsDownSteepName"] = "Exit with steep passenger stairs down",
			["FlatPassengerStairsDownSteepDesc"] = "Steep passenger stairs leading outside and down, 2 m. It connects automatically to nearby platforms or exits. Adjust their height with <m> and <n>.",
			["FlatPassengerStairsEdgeName"] = "Entrance to platform side with auto bridge",
			["FlatPassengerStairsEdgeDesc"] = "Connects a platform side to the road network. Link it to \"stairs\" assets, bridges or paths as required. It will become snappy at the next config update. Adjust its height with <m> and <n>.",
			["FlatPassengerStairsSnappyEdgeName"] = "Entrance to platform side with snappy auto bridge",
			["FlatPassengerStairsSnappyEdgeDesc"] = "Connects a platform side to the road network. Link it to \"stairs\" assets, bridges or paths as required. Adjust its height with <m> and <n>.",
			["FlatPassengerStairsFlatName"] = "Flat passenger exit",
			["FlatPassengerStairsFlatDesc"] = "Flat passenger exit, 2 m. It connects automatically to nearby platforms or exits. Adjust its height with <m> and <n>.",
			["FlatCargoRampUpSmoothName"] = "Smooth cargo ramp up",
			["FlatCargoRampUpSmoothDesc"] = "Smooth cargo ramp leading outside and up, 2 m. Adjust its height with <m> and <n>.",
			["FlatCargoRampUpSteepName"] = "Steep cargo ramp up",
			["FlatCargoRampUpSteepDesc"] = "Steep cargo ramp leading outside and up, 2 m. Adjust its height with <m> and <n>.",
			["FlatPassengerStairsUpSmoothName"] = "Exit with smooth passenger stairs up",
			["FlatPassengerStairsUpSmoothDesc"] = "Smooth passenger stairs leading outside and up, 2 m. It connects automatically to nearby platforms or exits. Adjust their height with <m> and <n>.",
			["FlatPassengerStairsUpSteepName"] = "Exit with steep passenger stairs up",
			["FlatPassengerStairsUpSteepDesc"] = "Steep passenger stairs leading outside and up, 2 m. It connects automatically to nearby platforms or exits. Adjust their height with <m> and <n>.",
			["FlushCargoExitOuterName"] = "Flush cargo exit along the platform",
			["FlushCargoExitOuterDesc"] = "Flush cargo exit along the platform or the extension border, whichever is farther. It connects automatically to nearby platforms or exits. Adjust its height with <m> and <n>.",
			["FlushPassengerExitAdjustableName"] = "Flush passenger exit with adjustable distance",
			["FlushPassengerExitAdjustableDesc"] = "Flush passenger exit, to make flexible connections across extensions. Adjust it between platform edge and extension edge with <m> and <n>. It connects automatically to nearby platforms or exits.",
			["FlushPassengerExitOuterName"] = "Flush passenger exit along the platform",
			["FlushPassengerExitOuterDesc"] = "Flush passenger exit along the platform or the extension border, whichever is farther. It connects automatically to nearby platforms or exits. Adjust its height with <m> and <n>.",
			["FlatCargoArea5x5Name"] = "5x5 flat side area with ramp, cargo",
			["FlatCargoArea5x5Desc"] = "Flat side area with ramp leading outside, 5x5 m, cargo style. Good for plopping assets on. Adjust its height with <m> and <n>.",
			["FlatCargoArea10x5Name"] = "10x5 flat side area with ramp, cargo",
			["FlatCargoArea10x5Desc"] = "Flat side area with ramp leading outside, 10x5 m, cargo style. Good for plopping assets on. Adjust its height with <m> and <n>.",
			["FlatCargoArea10x10Name"] = "10x10 flat side area with ramp, cargo",
			["FlatCargoArea10x10Desc"] = "Flat side area with ramp leading outside, 10x10 m, cargo style. Good for plopping assets on. Adjust its height with <m> and <n>.",
			["FlatCargoStation10x10Name"] = "10x10 cargo station",
			["FlatCargoStation10x10Desc"] = "10x10 cargo station. Adjust its height with <m> and <n>.",
			["FlatCargoStation10x15Name"] = "10x15 cargo station",
			["FlatCargoStation10x15Desc"] = "10x15 cargo station. Adjust its height with <m> and <n>.",
			["FlatCargoStationLower10x10Name"] = "10x10 lower cargo station",
			["FlatCargoStationLower10x10Desc"] = "10x10 lower cargo station. Adjust its height with <m> and <n>. Repaint its ground with <shift> and a paint tool.",
			["FlatCargoStation20x20Name"] = "20x20 cargo station",
			["FlatCargoStation20x20Desc"] = "20x20 cargo station. Adjust its height with <m> and <n>.",
			["FlatCargoStation30x28Name"] = "30x28 cargo station",
			["FlatCargoStation30x28Desc"] = "30x28 cargo station. Adjust its height with <m> and <n>.",
			["FlatPassengerArea5x5Name"] = "5x5 flat side area with stairs, passenger",
			["FlatPassengerArea5x5Desc"] = "Flat side area with stairs leading outside, 5x5 m, passenger style. Good for plopping assets on. Adjust its height with <m> and <n>.",
			["FlatPassengerArea10x5Name"] = "10x5 flat side area with stairs, passenger",
			["FlatPassengerArea10x5Desc"] = "Flat side area with stairs leading outside, 10x5 m, passenger style. Good for plopping assets on. Adjust its height with <m> and <n>.",
			["FlatPassengerArea10x10Name"] = "10x10 flat side area with stairs, passenger",
			["FlatPassengerArea10x10Desc"] = "Flat side area with stairs leading outside, 10x10 m, passenger style. Good for plopping assets on. Adjust its height with <m> and <n>.",
			["FlatPassengerStation0MName"] = "Small slick passenger station",
			["FlatPassengerStation0MDesc"] = "Small slick passenger station. Adjust its height with <m> and <n>.",
			["FlatPassengerStation5MName"] = "Small passenger station, 5 m up",
			["FlatPassengerStation5MDesc"] = "Small passenger station, to access a platform a bit higher than the road. Adjust its height with <m> and <n>. Repaint its ground with <shift> and a paint tool.",
			["FlatPassengerStationDown5MName"] = "Small passenger station, 5 m down",
			["FlatPassengerStationDown5MDesc"] = "Small passenger station, to access a platform a bit lower than the road. Adjust its height with <m> and <n>.",
			["FlatPassengerStationSmallName"] = "Small ornate passenger station",
			["FlatPassengerStationSmallDesc"] = "Small ornate passenger station. Adjust its height with <m> and <n>.",
			["FlatPassengerStationMidName"] = "Ornate passenger station",
			["FlatPassengerStationMidDesc"] = "Ornate passenger station. Adjust its height with <m> and <n>.",
			["FlatPassengerStationLargeName"] = "Ornate passenger station",
			["FlatPassengerStationLargeDesc"] = "Ornate passenger station with underpass inside. Adjust its height with <m> and <n>.",
			["LookUndergroundName"] = "Look Underground",
			["LookUndergroundDesc"] = "Hover or build this to look underground, remove it when done.",
			["OpenLiftName"] = "Lift up for ground platform",
			["OpenLiftDesc"] = "Connects ground passenger platforms to their twins, to nearby bridge underpasses or, if you add an exit, to the road network.",
			["OpenStairsUpLeftName"] = "Stairs up left for ground platform",
			["OpenStairsUpLeftDesc"] = "Connects ground passenger platforms to their twins, to nearby bridge underpasses or, if you add an exit, to the road network.",
			["OpenStairsUpRightName"] = "Stairs up right for ground platform",
			["OpenStairsUpRightDesc"] = "Connects ground passenger platforms to their twins, to nearby bridge underpasses or, if you add an exit, to the road network.",
			["OpenStairsExitWithEdgeName_2m"] = "Entrance to stairs with auto bridge",
			["OpenStairsExitWithSnappyEdgeName_2m"] = "Entrance to stairs with snappy auto bridge",
			["OpenStairsExitName_4m"] = "Entrance to stairs, 4 m",
			["OpenStairsExitName_8m"] = "Entrance to stairs, 8 m",
			["OpenStairsExitName_16m"] = "Entrance to stairs, 16 m",
			["OpenStairsExitName_32m"] = "Entrance to stairs, 32 m",
			["OpenStairsExitName_64m"] = "Entrance to stairs, 64 m",
			["OpenStairsExitDesc"] = "Connects stairs and lifts to the outside. Adjust its tilt with <m> and <n>. Link it to \"stairs\" assets if required.",
			["OpenStairsExitWithEdgeDesc"] = "Connects stairs and lifts to the road network. Adjust its tilt with <m> and <n>. Link it to \"stairs\" assets, bridges or paths as required. It will become snappy at the next config update.",
			["OpenStairsExitWithSnappyEdgeDesc"] = "Connects stairs and lifts to the road network. Adjust its tilt with <m> and <n>. Link it to \"stairs\" assets, bridges or paths as required.",
			["PassengerSideLiftName"] = "Passenger lift to a bridge side",
			["PassengerSideLiftDesc"] = "Passenger lift to access a platform on a bridge, from the side. It connects to bridge underpasses and other lifts if they are close enough. Max height 40 m, adjust it with <m> and <n>. Repaint its ground with <shift> and a paint tool.",
			["PassengerPlatformLiftName"] = "Passenger lift to a bridge",
			["PassengerPlatformLiftDesc"] = "Passenger lift to access a platform on a bridge, from below. It connects to bridge underpasses and other lifts if they are close enough. Max height 40 m, adjust it with <m> and <n>. Repaint its ground with <shift> and a paint tool.",
			["PassengerStationSquareName"] = "Station square",
			["PassengerStationSquareDesc"] = "Square between passenger stations and the road. Repaint its ground with <shift> and a paint tool.",
			["PassengerStationSquarePlainName"] = "Plain station square",
			["PassengerStationSquarePlainDesc"] = "Plain square between passenger stations and the road. Repaint its ground with <shift> and a paint tool.",
			["PlatformEraASwitcherName"] = "Switch platform to era A",
			["PlatformEraASwitcherDesc"] = "Switch a platform to era A style",
			["PlatformEraBSwitcherName"] = "Switch platform to era B",
			["PlatformEraBSwitcherDesc"] = "Switch a platform to era B style",
			["PlatformEraCSwitcherName"] = "Switch platform to era C",
			["PlatformEraCSwitcherDesc"] = "Switch a platform to era C style",
			["PlatformRoofConcreteName"] = "Concrete platform roof with tendons",
			["PlatformRoofConcreteDesc"] = "Concrete roof with tendons for passenger platforms",
			["PlatformRoofConcreteModernName"] = "Modern concrete platform roof",
			["PlatformRoofConcreteModernDesc"] = "Modern concrete roof for passenger platforms",
			["PlatformRoofConcretePlainName"] = "Concrete platform roof, plain",
			["PlatformRoofConcretePlainDesc"] = "Concrete roof for passenger platforms",
			["PlatformRoofIronName"] = "Iron roof",
			["PlatformRoofIronDesc"] = "Iron roof for passenger platforms",
			["platformRoofIronGlassCopperName"] = "Iron and glass roof",
			["platformRoofIronGlassCopperDesc"] = "Iron and glass roof for passenger platforms",
			["PlatformRoofMetalGlassName"] = "Glass platform roof",
			["PlatformRoofMetalGlassDesc"] = "Glass roof for passenger platforms",
			["SlopedCargoArea1x5Name"] = "5 m platform extension, cargo style",
			["SlopedCargoArea1x5Desc"] = "Platform extension, 5 m, cargo style. It holds extra cargo for all tracks. Good for plopping assets on.",
			["SlopedCargoArea1x10Name"] = "10 m platform extension, cargo style",
			["SlopedCargoArea1x10Desc"] = "Platform extension, 10 m, cargo style. It holds extra cargo for all tracks. Good for plopping assets on.",
			["SlopedCargoArea1x20Name"] = "20 m platform extension, cargo style",
			["SlopedCargoArea1x20Desc"] = "Platform extension, 20 m, cargo style. It holds extra cargo for all tracks. Good for plopping assets on.",
			["SlopedCargoAreaWaiting1x5Name"] = "5 m platform extension, decorated",
			["SlopedCargoAreaWaiting1x5Desc"] = "Platform extension, 5 m. It holds and displays extra cargo for its track.",
			["SlopedCargoAreaWaiting1x10Name"] = "10 m platform extension, decorated",
			["SlopedCargoAreaWaiting1x10Desc"] = "Platform extension, 10 m. It holds and displays extra cargo for its track.",
			["SlopedCargoAreaWaiting1x20Name"] = "20 m platform extension, decorated",
			["SlopedCargoAreaWaiting1x20Desc"] = "Platform extension, 20 m. It holds and displays extra cargo for its track.",
			["SlopedPassengerArea1x2_5Name"] = "2.5 m platform extension, passenger style",
			["SlopedPassengerArea1x2_5Desc"] = "Platform extension, 2.5 m, passenger style. It holds extra passengers for all tracks. Good for plopping assets on.",
			["SlopedPassengerArea1x5Name"] = "5 m platform extension, passenger style",
			["SlopedPassengerArea1x5Desc"] = "Platform extension, 5 m, passenger style. It holds extra passengers for all tracks. Good for plopping assets on.",
			["SlopedPassengerArea1x10Name"] = "10 m platform extension, passenger style",
			["SlopedPassengerArea1x10Desc"] = "Platform extension, 10 m, passenger style. It holds extra passengers for all tracks. Good for plopping assets on.",
			["SlopedPassengerArea1x20Name"] = "20 m platform extension, passenger style",
			["SlopedPassengerArea1x20Desc"] = "Platform extension, 20 m, passenger style. It holds extra passengers for all tracks. Good for plopping assets on.",
			["SlopedPassengerAreaWaiting1x2_5Name"] = "2.5 m platform extension, decorated",
			["SlopedPassengerAreaWaiting1x2_5Desc"] = "Platform extension, 2.5 m. It holds and displays extra passengers for its track.",
			["SlopedPassengerAreaWaiting1x5Name"] = "5 m platform extension, decorated",
			["SlopedPassengerAreaWaiting1x5Desc"] = "Platform extension, 5 m. It holds and displays extra passengers for its track.",
			["SlopedPassengerAreaWaiting1x10Name"] = "10 m platform extension, decorated",
			["SlopedPassengerAreaWaiting1x10Desc"] = "Platform extension, 10 m. It holds and displays extra passengers for its track.",
			["SlopedPassengerAreaWaiting1x20Name"] = "20 m platform extension, decorated",
			["SlopedPassengerAreaWaiting1x20Desc"] = "Platform extension, 20 m. It holds and displays extra passengers for its track.",
			["SubwayName"] = "Underground entrance",
			["SubwayDesc"] = "Plop these near a freestyle station and join them with the popup. Make sure your station has underpasses and / or subway stairs.",
			["TrackCrossingName"] = "Track crossing for two tracks",
			["TrackCrossingDesc"] = "It connects to one platform and it can connect to the road network or to a twin opposite, if it is close enough.",
			["TrackCrossingTwoStairsName"] = "Track crossing for a single track",
			["TrackCrossingTwoStairsDesc"] = "It connects two opposite platforms if they are close enough.",
			["TunnelStairsUpName"] = "Subway stairs up",
			["TunnelStairsUpDesc"] = "Connects underground passenger platforms to the subway entrances and the other terminals above.",
			["TunnelStairsUpDownName"] = "Subway stairs up and down",
			["TunnelStairsUpDownDesc"] = "Connects underground passenger platforms to the subway entrances and the other terminals above and below.",
			["UndergroundName"] = "Underground Station",
			["UnderpassName"] = "Covered Underpass",
			["UnderpassDesc"] = "When on the ground, it connects passenger platforms to subway entrances, lifts to bridges and other ground underpasses. When on a bridge instead, it connects to lifts to bridges, other bridge underpasses, platform stairs and lifts that are close enough.",
			["UnderpassStairsName"] = "Underpass",
			["UnderpassStairsDesc"] = "When on the ground, it connects passenger platforms to subway entrances, lifts to bridges and other ground underpasses. When on a bridge instead, it connects to lifts to bridges, other bridge underpasses, platform stairs and lifts that are close enough.",
			["WallBricksName"] = "Brick wall",
			["WallBricksDesc"] = "Brick wall, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallConcreteModernName"] = "Concrete wall, modern",
			["WallConcreteModernDesc"] = "Concrete wall, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallConcretePlainName"] = "Concrete wall, plain",
			["WallConcretePlainDesc"] = "Concrete wall, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallConcretePlainWRoofName"] = "Concrete wall and roof, plain",
			["WallConcretePlainWRoofDesc"] = "Concrete wall and roof for passenger platforms",
			["WallIronName"] = "Iron fence",
			["WallIronDesc"] = "Iron fence, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallIronGlassCopperName"] = "Iron and glass wall",
			["WallIronGlassCopperDesc"] = "Iron and glass wall, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallIronGlassCopperWRoofName"] = "Iron and glass wall and roof",
			["WallIronGlassCopperWRoofDesc"] = "Iron and glass wall and roof for passenger platforms",
			["WallStaccionataFsName"] = "1.4m concrete fence",
			["WallStaccionataFsDesc"] = "1.4m concrete fence, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallStaccionataFsTallName"] = "2m concrete fence",
			["WallStaccionataFsTallDesc"] = "2m concrete fence, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallTiledName"] = "Tiled wall, older",
			["WallTiledDesc"] = "Tiled wall, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallTiledWLargeStripesName"] = "Tiled wall, newer",
			["WallTiledWLargeStripesDesc"] = "Tiled wall, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallTiledWRoofName"] = "Tiled wall and roof",
			["WallTiledWRoofDesc"] = "Tiled wall and roof for passenger platforms",
			["WallMetalGlassName"] = "Glass wall",
			["WallMetalGlassDesc"] = "Glass wall, also suitable for tunnels. Adjust slantness with <m> and <n>.",
			["WallMetalGlassWRoofName"] = "Glass wall and roof",
			["WallMetalGlassWRoofDesc"] = "Glass wall and roof for passenger platforms",
			["EraACargoPlatform5MName"] = "5 m cargo platform, era A",
			["EraACargoPlatform5MDesc"] = "Cargo platforms to be laid as tracks, 5 m wide, era A. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraACargoPlatform10MName"] = "10 m cargo platform, era A",
			["EraACargoPlatform10MDesc"] = "Cargo platforms to be laid as tracks, 10 m wide, era A. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraACargoPlatform20MName"] = "20 m cargo platform, era A",
			["EraACargoPlatform20MDesc"] = "Cargo platforms to be laid as tracks, 20 m wide, era A. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraBCargoPlatform5MName"] = "5 m cargo platform, era B",
			["EraBCargoPlatform5MDesc"] = "Cargo platforms to be laid as tracks, 5 m wide, era B. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraBCargoPlatform10MName"] = "10 m cargo platform, era B",
			["EraBCargoPlatform10MDesc"] = "Cargo platforms to be laid as tracks, 10 m wide, era B. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraBCargoPlatform20MName"] = "20 m cargo platform, era B",
			["EraBCargoPlatform20MDesc"] = "Cargo platforms to be laid as tracks, 20 m wide, era B. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraCCargoPlatform5MName"] = "5 m cargo platform, era C",
			["EraCCargoPlatform5MDesc"] = "Cargo platforms to be laid as tracks, 5 m wide, era C. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraCCargoPlatform10MName"] = "10 m cargo platform, era C",
			["EraCCargoPlatform10MDesc"] = "Cargo platforms to be laid as tracks, 10 m wide, era C. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraCCargoPlatform20MName"] = "20 m cargo platform, era C",
			["EraCCargoPlatform20MDesc"] = "Cargo platforms to be laid as tracks, 20 m wide, era C. They are in fact slow train tracks; they are not meant to be crossed.",
			["LolloFreestyleTrainStationName"] = "Freestyle train station",
			["LolloFreestyleTrainStationDesc"] = "Freestyle train station",
			["PlatformWaypointName"] = "Platform end marker",
			["PlatformWaypointDesc"] = "Marks the ends of a platform that will become part of a freestyle station. The direction does not matter; if there is already a split nearby, it will take priority; if the platform ends nearby, that end will take a higher priority.",
			["EraAPassengerPlatform5MName"] = "5 m passenger platform, era A",
			["EraAPassengerPlatform5MDesc"] = "Passenger platforms to be laid as tracks, 5 m wide, era A. Use them with tunnels or bridges. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraAPassengerPlatform2_5MName"] = "2.5 m passenger platform, era A",
			["EraAPassengerPlatform2_5MDesc"] = "Passenger platforms to be laid as tracks, 2.5 m wide, era A. The best choice for stations on ground. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraBPassengerPlatform5MName"] = "5 m passenger platform, era B",
			["EraBPassengerPlatform5MDesc"] = "Passenger platforms to be laid as tracks, 5 m wide, era B. Use them with tunnels or bridges. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraBPassengerPlatform2_5MName"] = "2.5 m passenger platform, era B",
			["EraBPassengerPlatform2_5MDesc"] = "Passenger platforms to be laid as tracks, 2.5 m wide, era B. The best choice for stations on ground. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraCPassengerPlatform5MName"] = "5 m passenger platform, era C",
			["EraCPassengerPlatform5MDesc"] = "Passenger platforms to be laid as tracks, 5 m wide, era C. Use them with tunnels or bridges. They are in fact slow train tracks; they are not meant to be crossed.",
			["EraCPassengerPlatform2_5MName"] = "2.5 m passenger platform, era C",
			["EraCPassengerPlatform2_5MDesc"] = "Passenger platforms to be laid as tracks, 2.5 m wide, era C. The best choice for stations on ground. They are in fact slow train tracks; they are not meant to be crossed.",
			["TrackWaypointName"] = "Track End Marker",
			["TrackWaypointDesc"] = "Marks the ends of a track that will become part of a freestyle station. The direction does not matter; if there is already a split nearby, it will take priority; if the track ends nearby, that end will take a higher priority. Nearby semaphores can interfere, you may want to remove them and put them back once the station is laid out.",

			["CementBridgeGlassWallNoPillars"] = "Concrete bridge with underpasses, glass shields and no pillars. Only for 5 m platforms.",
			["CementBridgeGlassWallNormalPillars"] = "Concrete bridge with underpasses and glass shields. Only for 5 m platforms.",
			["CementBridgeGlassWallSpacedPillars"] = "Concrete bridge with underpasses, glass shields and spaced pillars. Only for 5 m platforms.",
			["CementBridgeNoPillarsNoSides"] = "Concrete bridge with no pillars and no railing, compatible with 2.5 m platforms",
			["CementBridgeNormalPillarsNoSides"] = "Concrete bridge with no railing, compatible with 2.5 m platforms",
			["CementBridgeSpacedPillarsNoSides"] = "Concrete bridge with spaced pillars and no railing, compatible with 2.5 m platforms",
			["IronBridgeNoPillarsNoSides"] = "Iron bridge with no pillars and no railing, compatible with 2.5 m platforms",
			["IronBridgeNormalPillarsNoSides"] = "Iron bridge with no railing, compatible with 2.5 m platforms",
			["IronBridgeSpacedPillarsNoSides"] = "Iron bridge with spaced pillars and no railing, compatible with 2.5 m platforms",
			["PedestrianCementBridgeNoPillars"] = "Concrete bridge with no pillars. For pedestrian paths",
			["PedestrianCementBridgeNoPillarsNoSides"] = "Concrete bridge with no pillars and no railing. For pedestrian paths and 2.5 m platforms",
			["era_a_PedestrianBasicBridgeNoPillars"] = "Era A bridge with no pillars, for pedestrian paths",
			["era_a_PedestrianBasicBridgeNoPillarsNoSides"] = "Era A bridge with no pillars and no railing, for pedestrian paths and 2.5 m platforms",
			["era_b_PedestrianBasicBridgeNoPillars"] = "Era B bridge with no pillars, for pedestrian paths",
			["era_b_PedestrianBasicBridgeNoPillarsNoSides"] = "Era B bridge with no pillars and no railing, for pedestrian paths and 2.5 m platforms",
			["era_c_PedestrianBasicBridgeNoPillars"] = "Era C bridge with no pillars, for pedestrian paths",
			["era_c_PedestrianBasicBridgeNoPillarsNoSides"] = "Era C bridge with no pillars and no railing, for pedestrian paths and 2.5 m platforms",

			["NewStationName"] = "New Station",

			-- categories
			["cargo-platform-extensions"] = "Cargo extensions",
			["cargo-platform-tracks"] = "Cargo platforms to be laid as tracks",
			["cargo-road-access"] = "Cargo side -> road",
			["cargo-road-access-axial"] = "Cargo end -> road",
			["cargo-shelves"] = "Cargo shelves",
			["passenger-platform-extensions"] = "Passenger extensions",
			["passenger-platform-tracks"] = "Passenger platforms to be laid as tracks",
			["passenger-road-access"] = "Passengers side -> road",
			["passenger-road-access-axial"] = "Passengers end -> road",
			["passenger-road-access-stairs"] = "Stairs -> road",
			["passenger-up-and-down"] = "Up and down",
			["platform-deco"] = "Platform Deco",
			["track-crossings"] = "Track crossings",
			["track-deco"] = "Track Deco",
			["train-tracks"] = "Train tracks",
			["waypoints-for-freestyle-station"] = "Waypoints For Freestyle Stations",

			-- messages
			["BuildInProgress"] = "Building terminal...",
			["BuildMoreWaypoints"] = "Plop two track markers and two platform markers to build a freestyle station",
			["BuildSnappyTracksFailed"] = "Fix the station connections to the adjacent tracks, the game cannot do it for you this time",
			["ConConfigWindowTitle"] = "Configuration",
			["DifferentPlatformWidths"] = "Avoid different track widths with cargo stations",
			["GoBack"] = "Go back",
			["GoThere"] = "Go there",
			["Join"] = "Join",
			["NeedAdjust4Snap"] = "Some street connections have unsnapped: make any change to the station configuration to fix this",
			["NoJoin"] = "Do not join",
			["RestoreInProgress"] = "Restoring platform and track...",
			["ShowUnderground"] = "Show Underground",
			["ShowUndergroundTooltip"] = "It cannot be changed once plopped. If you want assistance to place it easily, use the 'Look Underground' track construction instead of this.",
			["StationPickerWindowTitle"] = "Pick a station to join",
			["SubwayCannotConnect"] = "Add stairs or underpasses to connect this underground entrance",
			["SubwayNotConnected"] = "Join this underground entrance to a station",
			["TrackWaypointBuiltOnPlatform"] = "You can only build track markers on tracks and platform markers on platforms",
			["TrackWaypointsMissing"] = "Build two track markers first",
			["UndergroundTrainDepotName"] = "Underground Train depot",
			["UndergroundTrainDepotDesc"] = "Used to buy/sell trains. The 'Look Underground' track construction helps to snap it to the track.",
			["Wait4Join"] = "Joining may take a while, wait a bit!",
			["WarningWindowTitle"] = "Warning",
			["WaypointAlreadyBuilt"] = "You can only build two markers",
			["WaypointsCrossCrossing"] = "There is a joint between this marker and its twin",
			["WaypointsCrossSignal"] = "There is a semaphore or a waypoint between this marker and its twin, or too close to either",
			["WaypointsCrossStation"] = "You cannot cross an existing station",
			["WaypointDistanceWindowTitle"] = "Air Distance",
			["WaypointsNotConnected"] = "This marker is not connected to its twin, or there is a station / joint / semaphore between, or it is too close to a station / joint / semaphore",
			["WaypointsTooCloseToStation"] = "Too close to an existing station or depot. Cut the track with the track splitter if you need to get close. The platform heads will connect automatically if they are closer than 7 metres",
			["WaypointsTooFar"] = "Too far from its twin",
			["WaypointsWrong"] = "Place two markers on the same platform and two on the same track",

			-- free open stairs and free lifts
			["BaseMode"] = "Base Mode",
			["BridgeHeight"] = "Bridge Height",
			["BridgeMode"] = "Bridge Mode",
			["BridgeYAngle"] = "Bridge Tilt",
			["BridgeZAngle"] = "Bridge Rotation",
			["EdgeWithBridge"] = "Auto Bridge",
			["EdgeWithNoBridge"] = "Auto Path",
			["Era"] = "Era",
			["ErrorReplacingConWithSnappyCopy"] = "This object cannot connect to nearby roads, change it or move it somewhere else",
			["FlatSlopedTerrain"] = "Terrain Incline",
			["Model"] = "Platform",
			["ModelRaised"] = "Raised Platform",
			["NoRailing0"] = "0 - No Railing",
			["OpenTwinStairsFreeName"] = "Twin Stairs",
			["OpenTwinStairsFreeDesc"] = "Twin stairs matching the freestyle stations, collision tolerant; use fences or similar mods to fine-tune collisions. Combine this to pedestrian bridges or paths. Place it accurately with the construction mover.",
			["OpenLiftFreeDesc"] = "Lift matching the freestyle stations, collision tolerant; use fences or similar mods to fine-tune collisions. Combine this to pedestrian bridges or paths. Place it accurately with the construction mover.",
			["OpenLiftFreeName"] = "Lift",
			["OpenStairsFreeDesc"] = "Stairs matching the freestyle stations, collision tolerant; use fences or similar mods to fine-tune collisions. Combine this to pedestrian bridges or paths. Place it accurately with the construction mover. It can also carry cargo.",
			["OpenStairsFreeHeight"] = "Height",
			["OpenStairsFreeName"] = "Stairs",
			["PedestrianBridges"] = "Pedestrian Bridges",
			["PedestrianPaths"] = "Pedestrian Paths",
			["SimpleConnection"] = "Simple",
			["SnappyEdgeWithBridge"] = "Snappy Bridge",
			["SnappyEdgeWithNoBridge"] = "Snappy Path",
			["Stairs"] = "Stairs, lifts, underground entrances, assets for the Freestyle Train Station",
      		["StairsBase"] = "Expand Base",
			["StairsBaseTooltip"] = "It might be easier to select \"Auto Path\" or \"Auto Bridge\" when building or changing properties and change it to \"Snappy Path\" or \"Snappy Bridge\" once done. Check the connections with <AltGr> + <L>.",
			["TerrainAlignmentType"] = "Terrain Alignment",
			["TerrainAlignmentTypeFlat"] = "Flat",
			["TerrainAlignmentTypeSloped"] = "Sloped",
			["TopPlatformLength"] = "Top Platform Length",
			["TopPlatformLengthTooltip"] = "It might be easier to select \"Auto Path\" or \"Auto Bridge\" when building or changing properties and change it to \"Snappy Path\" or \"Snappy Bridge\" once done. Check the connections with <AltGr> + <L>.",
			["TopPlatformNorthLength"] = "Top Platform One",
			["TopPlatformSouthLength"] = "Top Platform Two",
			["TopPlatformNorthLengthTooltip"] = "It might be easier to select \"Auto Bridge\" when building or changing properties and change it to \"Snappy Bridge\" once done. Check the connections with <AltGr> + <L>.",

			-- track splitter
			["TrackSplitterName"] = "Track splitter",
			["TrackSplitterDesc"] = "Splits a track in two sections. Does not work on tracks, which are part of a construction (eg a station). Use <AltGr> + <L> to see its effect.",

			-- platform as asset
			["PlatformAsAssetName"] = "Platform as asset",
			["PlatformAsAssetDesc"] = "Platform as asset. Adjust it with the Construction Mover.",
			["PlatformAsAsset_CargoOrPassengers"] = "Cargo or passengers",
			["PlatformAsAsset_Cargo"] = "Cargo",
			["PlatformAsAsset_Passengers"] = "Passengers",
			["PlatformAsAsset_X10m"] = "X size, coarse, m",
			["PlatformAsAsset_X1m"] = "X size, fine, m",
			["PlatformAsAsset_Y10m"] = "Y size, coarse, m",
			["PlatformAsAsset_Y1m"] = "Y size, fine, m",

			["TilesHexagonClean"] = "Tiles hexagon, clean",

			-- fence assets
			["FenceAssetsName"] = "Walls and fences",
			["FenceAssetsDesc"] = "Walls and fences to match freestyle stations. Adjust them with the Construction Mover.",
			["fenceModelName"] = "Wall top",
			["wallEraPrefix_0IsNoWall"] = "Wall bottom Era",
			["NoWall"] = "No wall bottom",
			["Length"] = "Length m",
		},
		de = {
			["DESC"] = [[
Ein Freestyle-Bahnhof. Er führt einige neue Spezialgleise ein, die als Bahnsteige für Fracht oder Passagiere dienen werden.

[h1]Anleitung[/h1]
Legen Sie Bahnsteigen entlang normaler Gleise und platzieren Sie dann eine Bahnsteig- und einen Gleismarker dort, wo die Bahnsteig und das Gleis enden sollen. Wiederholen Sie den Vorgang am anderen Ende.
WARTEN Sie einen Moment und lassen Sie den Computer nachdenken.
Jetzt haben Sie einen Bahnhof gebaut, und die Züge werden zwischen den Gleismarker halten.
Fügen Sie weitere Bahnsteige, Gleise und Markierungen hinzu. Ein Popup-Fenster wird Sie fragen, ob Sie Ihren neuen Terminal mit den anderen verbinden möchten. Sie können bis zu 12 Terminals in einem Bahnhof haben.

Klicken Sie nun auf Ihren Bahnhof, um das Konfigurationsmenü zu öffnen und einige Verbindungen hinzuzufügen.
- Benachbarte Bahnsteige werden automatisch miteinander verbunden. Wenn sie zu weit voneinander entfernt sind, verbinden Sie sie mit Ausgängen, Treppen oder Unterführungen. Sie können auch zwei Brückenausgänge mit einem geeigneten Weg verbinden, wenn Sie bereit sind, ein wenig mit dem Spiel zu kämpfen. <AltGr> + <L> ist dein Freund.
- Jeder Satz benachbarter Bahnsteige am Boden erfordert einen Straßenzugang, eine Unterführung, einen Aufzug oder eine Treppe.
- Jede Reihe von benachbarten erhöhten Bahnsteigen erfordert einen Aufzug oder eine Unterführung.
- Jede Brückenebene erfordert einen Aufzug oder eine Unterführung in der Nähe eines ebenerdigen Bahnsteigs oder eine Treppe.
- Jede Gruppe von benachbarten unterirdischen Bahnsteigen erfordert eine Treppe.
- Jede unterirdische Ebene erfordert einen unterirdischen Eingang oder einen Bahnsteig am Boden mit einer Unterführung oder eine höhere unterirdische Ebene mit einer Treppe nach unten (wenn Sie mehrere unterirdische Ebenen haben, können Sie auf den höheren Ebenen eine Treppe hinzufügen, um zu den unteren Ebenen hinunter zu gelangen).

Sie können einen Bahnsteig zwischen zwei Terminals teilen, zum Beispiel die ersten 100 Meter mit Terminal 1 und den Rest mit Terminal 2. In diesem Fall werden die Köpfe automatisch verbunden, wenn sie höchstens 7 Meter voneinander entfernt sind.
Sie können einen Bahnsteigabschnitt nicht mit mehreren Terminals teilen.

Wenn Sie einen Terminal mit einem Bulldozer abreißen, versucht der Mod, die Gleise so wiederherzustellen, wie sie vorher waren, um Änderungen zu vereinfachen: Reißen Sie einen Terminal mit einem Bulldozer auf, ändern Sie, was Sie brauchen, und bauen Sie ihn dann mit den Markern wieder auf.
Wenn Sie den Bahnhof mit dem Bulldozer zerstören, wird alles mit dem Bulldozer abgerissen.

Aufzüge, Treppen und unterirdische Eingänge finden Sie in den Assets, suchen Sie nach "freestyle station".

[h1]Hinweise:[/h1]
- Bahnsteigen sind Gleise und können auch unter Mikrospalten leiden, die sehr schwer zu sehen sind.
- Um die Fahrspuren und die Spaltungen zu visualisieren, starten Sie das Spiel im Debug-Modus und drücken Sie <AltGr> + <L>. Dies ist besonders bei mehrstöckigen U-Bahn-Stationen nützlich.
- Um unterirdisch zu arbeiten, verwende <NumPad 4> oder die Gleiskonstruktion "Unterirdisch sehen".
- Bahnsteige befördern nur dann Passagiere oder Fracht, wenn sie Teil eines Terminals sind.
- 2,5 m Bahnsteige passen nicht zu Brücken und Tunneln. Meine "kein Geländer" Brücken helfen, in Tunnels kann nicht geholfen werden.
- Dieser Mod fügt Brücken hinzu, um bei erhöhten Bahnhöfen zu helfen.
- Dieser Mod fügt Fußgängerwege und Brücken hinzu. Einige dieser Wege verwandeln sich in Brücken, nachdem sie platziert wurden. Sie können knifflig zu platzieren sein, die "Chunks" und "Splitter" vom "Street fine tuning"-Mod können helfen.
- Sehr dünne Pfade helfen bei bestimmten Aufbauten: diese sind in meinem "Street fine tuning"-Mod enthalten.
- Soundeffekte für Bahnhöfe sind in meinem speziellen Mod enthalten.
- Soundeffekte für Züge sind in meinem speziellen Mod enthalten.
- Zusätzliche Bodentexturen befinden sich in meinem "Terrain Tweaks"-Mod.
- Wenn du andere Gebäude willst, benutze Assets. Es gibt Mods mit diesen.
- Dieser Mod fügt Treppen und Aufzüge als konfigurierbare Assets hinzu; sie können überall verwendet werden. Mein "Construction Mover"-Mod hilft, sie einfach zu platzieren. Dennoch geht das Spiel nicht sehr zimperlich mit ihnen um, und AltGr + L hilft dir, sie an dein Netzwerk zu binden. Das Wechseln zwischen "snappy" und "non-snappy" Straßen oder Brücken hilft ebenfalls.
- Verwenden Sie den Gleisbau-"Gleisteiler", um Präzisionsarbeit zu leisten.
- Beim Aufrüsten von Gleisen werden alle Gleise auf einmal ausgebaut.
- Wenn Sie zu viele Streckentypen haben, nutzen Sie die Kategorien im Menü, um sich das Leben leichter zu machen.
- Nach einer Weile wird die Umgebung Ihres Bahnhofs zugewachsen sein und möglicherweise Kollisionsfehler anzeigen, wenn Sie versuchen, den Bahnhof zu konfigurieren. Suchen Sie geduldig nach der schuldigen Straße, dem schuldigen Gebäude oder der schuldigen Anlage und entfernen Sie sie. Im schlimmsten Fall können Sie die Mod "build with collision" verwenden, um kollidierende Bahnhofsmodule zu entfernen.

[h1]Anmerkung:[/h1]
- U-Bahnhöfe sind jetzt in den Assets enthalten.
- Mit der Minor-Version 1.81 (31. August 2022) wurden wichtige Änderungen am Layout vorgenommen. Zuvor gebaute Terminals werden weiterhin funktionieren, können aber einige Fehler aufweisen. Um von den Änderungen zu profitieren, entfernen Sie sie, warten Sie, bis sie wieder auftauchen, und bauen Sie sie neu.
- Bahnsteige verbinden sich nicht mehr automatisch mit angrenzenden Straßen, Sie müssen eine Ausfahrt oder einen Bahnhof hinzufügen.
- Version 1.99 (13. Februar 2023) macht bestehende Wände unsichtbar, bis Sie eine neue bauen.
- Mauern um Gleise sind nur auf Terminals verfügbar, die mit Version 1.99 oder neuer gebaut wurden.

[h1]Bekannte Probleme:[/h1]
- Die Platzierung der Module ist ziemlich frei, der Spieler darf einige unrealistische Dinge tun. Richtige Kontrollen wären zu teuer.
- Die Benennung von Bahnhöfen funktioniert nicht richtig.
- 2,5 m Bahnsteige stimmen nicht mit Brücken und Tunneln überein. Bitten Sie UG, trackDistance zum Laufen zu bringen.
- Je größer ein Bahnhof ist, desto länger dauert es, ein Terminal hinzuzufügen oder zu entfernen. Es kann über eine Minute dauern. Warte einfach ab.
- Einige Module können nur nach anderen platziert werden, z.B. Treppenausgänge nach Treppen, aber das Konfigurationsmenü wird nicht automatisch aktualisiert. Nachdem Sie die erste Treppe platziert haben, müssen Sie das Menü schließen und erneut öffnen, damit die Treppenausgänge erscheinen.
- Einige Gleis- und Signalmods sind nicht kompatibel. Generell gilt: Vermeiden Sie Mods, die die Originalgleise des Spiels überschreiben oder deaktivieren. Wahrscheinlich werden Sie sie ohnehin nicht vermissen.
			]],
			["NAME"] = "Freestyle-Bahnhof",

			["AxialCargoRampFlatName"] = "Frachtausgang",
			["AxialCargoRampFlatDesc"] = "Frachtausstieg, 2 m. Kippen mit <m> und <n>.",
			["AxialCargoRampUpSmoothName"] = "Glatte Laderampe nach oben",
			["AxialCargoRampUpSmoothDesc"] = "Glatte Laderampe nach außen und nach oben, 2 m. Kippen mit <m> und <n>.",
			["AxialCargoRampUpSteepName"] = "Steile Laderampe nach oben",
			["AxialCargoRampUpSteepDesc"] = "Steile Laderampe nach außen und oben, 2 m. Neigung mit <m> und <n>.",
			["AxialCargoRampDownSmoothName"] = "Glatte Laderampe nach unten",
			["AxialCargoRampDownSmoothDesc"] = "Glatte Laderampe nach außen und unten, 2 m. Neigung mit <m> und <n>.",
			["AxialCargoRampDownSteepName"] = "Steile Laderampe nach unten",
			["AxialCargoRampDownSteepDesc"] = "Steile Laderampe nach außen und unten, 2 m. Neigung mit <m> und <n>.",
			["AxialPassengerStairsFlatName"] = "Flacher Passagierausstieg",
			["AxialPassengerStairsFlatDesc"] = "Flacher Passagierausgang, 2 m. Er verbindet sich automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Kippen mit <m> und <n>.",
			["AxialPassengerStairsUpSmoothName"] = "Ausgang mit glatter Passagiertreppe nach oben",
			["AxialPassengerStairsUpSmoothDesc"] = "Glatte Passagiertreppe, die nach außen und nach oben führt, 2 m. Sie verbindet sich automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Kippt mit <m> und <n>.",
			["AxialPassengerStairsUpSteepName"] = "Ausgang mit steiler Personentreppe nach oben",
			["AxialPassengerStairsUpSteepDesc"] = "Steile Passagiertreppe, die nach außen und nach oben führt, 2 m. Sie verbindet automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Kippt mit <m> und <n>.",
			["AxialPassengerStairsDownSmoothName"] = "Ausgang mit glatter Personentreppe nach unten",
			["AxialPassengerStairsDownSmoothDesc"] = "Glatte Passagiertreppe, die nach außen und nach unten führt, 2 m. Sie verbindet automatisch mit nahegelegenen Bahnsteigen oder Ausgängen. Kippt mit <m> und <n>.",
			["AxialPassengerStairsDownSteepName"] = "Ausgang mit steiler Personentreppe nach unten",
			["AxialPassengerStairsDownSteepDesc"] = "Steile Passagiertreppe, die nach außen und nach unten führt, 2 m. Sie verbindet automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Kippt mit <m> und <n>.",
			["AxialFlushCargoExitName"] = "Bündiger Frachtausgang, Bahnsteigende",
			["AxialFlushCargoExitDesc"] = "Bündiger Frachtausgang an einem Bahnsteigende. Er kann mit ähnlichen Ausgängen, Straßen, Treppen und Aufzügen in der Nähe verbunden werden. Kippt mit <m> und <n>.",
			["AxialPassengerStairsEdgeName"] = "Eingang zum Bahnsteigende mit Auto-Brücke",
			["AxialPassengerStairsEdgeDesc"] = "Verbindet ein Bahnsteigende mit dem Straßennetz. Verbinde es je nach Bedarf mit <m>Assets, Brücken oder Wegen. Kippt mit <m> und <n>. Es wird beim nächsten Konfigurationsupdate biegsam werden.",
			["AxialPassengerStairsSnappyEdgeName"] = "Eingang zum Bahnsteigende mit Snappy-Autobrücke",
			["AxialPassengerStairsSnappyEdgeDesc"] = "Verbindet ein Bahnsteigende mit dem Straßennetz. Verbinde es je nach Bedarf mit <m>Assets, Brücken oder Wegen. Kippt mit <m> und <n>.",
			["AxialFlushPassengerExitName"] = "Bündiger Passagierausgang, Bahnsteigende",
			["AxialFlushPassengerExitDesc"] = "Bündiger Passagierausstieg am Bahnsteigende. Er kann mit ähnlichen Ausgängen, Straßen, Treppen und Aufzügen in der Nähe verbunden werden. Kippt mit <m> und <n>.",
			["CargoStationSquarePlainName"] = "Einfacher Bahnhofsplatz",
			["CargoStationSquarePlainDesc"] = "Einfacher Platz zwischen den Frachtstationen und der Straße. Male den Boden mit <shift> und einem Malwerkzeug neu an.",
			["CargoShelfIronName"] = "Frachtregal",
			["CargoShelfIronDesc"] = "Ein Regal zur Aufbewahrung zusätzlicher Fracht",
			["FlatCargoRampDownSmoothName"] = "Glatte Laderampe nach unten",
			["FlatCargoRampDownSmoothDesc"] = "Glatte Laderampe, die nach außen und nach unten führt, 2 m. Stellen Sie die Höhe mit <m> und <n> ein.",
			["FlatCargoRampDownSteepName"] = "Steile Laderampe nach unten",
			["FlatCargoRampDownSteepDesc"] = "Steile Laderampe, die nach außen und nach unten führt, 2 m. Stellen Sie ihre Höhe mit <m> und <n> ein.",
			["FlatCargoRampFlatName"] = "Frachtausgang",
			["FlatCargoRampFlatDesc"] = "Frachtausgang, 2 m. Höhe mit <m> und <n> einstellen.",
			["FlatPassengerStairsDownSmoothName"] = "Ausstieg mit glatter Passagiertreppe nach unten",
			["FlatPassengerStairsDownSmoothDesc"] = "Glatte Passagiertreppe, die nach außen und nach unten führt, 2 m. Sie verbindet automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Stellen Sie ihre Höhe mit <m> und <n> ein.",
			["FlatPassengerStairsDownSteepName"] = "Ausgang mit steiler Personentreppe nach unten",
			["FlatPassengerStairsDownSteepDesc"] = "Steile Passagiertreppe, die nach außen und nach unten führt, 2 m. Sie verbindet automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Stelle ihre Höhe mit <m> und <n> ein.",
			["FlatPassengerStairsEdgeName"] = "Eingang zur Bahnsteigseite mit automatischer Brücke",
			["FlatPassengerStairsEdgeDesc"] = "Verbindet eine Bahnsteigseite mit dem Straßennetz. Verknüpfen Sie sie je nach Bedarf mit Treppen-Assets, Brücken oder Wegen. Sie wird bei der nächsten Konfigurationsaktualisierung biegsam werden. Passt seine Höhe mit <m> und <n> an.",
			["FlatPassengerStairsSnappyEdgeName"] = "Eingang zur Bahnsteigseite mit bissiger Autobrücke",
			["FlatPassengerStairsSnappyEdgeDesc"] = "Verbindet eine Bahnsteigseite mit dem Straßennetz. Verknüpfen Sie sie je nach Bedarf mit Treppen-Assets, Brücken oder Wegen. Passe ihre Höhe mit <m> und <n> an.",
			["FlatPassengerStairsFlatName"] = "Flacher Passagierausgang",
			["FlatPassengerStairsFlatDesc"] = "Flacher Passagierausgang, 2 m. Er verbindet automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Stellen Sie seine Höhe mit <m> und <n> ein.",
			["FlatCargoRampUpSmoothName"] = "Glatte Laderampe nach oben",
			["FlatCargoRampUpSmoothDesc"] = "Glatte Laderampe, die nach außen und nach oben führt, 2 m. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatCargoRampUpSteepName"] = "Steile Laderampe nach oben",
			["FlatCargoRampUpSteepDesc"] = "Steile Laderampe, die nach außen und nach oben führt, 2 m. Stellen Sie die Höhe mit <m> und <n> ein.",
			["FlatPassengerStairsUpSmoothName"] = "Ausstieg mit glatter Passagiertreppe nach oben",
			["FlatPassengerStairsUpSmoothDesc"] = "Glatte Passagiertreppe, die nach außen und nach oben führt, 2 m. Sie verbindet automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Stellen Sie ihre Höhe mit <m> und <n> ein.",
			["FlatPassengerStairsUpSteepName"] = "Ausgang mit steiler Personentreppe nach oben",
			["FlatPassengerStairsUpSteepDesc"] = "Steile Passagiertreppe, die nach außen und nach oben führt, 2 m. Sie verbindet automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Stellen Sie ihre Höhe mit <m> und <n> ein.",
			["FlushCargoExitOuterName"] = "Bündiger Frachtausgang entlang des Bahnsteigs",
			["FlushCargoExitOuterDesc"] = "Bündiger Frachtausgang entlang der Bahnsteig oder der Erweiterungsgrenze, je nachdem, was weiter entfernt ist. Er verbindet sich automatisch mit nahe gelegenen Bahnsteigen oder Ausgängen. Stelle seine Höhe mit <m> und <n> ein.",
			["FlushPassengerExitAdjustableName"] = "Bündiger Passagierausgang mit einstellbarem Abstand",
			["FlushPassengerExitAdjustableDesc"] = "Bündiger Passagierausstieg, um flexible Verbindungen über Erweiterungen hinweg herzustellen. Mit <m> und <n> kann der Abstand zwischen Bahnsteigkante und Erweiterungskante eingestellt werden. Er verbindet sich automatisch mit benachbarten Bahnsteigen oder Ausgängen.",
			["FlushPassengerExitOuterName"] = "Bündiger Passagierausstieg entlang des Bahnsteigs",
			["FlushPassengerExitOuterDesc"] = "Bündiger Passagierausgang entlang des Bahnsteigs oder der Erweiterungsgrenze, je nachdem, was weiter entfernt ist. Er verbindet sich automatisch mit benachbarten Bahnsteigen oder Ausgängen. Stellen Sie seine Höhe mit <m> und <n> ein.",
			["FlatCargoArea5x5Name"] = "5x5 flacher Seitenbereich mit Rampe, Fracht",
			["FlatCargoArea5x5Desc"] = "Flacher Seitenbereich mit Rampe, die nach draußen führt, 5x5 m, Fracht-Stil. Gut geeignet, um Fracht darauf zu platzieren. Passe die Höhe mit <m> und <n> an.",
			["FlatCargoArea10x5Name"] = "10x5 flacher Seitenbereich mit Rampe, Fracht",
			["FlatCargoArea10x5Desc"] = "Flacher Seitenbereich mit Rampe nach außen, 10x5 m, Fracht-Stil. Gut geeignet, um Fracht darauf zu platzieren. Passe die Höhe mit <m> und <n> an.",
			["FlatCargoArea10x10Name"] = "10x10 flacher Seitenbereich mit Rampe, Fracht",
			["FlatCargoArea10x10Desc"] = "Flacher Seitenbereich mit Rampe nach außen, 10x10 m, Fracht. Gut geeignet, um Fracht darauf zu platzieren. Passe die Höhe mit <m> und <n> an.",
			["FlatCargoStation10x10Name"] = "10x10 Ladestation",
			["FlatCargoStation10x10Desc"] = "10x10-Ladestation. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatCargoStation10x15Name"] = "10x15-Ladestation",
			["FlatCargoStation10x15Desc"] = "10x15-Ladestation. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatCargoStationLower10x10Name"] = "10x10 untere Ladestation",
			["FlatCargoStationLower10x10Desc"] = "10x10 untere Ladestation. Passe seine Höhe mit <m> und <n> an. Male den Boden mit <shift> und einem Malwerkzeug neu an.",
			["FlatCargoStation20x20Name"] = "20x20-Ladestation",
			["FlatCargoStation20x20Desc"] = "20x20-Ladestation. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatCargoStation30x28Name"] = "30x28-Ladestation",
			["FlatCargoStation30x28Desc"] = "30x28-Ladestation. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatPassengerArea5x5Name"] = "5x5 flacher Seitenbereich mit Treppe, Passagiere",
			["FlatPassengerArea5x5Desc"] = "Flacher Seitenbereich mit Treppe nach draußen, 5x5 m, Passagierstil. Gut geeignet, um Assete darauf zu platzieren. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatPassengerArea10x5Name"] = "10x5 flacher Seitenbereich mit Treppe, Passagiere",
			["FlatPassengerArea10x5Desc"] = "Flacher Seitenbereich mit Treppe nach draußen, 10x5 m, Passagierstil. Gut geeignet, um Assete darauf zu platzieren. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatPassengerArea10x10Name"] = "10x10 flacher Seitenbereich mit Treppe, Passagiere",
			["FlatPassengerArea10x10Desc"] = "Flacher Seitenbereich mit Treppe nach draußen, 10x10 m, Passagierstil. Gut geeignet, um Assete darauf zu platzieren. Passe die Höhe mit <m> und <n> an.",
			["FlatPassengerStation0MName"] = "Kleine glatte Personenbahnhof",
			["FlatPassengerStation0MDesc"] = "Kleine, schicke Personenbahnhof. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatPassengerStation5MName"] = "Kleiner Personenbahnhof, 5 m hoch",
			["FlatPassengerStation5MDesc"] = "Kleiner Personenbahnhof, für den Zugang zu einem Bahnsteig, der etwas höher liegt als die Straße. Passe seine Höhe mit <m> und <n> an. Male den Boden mit <shift> und einem Malwerkzeug neu an.",
			["FlatPassengerStationDown5MName"] = "Kleine Personenbahnhof, 5 m tiefer",
			["FlatPassengerStationDown5MDesc"] = "Kleiner Personenbahnhof, für den Zugang zu einem Bahnsteig, der etwas tiefer liegt als die Straße. Stellen Sie die Höhe mit <m> und <n> ein.",
			["FlatPassengerStationSmallName"] = "Kleiner, verzierter Personenbahnhof",
			["FlatPassengerStationSmallDesc"] = "Kleiner, verzierter Personenbahnhof. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatPassengerStationMidName"] = "Verschnörkelter Personenbahnhof",
			["FlatPassengerStationMidDesc"] = "Verschnörkelter Personenbahnhof. Passen Sie die Höhe mit <m> und <n> an.",
			["FlatPassengerStationLargeName"] = "Verschnörkelter Personenbahnhof",
			["FlatPassengerStationLargeDesc"] = "Verzierter Personenbahnhof mit Unterführung im Inneren. Passen Sie seine Höhe mit <m> und <n> an.",
			["LookUndergroundName"] = "Unterirdisch aussehen",
			["LookUndergroundDesc"] = "Schwebe oder baue dies, um unterirdisch auszusehen, entferne es, wenn du fertig bist",
			["OpenLiftName"] = "Nach oben heben für Bahnsteig am Boden",
			["OpenLiftDesc"] = "Verbindet Bodenbahnsteige mit ihren Zwillingen, mit nahegelegenen Brückenunterführungen oder, wenn Sie einen Ausgang hinzufügen, mit dem Straßennetz.",
			["OpenStairsUpLeftName"] = "Treppe oben links für Bodenbahnsteig",
			["OpenStairsUpLeftDesc"] = "Verbindet Bodenbahnsteige mit ihren Zwillingen, mit nahegelegenen Brückenunterführungen oder, wenn Sie einen Ausgang hinzufügen, mit dem Straßennetz",
			["OpenStairsUpRightName"] = "Treppe oben rechts für Bodenbahnsteig",
			["OpenStairsUpRightDesc"] = "Verbindet Bodenbahnsteige mit ihren Zwillingen, mit nahegelegenen Brückenunterführungen oder, wenn Sie einen Ausgang hinzufügen, mit dem Straßennetz",
			["OpenStairsExitWithEdgeName_2m"] = "Eingang zur Treppe mit Autobrücke",
			["OpenStairsExitWithSnappyEdgeName_2m"] = "Eingang zur Treppe mit zackiger Autobrücke",
			["OpenStairsExitName_4m"] = "Eingang zur Treppe, 4 m",
			["OpenStairsExitName_8m"] = "Eingang zur Treppe, 8 m",
			["OpenStairsExitName_16m"] = "Eingang zur Treppe, 16 m",
			["OpenStairsExitName_32m"] = "Eingang zur Treppe, 32 m",
			["OpenStairsExitName_64m"] = "Eingang zur Treppe, 64 m",
			["OpenStairsExitDesc"] = "Verbindet Treppen und Aufzüge mit dem Außenbereich. Stelle seine Neigung mit <m> und <n> ein. Verbinden Sie sie bei Bedarf mit dem Treppen-Asset ",
			["OpenStairsExitWithEdgeDesc"] = "Verbindet Treppen und Aufzüge mit dem Straßennetz. Passen Sie seine Neigung mit <m> und <n> an. Verknüpfen Sie sie je nach Bedarf mit Treppen, Brücken oder Wegen. Sie wird bei der nächsten Konfigurationsaktualisierung biegsam sein.",
			["OpenStairsExitWithSnappyEdgeDesc"] = "Verbindet Treppen und Aufzüge mit dem Straßennetz. Passen Sie die Neigung mit <m> und <n> an. Verbinden Sie sie je nach Bedarf mit Treppen, Brücken oder Wegen.",
			["PassengerSideLiftName"] = "Personenaufzug zu einer Brückenseite",
			["PassengerSideLiftDesc"] = "Personenaufzug für den Zugang zu einer Bahnsteig auf einer Brücke von der Seite. Er kann an Brückenunterführungen und andere Aufzüge angeschlossen werden, wenn diese nahe genug sind. Maximale Höhe 40 m, einstellbar mit <m> und <n>. Der Boden kann mit <shift> und einem Malwerkzeug neu bemalt werden.",
			["PassengerPlatformLiftName"] = "Personenaufzug zu einer Brücke",
			["PassengerPlatformLiftDesc"] = "Personenaufzug für den Zugang zu einer Bahnsteig auf einer Brücke, von unten. Er kann an Brückenunterführungen und andere Aufzüge angeschlossen werden, wenn diese nahe genug sind. Maximale Höhe 40 m, einstellbar mit <m> und <n>. Der Boden kann mit <shift> und einem Malwerkzeug neu gestrichen werden.",
			["PassengerStationSquareName"] = "Bahnhofsplatz",
			["PassengerStationSquareDesc"] = "Platz zwischen Passagierbahnhöfen und der Straße. Streiche den Boden mit <shift> und einem Malwerkzeug neu.",
			["PassengerStationSquarePlainName"] = "Einfacher Bahnhofsplatz",
			["PassengerStationSquarePlainDesc"] = "Einfacher Platz zwischen Passagierbahnhöfen und der Straße. Male seinen Boden mit <shift> und einem Malwerkzeug neu an.",
			["PlatformEraASwitcherName"] = "Bahnsteig auf Epoche A umstellen",
			["PlatformEraASwitcherDesc"] = "Bahnsteig auf Epoche A umstellen",
			["PlatformEraBSwitcherName"] = "Bahnsteig auf Epoche B umstellen",
			["PlatformEraBSwitcherDesc"] = "Bahnsteig auf Epoche B umstellen",
			["PlatformEraCSwitcherName"] = "Bahnsteig auf Epoche C umstellen",
			["PlatformEraCSwitcherDesc"] = "Bahnsteig auf Epoche C umstellen",
			["PlatformRoofConcreteName"] = "Bahnsteigdach aus Beton mit Spanngliedern",
			["PlatformRoofConcreteDesc"] = "Betondach mit Spanngliedern für Passagierbahnsteige",
			["PlatformRoofConcreteModernName"] = "Modernes Bahnsteigdach aus Beton",
			["PlatformRoofConcreteModernDesc"] = "Modernes Betondach für Passagierbahnsteige",
			["PlatformRoofConcretePlainName"] = "Bahnsteigdach aus Beton, einfach",
			["PlatformRoofConcretePlainDesc"] = "Betondach für Passagierbahnsteige",
			["PlatformRoofIronName"] = "Eisendach",
			["PlatformRoofIronDesc"] = "Eisendach für Passagierbahnsteige",
			["PlatformRoofIronGlassCopperName"] = "Eisen- und Glasdach",
			["PlatformRoofIronGlassCopperDesc"] = "Eisen- und Glasdach für Passagierbahnsteige",
			["PlatformRoofMetalGlassName"] = "Bahnsteigdach aus Glas",
			["PlatformRoofMetalGlassDesc"] = "Glasdach für Passagierbahnsteige",
			["SlopedCargoArea1x5Name"] = "5 m Plattformerweiterung, Fracht-Stil",
			["SlopedCargoArea1x5Desc"] = "Plattformerweiterung, 5 m, Fracht-Stil. Sie fasst zusätzliche Fracht für alle Gleise. Gut geeignet, um Fracht-Assets darauf zu platzieren.",
			["SlopedCargoArea1x10Name"] = "10 m Plattformerweiterung, Fracht-Stil",
			["SlopedCargoArea1x10Desc"] = "Plattformerweiterung, 10 m, Fracht-Stil. Sie fasst zusätzliche Fracht für alle Gleise. Gut geeignet, um Fracht-Assets darauf zu platzieren.",
			["SlopedCargoArea1x20Name"] = "20 m Plattformerweiterung, Fracht-Stil",
			["SlopedCargoArea1x20Desc"] = "Plattformerweiterung, 20 m, Fracht-Stil. Sie fasst zusätzliche Fracht für alle Gleise. Gut geeignet, um Fracht darauf zu platzieren.",
			["SlopedCargoAreaWaiting1x5Name"] = "5 m Plattformerweiterung, dekoriert",
			["SlopedCargoAreaWaiting1x5Desc"] = "Plattformerweiterung, 5 m. Sie enthält und zeigt zusätzliche Fracht für ihr Gleis an.",
			["SlopedCargoAreaWaiting1x10Name"] = "10 m Plattformerweiterung, dekoriert",
			["SlopedCargoAreaWaiting1x10Desc"] = "Plattformerweiterung, 10 m. Sie fasst und zeigt zusätzliche Fracht für ihr Gleis an.",
			["SlopedCargoAreaWaiting1x20Name"] = "20 m Plattformerweiterung, dekoriert",
			["SlopedCargoAreaWaiting1x20Desc"] = "Plattformerweiterung, 20 m. Sie fasst und zeigt zusätzliche Fracht für ihr Gleis an.",
			["SlopedPassengerArea1x2_5Name"] = "2,5 m Bahnsteigerweiterung, Passagier-Stil",
			["SlopedPassengerArea1x2_5Desc"] = "Bahnsteigerweiterung, 2,5 m, Passagierart. Er fasst zusätzliche Passagiere für alle Gleise. Gut geeignet, um Anlagen-Assets darauf zu platzieren.",
			["SlopedPassengerArea1x5Name"] = "5 m Bahnsteigerweiterung, Passagier-Stil",
			["SlopedPassengerArea1x5Desc"] = "Bahnsteigerweiterung, 5 m, Passagier-Stil. Er fasst zusätzliche Passagiere für alle Gleise. Gut geeignet, um Anlagen-Assets darauf zu platzieren.",
			["SlopedPassengerArea1x10Name"] = "Bahnsteigerweiterung, 10 m, Passagier-Stil",
			["SlopedPassengerArea1x10Desc"] = "Bahnsteigerweiterung, 10 m, Passagier-Stil. Er fasst zusätzliche Passagiere für alle Gleise. Gut geeignet, um Anlagen-Assets darauf zu platzieren.",
			["SlopedPassengerArea1x20Name"] = "Bahnsteigerweiterung, 20 m, Passagier-Stil",
			["SlopedPassengerArea1x20Desc"] = "Bahnsteigerweiterung, 20 m, Passagier-Stil. Er fasst zusätzliche Passagiere für alle Gleise. Gut geeignet, um Anlagen-Assets darauf zu platzieren.",
			["SlopedPassengerAreaWaiting1x2_5Name"] = "2,5 m Bahnsteigerweiterung, dekoriert",
			["SlopedPassengerAreaWaiting1x2_5Desc"] = "Bahnsteigerweiterung, 2,5 m. Sie fasst und zeigt zusätzliche Passagiere für ihr Gleis an.",
			["SlopedPassengerAreaWaiting1x5Name"] = "Bahnsteigerweiterung, 5 m, dekoriert",
			["SlopedPassengerAreaWaiting1x5Desc"] = "Bahnsteigerweiterung, 5 m. Sie nimmt zusätzliche Passagiere für ihr Gleis auf und zeigt sie an.",
			["SlopedPassengerAreaWaiting1x10Name"] = "Bahnsteigerweiterung, 10 m, dekoriert",
			["SlopedPassengerAreaWaiting1x10Desc"] = "Bahnsteigerweiterung, 10 m. Sie fasst und zeigt zusätzliche Passagiere für ihr Gleis an.",
			["SlopedPassengerAreaWaiting1x20Name"] = "Bahnsteigerweiterung, 20 m, dekoriert",
			["SlopedPassengerAreaWaiting1x20Desc"] = "Bahnsteigerweiterung, 20 m. Sie nimmt zusätzliche Passagiere für ihr Gleis auf und zeigt sie an.",
			["SubwayName"] = "Unterirdischer Eingang",
			["SubwayDesc"] = "Platzieren Sie diese in der Nähe eine Freestyle-Bahnhofs und verbinden Sie sie mit dem Popup. Stellen Sie sicher, dass Ihr Bahnhof Unterführungen und / oder U-Bahn-Treppen hat.",
			["TrackCrossingName"] = "Gleisübergang für zwei Gleise",
			["TrackCrossingDesc"] = "Er verbindet einen Bahnsteig und kann eine Verbindung zum Straßennetz oder zu einem gegenüberliegenden Zwilling herstellen, wenn dieser nahe genug ist.",
			["TrackCrossingTwoStairsName"] = "Gleisübergang für ein einzelnes Gleis",
			["TrackCrossingTwoStairsDesc"] = "Er verbindet zwei gegenüberliegende Bahnsteige, wenn sie nahe genug beieinander liegen.",
			["TunnelStairsUpName"] = "U-Bahn-Treppe nach oben",
			["TunnelStairsUpDesc"] = "Verbindet unterirdische Passagierbahnsteige mit den U-Bahn-Eingängen und den anderen Terminals darüber.",
			["TunnelStairsUpDownName"] = "U-Bahn-Treppen nach oben und unten",
			["TunnelStairsUpDownDesc"] = "Verbindet die unterirdischen Passagierbahnsteige mit den U-Bahn-Eingängen und den anderen Terminals oben und unten.",
			["UndergroundName"] = "Unterirdischer Bahnhof",
			["UnderpassName"] = "Überdachte Unterführung",
			["UnderpassDesc"] = "Wenn sie auf dem Boden liegt, verbindet sie die Bahnsteige mit den U-Bahn-Eingängen, die Aufzüge mit den Brücken und anderen Unterführungen auf dem Boden. Wenn sie stattdessen auf einer Brücke steht, verbindet sie Aufzüge zu Brücken, andere Brückenunterführungen, Bahnsteigtreppen und Aufzüge, die nahe genug sind.",
			["UnderpassStairsName"] = "Unterführung",
			["UnderpassStairsDesc"] = "Wenn sie auf dem Boden liegt, verbindet sie Passagierbahnsteige mit U-Bahn-Eingängen, Aufzügen mit Brücken und anderen Unterführungen am Boden. Wenn sie stattdessen auf einer Brücke steht, verbindet sie Aufzüge zu Brücken, andere Brückenunterführungen, Bahnsteigtreppen und Aufzüge, die nahe genug sind.",
			["WallBricksName"] = "Backsteinmauer",
			["WallBricksDesc"] = "Backsteinmauer, auch für Tunnel geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallConcreteModernName"] = "Betonwand, modern",
			["WallConcreteModernDesc"] = "Betonmauer, auch für Tunnels geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallConcretePlainName"] = "Betonwand, schlicht",
			["WallConcretePlainDesc"] = "Betonmauer, auch für Tunnels geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallConcretePlainWRoofName"] = "Betonwand und Dach, glatt",
			["WallConcretePlainWRoofDesc"] = "Betonwand und -dach für Passagierbahnsteige",
			["WallIronName"] = "Eisenzaun",
			["WallIronDesc"] = "Eisenzaun, auch für Tunnel geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallIronGlassCopperName"] = "Wand aus Eisen und Glas",
			["WallIronGlassCopperDesc"] = "Eisen- und Glaswand, auch für Tunnels geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallIronGlassCopperWRoofName"] = "Eisen- und Glaswand und Dach",
			["WallIronGlassCopperWRoofDesc"] = "Eisen- und Glaswand und -dach für Passagierbahnsteige",
			["WallStaccionataFsName"] = "1,4m Betonzaun",
			["WallStaccionataFsDesc"] = "1,4m Betonzaun, auch für Tunnel geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallStaccionataFsTallName"] = "2m Betonzaun",
			["WallStaccionataFsTallDesc"] = "2m Betonzaun, auch für Tunnel geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallTiledName"] = "Geflieste Wand, älter",
			["WallTiledDesc"] = "Geflieste Wand, auch für Tunnel geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallTiledWLargeStripesName"] = "Geflieste Wand, neuere",
			["WallTiledWLargeStripesDesc"] = "Geflieste Wand, auch für Tunnel geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallTiledWRoofName"] = "Geflieste Wand und Dach",
			["WallTiledWRoofDesc"] = "Geflieste Wand und Dach für Passagierbahnsteige",
			["WallMetalGlassName"] = "Glaswand",
			["WallMetalGlassDesc"] = "Glaswand, auch für Tunnels geeignet. Schräglage mit <m> und <n> einstellen.",
			["WallMetalGlassWRoofName"] = "Glaswand und Dach",
			["WallMetalGlassWRoofDesc"] = "Glaswand und -dach für Passagierbahnsteige",
			["EraACargoPlatform5MName"] = "5 m Frachtplattform, Epoche A",
			["EraACargoPlatform5MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 5 m breit, Epoche A. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraACargoPlatform10MName"] = "10 m Frachtplattform, Epoche A",
			["EraACargoPlatform10MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 10 m breit, Epoche A. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraACargoPlatform20MName"] = "20 m Frachtplattform, Epoche A",
			["EraACargoPlatform20MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 20 m breit, Epoche A. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraBCargoPlatform5MName"] = "5 m Frachtplattform, Epoche B",
			["EraBCargoPlatform5MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 5 m breit, Epoche B. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraBCargoPlatform10MName"] = "10 m Frachtplattform, Epoche B",
			["EraBCargoPlatform10MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 10 m breit, Epoche B. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraBCargoPlatform20MName"] = "20 m Frachtplattform, Epoche B",
			["EraBCargoPlatform20MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 20 m breit, Epoche B. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraCCargoPlatform5MName"] = "5 m Frachtplattform, Epoche C",
			["EraCCargoPlatform5MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 5 m breit, Epoche C. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraCCargoPlatform10MName"] = "10 m Frachtplattform, Epoche C",
			["EraCCargoPlatform10MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 10 m breit, Epoche C. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraCCargoPlatform20MName"] = "20 m Frachtplattform, Epoche C",
			["EraCCargoPlatform20MDesc"] = "Frachtplattformen, die als Gleise zu verlegen sind, 20 m breit, Epoche C. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["LolloFreestyleTrainStationName"] = "Freestyle-Bahnhof",
			["LolloFreestyleTrainStationDesc"] = "Freestyle-Bahnhof",
			["PlatformWaypointName"] = "Bahnsteigmarker",
			["PlatformWaypointDesc"] = "Markiert die Enden eines Bahnsteigs, der Teil eines Freestyle-Bahnhofs wird. Die Richtung spielt keine Rolle; wenn es in der Nähe bereits einen Teiler gibt, hat dieser Vorrang; wenn der Bahnsteig in der Nähe endet, hat dieses Ende eine höhere Priorität.",
			["EraAPassengerPlatform5MName"] = "5 m Personenbahnsteig, Epoche A",
			["EraAPassengerPlatform5MDesc"] = "Personenbahnsteige, die als Gleise zu verlegen sind, 5 m breit, Epoche A. Verwenden Sie sie mit Tunneln oder Brücken. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraAPassengerPlatform2_5MName"] = "2,5 m Personenbahnsteig, Epoche A",
			["EraAPassengerPlatform2_5MDesc"] = "Personenbahnsteige, die als Gleise zu verlegen sind, 2,5 m breit, Epoche A. Die beste Wahl für Bahnhöfe am Boden. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraBPassengerPlatform5MName"] = "5 m Personenbahnsteig, Epoche B",
			["EraBPassengerPlatform5MDesc"] = "Personenbahnsteige, die als Gleise zu verlegen sind, 5 m breit, Epoche B. Verwenden Sie sie mit Tunneln oder Brücken. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraBPassengerPlatform2_5MName"] = "2,5 m Personenbahnsteig, Epoche B",
			["EraBPassengerPlatform2_5MDesc"] = "Als Gleise zu verlegende Personenbahnsteige, 2,5 m breit, Epoche B. Die beste Wahl für Bahnhöfe am Boden. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraCPassengerPlatform5MName"] = "5 m Personenbahnsteig, Epoche C",
			["EraCPassengerPlatform5MDesc"] = "Personenbahnsteige, die als Gleise zu verlegen sind, 5 m breit, Epoche C. Verwenden Sie sie mit Tunneln oder Brücken. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["EraCPassengerPlatform2_5MName"] = "2,5 m Personenbahnsteig, Epoche C",
			["EraCPassengerPlatform2_5MDesc"] = "Personenbahnsteige, die als Gleise zu verlegen sind, 2,5 m breit, Epoche C. Die beste Wahl für Bahnhöfe am Boden. Sie sind eigentlich Langsamfahrgleise, die nicht mit Bü überquert werden sollen.",
			["TrackWaypointName"] = "Gleismarker",
			["TrackWaypointDesc"] = "Markiert die Enden eines Gleises, das Teil eines Freestyle-Bahnhofs wird. Die Richtung spielt keine Rolle; wenn es in der Nähe bereits einen Teiler gibt, hat dieser Vorrang; wenn der Track in der Nähe endet, hat dieses Ende eine höhere Priorität. Nahegelegene Semaphoren können stören, Sie sollten sie entfernen und wieder einfügen, sobald der Bahnhof angelegt ist.",

			["CementBridgeGlassWallNoPillars"] = "Betonbrücke mit Unterführungen, Glasschirmen und ohne Pfeiler. Nur für 5-m-Bahnsteigen.",
			["CementBridgeGlassWallNormalPillars"] = "Betonbrücke mit Unterführungen und Glasschilden. Nur für 5 m Bahnsteige.",
			["CementBridgeGlassWallSpacedPillars"] = "Betonbrücke mit Unterführungen, Glasschilden und Abstandspfeilern. Nur für 5 m Bahnsteige.",
			["CementBridgeNoPillarsNoSides"] = "Betonbrücke ohne Pfeiler und ohne Geländer, kompatibel mit 2,5 m Bahnsteigen",
			["CementBridgeNormalPillarsNoSides"] = "Betonbrücke ohne Geländer, kompatibel mit 2,5 m hohen Bahnsteigen",
			["CementBridgeSpacedPillarsNoSides"] = "Betonbrücke mit Abstandspfeilern und ohne Geländer, kompatibel mit 2,5 m hohen Bahnsteigen",
			["IronBridgeNoPillarsNoSides"] = "Eisenbrücke ohne Pfeiler und ohne Geländer, kompatibel mit 2,5 m hohen Bahnsteigen",
			["IronBridgeNormalPillarsNoSides"] = "Eisenbrücke ohne Geländer, kompatibel mit 2,5 m Bahnsteigen",
			["IronBridgeSpacedPillarsNoSides"] = "Eisenbrücke mit Abstandspfeilern und ohne Geländer, kompatibel mit 2,5 m hohen Bahnsteigen",
			["PedestrianCementBridgeNoPillars"] = "Betonbrücke ohne Pfeiler. Für Fußgängerwege",
			["PedestrianCementBridgeNoPillarsNoSides"] = "Betonbrücke ohne Pfeiler und ohne Geländer. Für Fußgängerwege und 2,5 m hohe Bahnsteigen",
			["era_a_PedestrianBasicBridgeNoPillars"] = "Epoche A-Brücke ohne Pfeiler, für Fußgängerwege",
			["era_a_PedestrianBasicBridgeNoPillarsNoSides"] = "Brücke der Epoche A ohne Pfeiler und ohne Geländer, für Fußgängerwege und 2,5 m hohe Bahnsteige",
			["era_b_PedestrianBasicBridgeNoPillars"] = "Epoche-B-Brücke ohne Pfeiler, für Fußgängerwege",
			["era_b_PedestrianBasicBridgeNoPillarsNoSides"] = "Brücke der Epoche B ohne Pfeiler und ohne Geländer, für Fußgängerwege und 2,5 m hohe Bahnsteige",
			["era_c_PedestrianBasicBridgeNoPillars"] = "Epoche-C-Brücke ohne Pfeiler, für Fußgängerwege",
			["era_c_PedestrianBasicBridgeNoPillarsNoSides"] = "Brücke der Epoche C ohne Pfeiler und ohne Geländer, für Fußgängerwege und 2,5 m hohe Bahnsteige",

			["NewStationName"] = "Neuer Bahnhof",

			-- Kategorien
			["cargo-platform-extensions"] = "Frachterweiterungen",
			["cargo-platform-tracks"] = "Frachtplattformen, die als Gleise zu verlegen sind",
			["cargo-road-access"] = "Fracht Seite -> Straße",
			["cargo-road-access-axial"] = "Fracht Ende -> Straße",
			["cargo-shelves"] = "Frachtregale",
			["passenger-platform-extensions"] = "Passagiererweiterung",
			["passenger-platform-tracks"] = "Passagierbahnsteige, die als Gleise zu verlegen sind",
			["passenger-road-access"] = "Passagiere Seite -> Straße",
			["passenger-road-access-axial"] = "Passagiere Ende -> Straße",
			["passenger-road-access-stairs"] = "Treppe -> Straße",
			["passenger-up-and-down"] = "Auf und ab",
			["platform-deco"] = "Plattform-Deko",
			["track-crossings"] = "Gleiswege",
			["track-deco"] = "Gleis-Deko",
			["train-tracks"] = "Bahngleise",
			["waypoints-for-freestyle-station"] = "Marker für Freestyle-Bahnhöfe",

			-- Meldungen
			["BuildInProgress"] = "Bau eines Bahnsteigs...",
			["BuildMoreWaypoints"] = "Setze zwei Gleismarker und zwei Bahnsteigmarker ein, um einen Freestyle-Bahnhof zu bauen",
			["BuildSnappyTracksFailed"] = "Repariere die Bahnhofsverbindungen zu den angrenzenden Gleisen, das Spiel kann es diesmal nicht für dich tun",
			["ConConfigWindowTitle"] = "Konfiguration",
			["DifferentPlatformWidths"] = "Vermeide unterschiedliche Gleisbreiten bei Frachtbahnhöfen",
			["GoBack"] = "Zurückgehen",
			["GoThere"] = "Dorthin gehen",
			["Join"] = "Beitreten",
			["NeedAdjust4Snap"] = "Einige Straßenverbindungen haben sich gelöst: Nehmen Sie eine Änderung an der Bahnhofskonfiguration vor, um dies zu beheben",
			["NoJoin"] = "Nicht verbinden",
			["RestoreInProgress"] = "Zurücksetzen von Bahnsteig und Gleis...",
			["ShowUnderground"] = "U-Bahn anzeigen",
			["ShowUndergroundTool"] = "U-Bahn anzeigen",
			["ShowUndergroundTooltip"] = "Einmal platziert, kann es nicht mehr geändert werden. Wenn Sie Hilfe bei der Platzierung wünschen, verwenden Sie stattdessen die Gleiskonstruktion 'Look Underground'.",
			["StationPickerWindowTitle"] = "Wählen Sie eine Station zum Einsteigen",
			["SubwayCannotConnect"] = "Fügen Sie Treppen oder Unterführungen hinzu, um diesen unterirdischen Eingang zu verbinden",
			["SubwayNotConnected"] = "Verbinden Sie diesen unterirdischen Eingang mit einem Bahnhof",
			["TrackWaypointBuiltOnPlatform"] = "Sie können Gleismarker nur auf Gleisen und Bahnsteigmarker nur auf Bahnsteigen bauen",
			["TrackWaypointsMissing"] = "Baue zuerst zwei Gleismarker",
			["UndergroundTrainDepotName"] = "U-Bahn-Depot",
			["UndergroundTrainDepotDesc"] = "Wird zum Kauf/Verkauf von Zügen verwendet. Die Gleiskonstruktion 'Look Underground' hilft beim Einrasten auf dem Gleis.",
			["Wait4Join"] = "Das Verbinden kann eine Weile dauern, warte ein bisschen!",
			["WarningWindowTitle"] = "Warnung",
			["WaypointAlreadyBuilt"] = "Du kannst nur zwei Markierungen bauen",
			["WaypointsCrossCrossing"] = "Es gibt eine Verbindung zwischen diesem Marker und seinem Zwilling",
			["WaypointsCrossSignal"] = "Zwischen dieser Markierung und ihrem Zwilling befindet sich ein Semaphor oder ein Wegpunkt, oder zu nahe an einem von beiden",
			["WaypointsCrossStation"] = "Sie können eine bestehende Station nicht kreuzen",
			["WaypointDistanceWindowTitle"] = "Luftentfernung",
			["WaypointsNotConnected"] = "Dieser Marker ist nicht mit seinem Zwilling verbunden, oder es liegt ein Bahnhof / eine Verbindung / ein Semaphor dazwischen, oder er ist zu nahe an einem Bahnhof / einer Verbindung / einem Semaphor",
			["WaypointsTooCloseToStation"] = "Zu nahe an einem bestehenden Bahnhof oder Depot. Schneiden Sie das Gleis mit dem Gleisteiler, wenn Sie näher herankommen müssen. Die Bahnsteigköpfe verbinden sich automatisch, wenn sie näher als 7 Meter sind",
			["WaypointsTooFar"] = "Zu weit von seinem Zwilling entfernt",
			["WaypointsWrong"] = "Platziere zwei Marker auf demselben Bahnsteig und zwei auf demselben Gleis",

			-- lose offene Treppen und lose Aufzüge
			["BaseMode"] = "Basismodus",
			["BridgeHeight"] = "Brückenhöhe",
			["BridgeMode"] = "Brückenmodus",
			["BridgeYAngle"] = "Neigung der Brücke",
			["BridgeZAngle"] = "Brückendrehung",
			["EdgeWithBridge"] = "Automatische Brücke",
			["EdgeWithNoBridge"] = "Automatischer Pfad",
			["Zeitalter"] = "Zeitalter",
			["ErrorReplacingConWithSnappyCopy"] = "Dieses Objekt kann nicht an nahe gelegene Straßen angeschlossen werden, ändern Sie es oder verschieben Sie es woanders hin",
			["FlatSlopedTerrain"] = "Gefälle des Geländes",
			["Model"] = "Bahnsteig",
			["ModelRaised"] = "Erhöhte Bahnsteig",
			["NoRailing0"] = "0 - Kein Geländer",
			["OpenTwinStairsFreeName"] = "Zwillingstreppe",
			["OpenTwinStairsFreeDesc"] = "Zwillingstreppe, passend zu den Freestyle-Bahnhöfen, kollisionstolerant; verwende Zäune oder ähnliche Mods, um Kollisionen abzustimmen. Kombiniere dies mit Fußgängerbrücken oder -wegen. Platziere sie genau mit dem \"Construction Mover\".",
			["OpenLiftFreeDesc"] = "Aufzug passend zu den Freestyle-Bahnhöfen, kollisionstolerant; verwende Zäune oder ähnliche Mods zur Feinabstimmung von Kollisionen. Kombiniere ihn mit Fußgängerbrücken oder -wegen. Platziere ihn genau mit dem \"Construction Mover\".",
			["OpenLiftFreeName"] = "Aufzug",
			["OpenStairsFreeDesc"] = "Treppen, die zu den Freestyle-Bahnhöfen passen, kollisionstolerant; verwende Zäune oder ähnliche Mods zur Feinabstimmung von Kollisionen. Kombiniere dies mit Fußgängerbrücken oder -wegen. Platziere sie genau mit dem \"Construction Mover\". Sie kann auch Fracht transportieren.",
			["OpenStairsFreeHeight"] = "Höhe",
			["OpenStairsFreeName"] = "Treppe",
			["PedestrianBridges"] = "Fußgängerbrücken",
			["PedestrianPaths"] = "Fußgängerwege",
			["SimpleConnection"] = "Einfach",
			["SnappyEdgeWithBridge"] = "Snappy-Brücke",
			["SnappyEdgeWithNoBridge"] = "Snappy-Pfad",
			["Stairs"] = "Treppen, Aufzüge, unterirdische Eingänge, Assets für den Freestyle-Bahnhof",
			["StairsBase"] = "Basis ausbauen",
			["StairsBaseTooltip"] = "Es könnte einfacher sein, beim Erstellen oder Ändern von Eigenschaften \"Automatischer Pfad\" oder \"Automatische Brücke\" auszuwählen und danach in \"Snappy-Pfad\" oder \"Snappy-Brücke\" zu ändern. Überprüfen Sie die Verbindungen mit AltGr + L.",
			["TerrainAlignmentType"] = "Terrainausrichtung",
			["TerrainAlignmentTypeFlat"] = "Flach",
			["TerrainAlignmentTypeSloped"] = "Abgeschrägt",
			["TopPlatformLength"] = "Obere Bahnsteiglänge",
			["TopPlatformLengthTooltip"] = "Es könnte einfacher sein, beim Erstellen oder Ändern von Eigenschaften die Option \"Auto Path\" oder \"Auto Bridge\" auszuwählen und sie anschließend in \"Snappy-Pfad\" oder \"Snappy-Brücke\" zu ändern. Überprüfen Sie die Verbindungen mit AltGr + L.",
			["TopPlatformNorthLength"] = "Obere Bahnsteig Eins",
			["TopPlatformSouthLength"] = "Oberste Bahnsteig Zwei",
			["TopPlatformNorthLengthTooltip"] = "Es könnte einfacher sein, beim Erstellen oder Ändern von Eigenschaften die Option \"Automatische Brücke\" auszuwählen und sie nach Abschluss in \"Snappy-Brücke\" zu ändern. Überprüfen Sie die Verbindungen mit AltGr + L.",

			-- Gleisteiler
			["TrackSplitterName"] = "Gleisteiler",
			["TrackSplitterDesc"] = "Teilt ein Gleis in zwei Abschnitte. Funktioniert nicht bei Gleisen, die Teil einer Konstruktion sind (z.B. ein Bahnhof). Verwenden Sie AltGr + L, um die Wirkung zu sehen.",

			-- Bahnsteige als Asset
			["PlatformAsAssetName"] = "Bahnsteig als Asset",
			["PlatformAsAssetDesc"] = "Bahnsteig als Asset. Passen Sie sie mit dem \"Construction Mover\" an.",
			["PlatformAsAsset_CargoOrPassengers"] = "Fracht oder Passagiere",
			["PlatformAsAsset_Cargo"] = "Fracht",
			["PlatformAsAsset_Passengers"] = "Passagiere",
			["PlatformAsAsset_X10m"] = "X Größe, grob, m",
			["PlatformAsAsset_X1m"] = "X Größe, fein, m",
			["PlatformAsAsset_Y10m"] = "Y-Größe, grob, m",
			["PlatformAsAsset_Y1m"] = "Y-Größe, fein, m",

			["TilesHexagonClean"] = "Kacheln Sechseck, sauber",

			-- Zaun-Assets
			["FenceAssetsName"] = "Mauern und Zäune",
			["FenceAssetsDesc"] = "Mauern und Zäune, die zu den Freestyle-Bahnhöfen passen. Passen Sie sie mit dem \"Construction Mover\" an.",
			["fenceModelName"] = "Mauer oben",
			["wallEraPrefix_0IsNoWall"] = "Wand unten Epoche",
			["NoWall"] = "Keine Wand unten",
			["Length"] = "Länge m",
		},
	}
end
