function data()
	return {
		en = {
			["DESC"] = [[
				A freestyle train station.
			]],
			["NAME"] = "Freestyle train station",
			["BuildMoreWaypoints"] = "Plop two track markers and two platform markers to build a freestyle station",
			["GoBack"] = "Go back",
			["GoThere"] = "Go there",
			["Join"] = "Join",
			["NoJoin"] = "Do not join",
			["StairsName"] = "Stairs",
			["StairsDesc"] = "Stairs, 2 m",
			["FlatPassengerArea5x5Name"] = "5x5 Flat Side area",
			["FlatPassengerArea5x5Desc"] = "Flat side area, 5x5 m",
			["FlatPassengerArea10x5Name"] = "10x5 Flat Side area",
			["FlatPassengerArea10x5Desc"] = "Flat side area, 10x5 m",
			["FlatPassengerArea10x10Name"] = "10x10 Flat Side area",
			["FlatPassengerArea10x10Desc"] = "Flat side area, 10x10 m",
			["SlopedPassengerArea1x5Name"] = "5 m Sloped side area",
			["SlopedPassengerArea1x5Desc"] = "Sloped side area, 5 m",
			["SlopedPassengerArea1x10Name"] = "10 m Sloped side area",
			["SlopedPassengerArea1x10Desc"] = "Sloped side area, 10 m",
			["SlopedPassengerArea1x20Name"] = "20 m Sloped side area",
			["SlopedPassengerArea1x20Desc"] = "Sloped side area, 20 m",
			["CargoPlatform5MTracksName"] = "5 m Cargo Platform",
			["CargoPlatform5MTracksDesc"] = "Cargo Platforms to Be Laid as Tracks, 5 m wide",
			["CargoPlatform10MTracksName"] = "10 m Cargo Platforms",
			["CargoPlatform10MTracksDesc"] = "Cargo Platforms to Be Laid as Tracks, 10 m wide",
			["CargoPlatform20MTracksName"] = "20 m Cargo Platforms",
			["CargoPlatform20MTracksDesc"] = "Cargo Platforms to Be Laid as Tracks, 20 m wide",
			["PlatformWaypointName"] = "Platform End Marker",
			["PlatformWaypointDesc"] = "Mark the ends of a platform that will become part of a freestyle station",
			["PassengerPlatform5MTracksName"] = "5 m Passenger Platforms",
			["PassengerPlatform5MTracksDesc"] = "Passenger Platforms to Be Laid as Tracks, 5 m wide. Use them at tunnel entrances, to make the ends meet.",
			["PassengerPlatform2_5MTracksName"] = "2.5 m Passenger Platforms",
			["PassengerPlatform2_5MTracksDesc"] = "Passenger Platforms to Be Laid as Tracks, 2.5 m wide",
			["Cargo-Platform-Tracks"] = "Cargo platforms to be laid as tracks",
			["Passenger-Platform-Tracks"] = "Passenger platforms to be laid as tracks",
			["StationPickerWindowTitle"] = "Pick a station to join",
			["TrackWaypointBuiltOnPlatform"] = "You can only build track markers on tracks and platform markers on platforms",
			["TrackWaypointName"] = "Track End Marker",
			["TrackWaypointDesc"] = "Mark the ends of a track that will become part of a freestyle station",
			["TrackWaypointsMissing"] = "Build two track markers first",
			["UnderpassName"] = "Underpass",
			["UnderpassDesc"] = "Underpasses",
			["WarningWindowTitle"] = "Warning",
			["WaypointAlreadyBuilt"] = "You can only build two markers",
			["WaypointsCrossStation"] = "You cannot cross an existing station",
			["WaypointsNotConnected"] = "This markers is not connected to its twin",
			["WaypointsTooFar"] = "Too far from its twin",
		},
	}
end
