local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local slotHelpers = require('lollo_freestyle_train_station.slotHelpers')
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-shelves", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("CargoShelfIronName"),
			description = _("CargoShelfIronDesc"),
			icon = "ui/lollo_freestyle_train_station/cargoShelfIron.tga"
		},
		metadata = { },
		order = {
			value = 11,
		},
		type = _constants.cargoShelfModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
			local eraPrefix = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)
			if eraPrefix == moduleHelpers.eras.era_a.prefix then
				moduleHelpers.cargoShelves.doCargoShelf(
					result, slotTransf, tag, slotId, params, nTerminal, _terminalData, nTrackEdge,
					'lollo_freestyle_train_station/cargo_shelves/dark_iron/brackets_5m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/dark_iron/brackets_10m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/dark_iron/brackets_20m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/dark_iron/legs_5m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/dark_iron/legs_10m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/dark_iron/legs_20m.mdl'
				)
			else
				moduleHelpers.cargoShelves.doCargoShelf(
					result, slotTransf, tag, slotId, params, nTerminal, _terminalData, nTrackEdge,
					'lollo_freestyle_train_station/cargo_shelves/iron/brackets_5m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/iron/brackets_10m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/iron/brackets_20m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/iron/legs_5m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/iron/legs_10m.mdl',
					'lollo_freestyle_train_station/cargo_shelves/iron/legs_20m.mdl'
				)
			end
		end,

		getModelsFn = function(params)
			local results = {}
			for x = -2, 2 do
				results[#results+1] = {
					id = 'lollo_freestyle_train_station/cargo_shelves/iron/brackets_5m.mdl',
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  x, 0, 0, 1},
				}
			end
			results[#results+1] = {
				id = 'lollo_freestyle_train_station/cargo_shelves/iron/legs_5m.mdl',
				transf = {-1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1},
			}
		return results
		end
	}
end
