local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local slotHelpers = require('lollo_freestyle_train_station.slotHelpers')
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "platform-deco", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("PlatformRoofIronName"),
			description = _("PlatformRoofIronDesc"),
			icon = "ui/lollo_freestyle_train_station/platformRoofIron.tga"
		},
		metadata = { },
		order = {
			value = 12,
		},
		type = _constants.platformRoofModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			moduleHelpers.deco.doPlatformRoof(result, slotTransf, tag, slotId, params, nTerminal, nTrackEdge,
			_constants.platformRoofIronCeiling2_5MModelFileName, _constants.platformRoofIronCeiling5MModelFileName,
			'lollo_freestyle_train_station/roofs/iron/platformRoofPillarDeco_2_5m.mdl', 'lollo_freestyle_train_station/roofs/iron/platformRoofPillarDeco_5m.mdl')
		end,

		getModelsFn = function(params)
			local results = {}
			for x = -2, 2 do
				results[#results+1] = {
					id = _constants.platformRoofIronCeiling2_5MModelFileName,
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  x, 0, 0, 1},
				}
			end
			results[#results+1] = {
				id = 'lollo_freestyle_train_station/roofs/iron/platformRoofPillarDeco_2_5m.mdl',
				transf = {-1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1},
			}
		return results
		end
	}
end
