local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { 'platform-deco', },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _('PlatformRoofIronLightName'),
			description = _('PlatformRoofIronLightDesc'),
			icon = 'ui/lollo_freestyle_train_station/platformRoofIronLight.tga'
		},
		metadata = { },
		order = {
			value = 13,
		},
		type = _constants.platformRoofModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			moduleHelpers.deco.doPlatformRoof(result, slotTransf, tag, slotId, params, nTerminal, nTrackEdge,
			'lollo_freestyle_train_station/roofs/iron_light/platformRoofCeiling_2_5m.mdl',
			'lollo_freestyle_train_station/roofs/iron_light/platformRoofCeiling_5m.mdl',
			'lollo_freestyle_train_station/roofs/iron_light/platformRoofPillarDeco_2_5m.mdl',
			'lollo_freestyle_train_station/roofs/iron_light/platformRoofPillarDeco_5m.mdl')
		end,

		getModelsFn = function(params)
			local results = {}
			for x = -2, 2 do
				results[#results+1] = {
					id = 'lollo_freestyle_train_station/roofs/iron_light/platformRoofCeiling_2_5m.mdl',
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  x, 0, 0, 1},
				}
			end
			results[#results+1] = {
				id = 'lollo_freestyle_train_station/roofs/iron_light/platformRoofPillarDeco_2_5m.mdl',
				transf = {-1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1},
			}
		return results
		end
	}
end
