local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
-- local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "passenger-road-access", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("PassengerSideLiftName"),
		description = _("PassengerSideLiftDesc"),
		icon = "ui/lollo_freestyle_train_station/passengerSideLift.tga"
	},
	metadata = { },
	order = {
		value = 41,
	},
	type = _constants.passengerSideLiftModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not nTrackEdge or not baseId then return end

		-- LOLLO NOTE tag looks like '__module_201030', never mind what you write into it, the game overwrites it
		-- in base_config.lua
		-- Set it into the models so the game knows what module they belong to.
		local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
		local buildingHeight = moduleHelpers.lifts.tryGetLiftHeight(params, nTerminal, nTrackEdge, slotId)
		if not(buildingHeight) then return end
		local buildingModelId = moduleHelpers.lifts.tryGetSideLiftModelId(params, nTerminal, nTrackEdge, era, buildingHeight)
		if not(buildingModelId) then return end

		local buildingTransf = transfUtilsUG.mul(
			slotTransf,
			{ 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 }
		)
		result.models[#result.models + 1] = {
			id = buildingModelId,
			slotId = slotId,
			transf = buildingTransf,
			tag = tag
		}

		if result.terminateConstructionHookInfo.liftBottomPositions[nTerminal] == nil then result.terminateConstructionHookInfo.liftBottomPositions[nTerminal] = {} end
		result.terminateConstructionHookInfo.liftBottomPositions[nTerminal][#result.terminateConstructionHookInfo.liftBottomPositions[nTerminal]+1] = {
			t = nTerminal,
			pos2Link = transfUtils.transf2Position(
					transfUtilsUG.mul(buildingTransf, { 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, -2.0, -buildingHeight + _constants.underpassZ, 1 })
				)
		}

		table.insert(result.slots, {
			id = result.mangleId(nTerminal, nTrackEdge, _constants.idBases.stationSquareOuterSlotId),
			shape = 1,
			spacing = {-1, 4, 4, 4},
			transf = transfUtilsUG.mul(
				buildingTransf,
				{ 0, -1, 0, 0,  1, 0, 0, 0,  0, 0, 1, 0,  0, -4.75, 0, 1 }
			),
			type = _constants.passengerStationSquareModuleType,
		})
		table.insert(result.slots, {
			id = result.mangleId(nTerminal, nTrackEdge, _constants.idBases.stationSquareInnerSlotId),
			shape = 1,
			spacing = {-1, 4, 4, 4},
			transf = transfUtilsUG.mul(
				buildingTransf,
				{ 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0.75, 0, 1 }
			),
			type = _constants.passengerStationSquareModuleType,
		})

		-- add some deco
		local _clockY = era == moduleHelpers.eras.era_a.prefix and -3.95 or -4.3
		local clockModelId = era == moduleHelpers.eras.era_c.prefix
			and 'station/rail/asset/era_c_big_clock.mdl'
			or 'station/rail/asset/era_a_big_clock.mdl'
		if buildingHeight == 10 then
			result.models[#result.models + 1] = {
				id = clockModelId,
				slotId = slotId,
				transf = transfUtilsUG.mul(
					buildingTransf,
					{ 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, _clockY, - 3.8, 1 }
				),
				tag = tag
			}
		elseif buildingHeight >= 15 then
			result.models[#result.models + 1] = {
				id = clockModelId,
				slotId = slotId,
				transf = transfUtilsUG.mul(
					buildingTransf,
					{ 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, _clockY, - 5.8, 1 }
				),
				tag = tag
			}
		end

		if era == moduleHelpers.eras.era_c.prefix then
			local _tableY = 0.8
			if buildingHeight == 10 then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/asset/tabellone_hanging.mdl',
					slotId = slotId,
					transf = transfUtilsUG.mul(
						buildingTransf,
						{ 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, _tableY, 5.2 - buildingHeight, 1 }
					),
					tag = tag
				}
			elseif buildingHeight >= 15 then
				result.models[#result.models + 1] = {
					id = 'lollo_freestyle_train_station/asset/tabellone_hanging.mdl',
					slotId = slotId,
					transf = transfUtilsUG.mul(
						buildingTransf,
						{ 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, _tableY, 4.5 - buildingHeight, 1 }
					),
					tag = tag
				}
			end
		end

		if era ~= moduleHelpers.eras.era_a.prefix and buildingHeight > 0 then
			result.models[#result.models + 1] = {
				id = 'lollo_freestyle_train_station/asset/arrivi.mdl',
				slotId = slotId,
				transf = transfUtilsUG.mul(
					buildingTransf,
					{ 1, 0, 0, 0,  0, -1, 0, 0,  0, 0, 1, 0,  2.7, -3.3, 0, 1 }
				),
				tag = tag
			}
			result.models[#result.models + 1] = {
				id = 'lollo_freestyle_train_station/asset/partenze.mdl',
				slotId = slotId,
				transf = transfUtilsUG.mul(
					buildingTransf,
					{ -1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  -2.7, -3.3, 0, 1 }
				),
				tag = tag
			}
		end

		moduleHelpers.lifts.doTerrain4SideLifts(buildingHeight, slotTransf, result,
		_constants.era_c_groundFacesFillKey, _constants.era_c_groundFacesStrokeOuterKey)
	end,

	getModelsFn = function(params)
		return {
			{
				id = 'lollo_freestyle_train_station/lift/side_lifts_9_5_20.mdl',
				transf = { 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 },
			},
		}
	end
}

end
