local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = moduleHelpers.eras.era_b.startYear,
		yearTo = 0
	},
	category = {
		categories = { "passenger-road-access", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("PassengerStationSquarePlainName"),
		description = _("PassengerStationSquarePlainDesc"),
		icon = "ui/lollo_freestyle_train_station/passengerStationSquarePlain.tga"
	},
	metadata = { },
	order = {
		value = 52,
	},
	type = _constants.passengerStationSquareModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not nTrackEdge or not baseId then return end

		local buildingHeight = moduleHelpers.lifts.tryGetLiftHeight(params, nTerminal, nTrackEdge)
		if not(buildingHeight) then return end
		print('buildingHeight =', buildingHeight)

		local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
		local modelId = nil
		if era == moduleHelpers.eras.era_a.prefix then
			modelId = 'lollo_freestyle_train_station/lift/era_a_station_square_plain.mdl'
		elseif era == moduleHelpers.eras.era_b.prefix then
			modelId = 'lollo_freestyle_train_station/lift/era_b_station_square_plain.mdl'
		else
			modelId = 'lollo_freestyle_train_station/lift/station_square_plain.mdl'
		end
		result.models[#result.models + 1] = {
			id = modelId,
			slotId = slotId,
			transf = transfUtilsUG.mul(
				slotTransf,
				{ 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, -buildingHeight, 1 }
			),
			tag = tag
		}

		moduleHelpers.lifts.doTerrain4SideLifts(buildingHeight, slotTransf, result,
		_constants.era_c_groundFacesFillKey, _constants.era_c_groundFacesStrokeOuterKey)
	end,

	getModelsFn = function(params)
		return {
			{
				id = 'lollo_freestyle_train_station/lift/station_square_plain.mdl',
				transf = { 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1 },
			},
		}
	end
}

end
