local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-up-and-down", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("OpenLiftName"),
			description = _("OpenLiftDesc"),
			icon = "ui/lollo_freestyle_train_station/openLift.tga"
		},
		metadata = { },
		order = {
			value = 75,
		},
		type = _constants.openLiftModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			moduleHelpers.openStairs.openLifts_v2_updateFn(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/open_lifts/era_c_open_lift_8m.mdl',
					transf = _constants.idTransf,
				},
			}
		end
	}
end
