local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
-- local transfUtils = require('lollo_freestyle_train_station.transfUtils')
-- local transfUtilsUG = require "transf"
-- local vec3 = require "vec3"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-platform-extensions", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SlopedPassengerAreaWaiting1x5Name"),
			description = _("SlopedPassengerAreaWaiting1x5Desc"),
			icon = "ui/lollo_freestyle_train_station/passenger_area_waiting_1x5.tga"
		},
		metadata = { },
		order = {
			value = 22,
		},
		type = _constants.slopedPassengerArea1x5ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
            local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)

			local myGroundFacesFillKey = _constants[era .. 'groundFacesFillKey']
			local myModelId = _constants[era .. 'slopedPassengerArea1x5ModelFileName']

			moduleHelpers.slopedAreas.addAll(result, tag, params, nTerminal, nTrackEdge, 5,
				myModelId, _constants.passengerWaitingAreaCentredModelFileName,
				myGroundFacesFillKey)

			moduleHelpers.slopedAreas.addSlopedPassengerAreaDeco(result, slotTransf, tag, slotId, params, nTerminal, nTrackEdge, cpl.posTanX2, 0.0, 0.0, era)
		end,

		getModelsFn = function(params)
			local results = {}
			for y = -2, 2 do
				results[#results+1] = {
					id = _constants.era_c_slopedPassengerArea1x5ModelFileName,
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
				}
			end
			return results
		end
	}
end
