local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-platform-extensions", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SlopedPassengerAreaWaiting1x10Name"),
			description = _("SlopedPassengerAreaWaiting1x10Desc"),
			icon = "ui/lollo_freestyle_train_station/passenger_area_waiting_1x10.tga"
		},
		metadata = { },
		order = {
			value = 26,
		},
		type = _constants.slopedPassengerArea1x10ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

            local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
			moduleHelpers.slopedAreas.addAll(result, tag, slotId, params, nTerminal, nTrackEdge, era,
				10,
				_constants[era .. 'slopedPassengerArea1x10ModelFileName'],
				_constants.passengerWaitingAreaCentredModelFileName,
				_constants[era .. 'groundFacesFillKey']
			)
		end,

		getModelsFn = function(params)
			local results = {}
			for y = -5, 5 do
				results[#results+1] = {
					id = _constants.era_c_slopedPassengerArea1x10ModelFileName,
					transf = {0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
				}
			end
			return results
		end
	}
end
