local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-platform-extensions", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SlopedCargoArea1x5Name"),
			description = _("SlopedCargoArea1x5Desc"),
			icon = "ui/lollo_freestyle_train_station/cargo_area_1x5.tga"
		},
		metadata = {
			moreCapacity = {
				cargo = 16,
				passenger = 0
			},
		},
		order = {
			value = 21,
		},
		type = _constants.slopedCargoArea1x5ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
            local _eraPrefix = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)
			local modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/area1x5.mdl'
			if _eraPrefix == _constants.eras.era_a.prefix then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/era_a_area1x5.mdl'
			elseif _eraPrefix == _constants.eras.era_b.prefix then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/era_b_area1x5.mdl'
			end
			if result.platformStyles[nTerminal] == _constants.cargoPlatformStyles.cargo_earth.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/earth_area1x5.mdl'
			elseif result.platformStyles[nTerminal] == _constants.cargoPlatformStyles.cargo_gravel.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/gravel_area1x5.mdl'
			end
			moduleHelpers.slopedAreas.addAll(result, tag, slotId, params, nTerminal, _terminalData, nTrackEdge, _eraPrefix,
				5,
				modelId,
				nil,
				_constants[_eraPrefix .. 'groundFacesFillKey'],
				true
			)
		end,

		getModelsFn = function(params)
			local results = {}
			for y = -2, 2 do
				results[#results+1] = {
					id = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/area1x5.mdl',
					transf = {0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
				}
			end
			return results
		end
	}
end
