local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-platform-extensions", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SlopedCargoAreaWaiting1x20Name"),
			description = _("SlopedCargoAreaWaiting1x20Desc"),
			icon = "ui/lollo_freestyle_train_station/cargo_area_waiting_1x20.tga"
		},
		metadata = { },
		order = {
			value = 26,
		},
		type = _constants.slopedCargoArea1x20ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
            local _eraPrefix = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)
			local modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/area1x20.mdl'
			if _eraPrefix == _constants.eras.era_a.prefix then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/era_a_area1x20.mdl'
			elseif _eraPrefix == _constants.eras.era_b.prefix then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/era_b_area1x20.mdl'
			end
			if result.platformStyles[nTerminal] == _constants.cargoPlatformStyles.cargo_earth.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/earth_area1x20.mdl'
			elseif result.platformStyles[nTerminal] == _constants.cargoPlatformStyles.cargo_gravel.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/gravel_area1x20.mdl'
			end
			if result.laneZs[nTerminal] == _constants.platformHeights._0cm.aboveGround then
				modelId = 'lollo_freestyle_train_station/empty.mdl'
			end
			moduleHelpers.slopedAreas.addAll(result, tag, slotId, params, nTerminal, _terminalData, nTrackEdge, _eraPrefix,
				20,
				modelId,
				_constants.cargoWaitingAreaCentredModelFileName,
				moduleHelpers.getGroundFacesFillKey_cargo(result, nTerminal, _eraPrefix),
				true
			)
		end,

		getModelsFn = function(params)
			local results = {}
			for y = -10, 10 do
				results[#results+1] = {
					id = 'lollo_freestyle_train_station/railroad/slopedSides/cargo/area1x20.mdl',
					transf = {0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
				}
			end
			return results
		end
	}
end
