local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
-- local slotHelpers = require('lollo_freestyle_train_station.slotHelpers')
-- local transfUtils = require('lollo_freestyle_train_station.transfUtils')
-- local transfUtilsUG = require "transf"
-- local vec3 = require "vec3"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-platform-extensions", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SlopedCargoAreaWaiting1x10Name"),
			description = _("SlopedCargoAreaWaiting1x10Desc"),
			icon = "ui/lollo_freestyle_train_station/cargo_area_waiting_1x10.tga"
		},
		metadata = { },
		order = {
			value = 24,
		},
		type = _constants.slopedCargoArea1x10ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			local myGroundFacesFillKey = _constants[(cpl.era or moduleHelpers.eras.era_c.prefix) .. 'groundFacesFillKey']
			local myModelId = _constants[(cpl.era or moduleHelpers.eras.era_c.prefix) .. 'slopedCargoArea1x10ModelFileName']

			moduleHelpers.slopedAreas.addAll(result, tag, params, nTerminal, nTrackEdge, 10,
				myModelId, _constants.cargoWaitingAreaCentredModelFileName,
				myGroundFacesFillKey)

			moduleHelpers.addSlopedCargoAreaDecoEraC(result, slotTransf, tag, slotId, 0, 0)
		end,

		getModelsFn = function(params)
			local results = {}
			for y = -5, 5 do
				results[#results+1] = {
					id = _constants.era_c_slopedCargoArea1x10ModelFileName,
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
				}
			end
			return results
		end
	}
end
