local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-platform-extensions", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SlopedCargoArea1x20Name"),
			description = _("SlopedCargoArea1x20Desc"),
			icon = "ui/lollo_freestyle_train_station/cargo_area_1x20.tga"
		},
		metadata = { },
		order = {
			value = 25,
		},
		type = _constants.slopedCargoArea1x20ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
            local era = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)

			local myGroundFacesFillKey = _constants[era .. 'groundFacesFillKey']
			local myModelId = _constants[era .. 'slopedCargoArea1x20ModelFileName']

			moduleHelpers.slopedAreas.addAll(result, tag, slotId, params, nTerminal, nTrackEdge, era,
				20,
				myModelId,
				nil,
				myGroundFacesFillKey,
				true
			)
		end,

		getModelsFn = function(params)
			local results = {}
			for y = -10, 10 do
				results[#results+1] = {
					id = _constants.era_c_slopedCargoArea1x20ModelFileName,
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
				}
			end
			return results
		end
	}
end
