local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-platform-extensions", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SlopedPassengerArea1x10Name"),
			description = _("SlopedPassengerArea1x10Desc"),
			icon = "ui/lollo_freestyle_train_station/passenger_area_1x10.tga"
		},
		metadata = {
			moreCapacity = {
				cargo = 0,
				passenger = 32
			},
		},
		order = {
			value = 25,
		},
		type = _constants.slopedPassengerArea1x10ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
            local _eraPrefix = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)
			local modelId = 'lollo_freestyle_train_station/railroad/slopedSides/passengers/area1x10.mdl'
			if _eraPrefix == _constants.eras.era_a.prefix then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/passengers/era_a_area1x10.mdl'
			elseif _eraPrefix == _constants.eras.era_b.prefix then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/passengers/era_b_area1x10.mdl'
			end
			if result.platformStyles[nTerminal] == _constants.platformStyles.era_b_db.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/passengers/era_b_db_area1x10.mdl'
			elseif result.platformStyles[nTerminal] == _constants.platformStyles.era_c_db_1_stripe.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/passengers/era_c_db_1_stripe_area1x10.mdl'
			elseif result.platformStyles[nTerminal] == _constants.platformStyles.era_c_fs_1_stripe.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/passengers/era_c_db_1_stripe_area1x10.mdl'
			elseif result.platformStyles[nTerminal] == _constants.platformStyles.era_c_uk_2_stripes.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/passengers/era_c_db_1_stripe_area1x10.mdl'
			elseif result.platformStyles[nTerminal] == _constants.platformStyles.era_c_db_2_stripes.moduleFileName then
				modelId = 'lollo_freestyle_train_station/railroad/slopedSides/passengers/era_c_db_2_stripes_area1x10.mdl'
			end
			moduleHelpers.slopedAreas.addAll(result, tag, slotId, params, nTerminal, _terminalData, nTrackEdge, _eraPrefix,
				10,
				modelId,
				nil,
				_constants[_eraPrefix .. 'groundFacesFillKey']
			)
		end,

		getModelsFn = function(params)
			local results = {}
			for y = -5, 5 do
				results[#results+1] = {
					id = _constants.era_c_slopedPassengerArea1x10ModelFileName,
					transf = {0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
				}
			end
			return results
		end
	}
end
