local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local trackUtils = require('lollo_freestyle_train_station.trackHelpers')
-- local transfUtils = require('lollo_freestyle_train_station.transfUtils')
-- local transfUtilsUG = require "transf"
-- local vec3 = require "vec3"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-platform-extensions", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("SlopedCargoArea1x5Name"),
			description = _("SlopedCargoArea1x5Desc"),
			icon = "ui/lollo_freestyle_train_station/cargo_area_1x5.tga"
		},
		metadata = { },
		order = {
			value = 21,
		},
		type = _constants.slopedCargoArea1x5ModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not nTrackEdge or not baseId then return end

			-- LOLLO TODO do the same as here to provide the right model and the right ground texture to flat and sloped area modules
			local cpl = params.terminals[nTerminal].centrePlatformsRelative[nTrackEdge]
			local myGroundFacesFillKey = _constants.era_c_groundFacesFillKey
			local myModelId = _constants.slopedEraCCargoArea1x5ModelFileName
			if cpl.era == trackUtils.eras.era_a.prepend then
				myGroundFacesFillKey = _constants.era_a_groundFacesFillKey
				myModelId = _constants.slopedEraACargoArea1x5ModelFileName
			elseif cpl.era == trackUtils.eras.era_b.prepend then
				myGroundFacesFillKey = _constants.era_b_groundFacesFillKey
				myModelId = _constants.slopedEraBCargoArea1x5ModelFileName
			end

			moduleHelpers.slopedAreas.addAll(result, tag, params, nTerminal, nTrackEdge, 5,
				myModelId, nil, myGroundFacesFillKey)
		end,

		getModelsFn = function(params)
			local results = {}
			for y = -2, 2 do
				results[#results+1] = {
					id = _constants.slopedEraCCargoArea1x5ModelFileName,
					transf = {1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, y, 0, 1},
				}
			end
			return results
		end
	}
end
