local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-road-access-axial", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("AxialCargoRampFlatName"),
			description = _("AxialCargoRampFlatDesc"),
			icon = "ui/lollo_freestyle_train_station/flatCargoRampFlat.tga"
		},
		metadata = { },
		order = {
			value = 14,
		},
		type = _constants.axialCargoExitModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
			local adjustedTransf = moduleHelpers.axialAreas.getMNAdjustedTransf(params, slotId, slotTransf)
			local _eraPrefix = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)
			local myGroundFacesFillKey = moduleHelpers.getGroundFacesFillKey_cargo(result, nTerminal, _eraPrefix)
			local myModelId = _constants[_eraPrefix .. 'flatCargoRampFlatModelFileName']

			result.models[#result.models + 1] = {
				id = myModelId,
				slotId = slotId,
				transf = adjustedTransf,
				tag = tag
			}

			moduleHelpers.axialAreas.addExitPole(result, slotTransf, tag, slotId, params, nTerminal, _terminalData, nTrackEdge)
			moduleHelpers.axialAreas.addCargoLaneToSelf(result, adjustedTransf, tag, slotId, params, nTerminal, _terminalData, nTrackEdge)

			local groundFace = { -- groundFaces ignore z, terrainAlignmentLists don't
				{-1, -2, _constants.platformSideBitsZ, 1},
				{-1, 2, _constants.platformSideBitsZ, 1},
				{3.5, 2, _constants.platformSideBitsZ, 1},
				{3.5, -2, _constants.platformSideBitsZ, 1},
			}
			modulesutil.TransformFaces(adjustedTransf, groundFace)
			result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, myGroundFacesFillKey)

			local terrainAlignmentList = {
				faces = { groundFace },
				optional = true,
				slopeHigh = _constants.slopeHigh,
				slopeLow = _constants.slopeLow,
				type = 'EQUAL',
			}
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList
		end,

		getModelsFn = function(params)
			return {
				{
					id = _constants.era_c_flatCargoRampFlatModelFileName,
					transf = _constants.idTransf,
				},
				moduleHelpers.axialAreas.getPreviewIcon(params)
			}
		end
	}
end
