local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "cargo-road-access-axial", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("AxialCargoRampUpSmoothName"),
			description = _("AxialCargoRampUpSmoothDesc"),
			icon = "ui/lollo_freestyle_train_station/flatCargoRampUpSmooth.tga"
		},
		metadata = { },
		order = {
			value = 17,
		},
		type = _constants.axialCargoExitModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
			if not nTerminal or not baseId then return end

			local _terminalData = params.terminals[nTerminal]
			local adjustedTransf = moduleHelpers.axialAreas.getMNTiltedTransf(params, slotId, slotTransf)
			local _eraPrefix = moduleHelpers.getEraPrefix2(params, nTerminal, _terminalData, nTrackEdge)
			local myGroundFacesFillKey = moduleHelpers.getGroundFacesFillKey_cargo(result, nTerminal, _eraPrefix)

			local myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/ramp_up_smooth.mdl'
			if _eraPrefix == moduleHelpers.eras.era_b.prefix then
				myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_b_ramp_up_smooth.mdl'
			elseif _eraPrefix == moduleHelpers.eras.era_a.prefix then
				myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/era_a_ramp_up_smooth.mdl'
			end
			if result.platformStyles[nTerminal] == _constants.cargoPlatformStyles.cargo_earth.moduleFileName then
				myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/earth_ramp_up_smooth.mdl'
			elseif result.platformStyles[nTerminal] == _constants.cargoPlatformStyles.cargo_gravel.moduleFileName then
				myModelId = 'lollo_freestyle_train_station/railroad/flatSides/cargo/gravel_ramp_up_smooth.mdl'
			end
			result.models[#result.models + 1] = {
				id = myModelId,
				slotId = slotId,
				transf = adjustedTransf,
				tag = tag
			}

			moduleHelpers.axialAreas.addExitPole(result, slotTransf, tag, slotId, params, nTerminal, _terminalData, nTrackEdge)
			moduleHelpers.axialAreas.addCargoLaneToSelf(result, adjustedTransf, tag, slotId, params, nTerminal, _terminalData, nTrackEdge)

			local groundFace = {
				{-1, -2, 0, 1},
				{-1, 2, 0, 1},
				{3.5, 2, 0, 1},
				{3.5, -2, 0, 1},
			}
			modulesutil.TransformFaces(adjustedTransf, groundFace)
			result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(groundFace, myGroundFacesFillKey)

			local terrainAlignmentList = {
				faces = {
					{
						{-1, -2, _constants.platformSideBitsZ, 1},
						{-1, 2, _constants.platformSideBitsZ, 1},
						{0.0, 2, _constants.platformSideBitsZ, 1},
						{0.0, -2, _constants.platformSideBitsZ, 1},
					},
					{
						{0.0, -2, _constants.platformSideBitsZ, 1},
						{0.0, 2, _constants.platformSideBitsZ, 1},
						{3.5, 2, _constants.stairsAndRampHeight, 1},
						{3.5, -2, _constants.stairsAndRampHeight, 1},
					}
				},
				optional = true,
				slopeHigh = _constants.slopeHigh,
				slopeLow = _constants.slopeLow,
				type = 'EQUAL',
			}
			for _, face in pairs(terrainAlignmentList.faces) do
				modulesutil.TransformFaces(slotTransf, face)
			end
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = terrainAlignmentList
		end,

		getModelsFn = function(params)
			return {
				{
					id = 'lollo_freestyle_train_station/railroad/flatSides/cargo/ramp_up_smooth.mdl',
					transf = _constants.idTransf,
				},
				moduleHelpers.axialAreas.getPreviewIcon(params)
			}
		end
	}
end
