local _constants = require('lollo_freestyle_train_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('lollo_freestyle_train_station.transfUtils')
local transfUtilsUG = require "transf"
local vec3 = require "vec3"


function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	category = {
		categories = { "passenger-up-and-down", },
	},
	cost = {
		price = 0,
	},
	description = {
		name = _("OpenStairsUpRightName"),
		description = _("OpenStairsUpRightDesc"),
		icon = "ui/lollo_freestyle_train_station/openStairsUpRight.tga"
	},
	metadata = { },
	order = {
		value = 71,
	},
	type = _constants.openStairsUpRightModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
		if not nTerminal or not baseId then return end

		local eraPrefix = moduleHelpers.getEraPrefix(params, nTerminal, nTrackEdge)
		local modelId = nil
		if eraPrefix == moduleHelpers.eras.era_a.prefix then modelId = _constants.era_a_openStairsUpModelId
		elseif eraPrefix == moduleHelpers.eras.era_b.prefix then modelId = _constants.era_b_openStairsUpModelId
		else modelId = _constants.era_c_openStairsUpModelId
		end
		result.models[#result.models + 1] = {
			id = modelId,
			slotId = slotId,
			transf = slotTransf,
			tag = tag
		}
        table.insert(result.slots, {
			id = result.mangleId(nTerminal, nTrackEdge, _constants.idBases.openStairsExitInnerSlotId),
			shape = 1,
			spacing = {-1, 3, 0.5, 0.5},
			transf = transfUtilsUG.mul(
				slotTransf,
				{ 0, -1, 0, 0,  1, 0, 0, 0,  0, 0, 1, 0,  0, -1, _constants.openStairsUpZ, 1 }
			),
			type = _constants.openStairsExitModuleType,
		})
		table.insert(result.slots, {
			id = result.mangleId(nTerminal, nTrackEdge, _constants.idBases.stationSquareOuterSlotId),
			shape = 1,
			spacing = {-1, 3, 0.5, 0.5},
			transf = transfUtilsUG.mul(
				slotTransf,
				{ 0, 1, 0, 0,  -1, 0, 0, 0,  0, 0, 1, 0,  0, 1, _constants.openStairsUpZ, 1 }
			),
			type = _constants.openStairsExitModuleType,
		})
	end,

	getModelsFn = function(params)
		return {
			{
				id = _constants.era_c_openStairsUpModelId,
				transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
