local _constants = require('lollo_freestyle_train_station.constants')
local moduleHelpers = require('lollo_freestyle_train_station.moduleHelpers')


function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		category = {
			categories = { "passenger-road-access-stairs", },
		},
		cost = {
			price = 0,
		},
		description = {
			name = _("OpenStairsExitWithSnappyEdgeName_2m"),
			description = _("OpenStairsExitWithSnappyEdgeDesc"),
			icon = "ui/lollo_freestyle_train_station/openStairsExitWithSnappyEdge2m.tga"
		},
		metadata = { },
		order = {
			value = 61,
		},
		type = _constants.openStairsExitModuleType,
		updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
			return moduleHelpers.openStairs.stairsExitWithEdgeModule_v2_updateFn(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams, true)
		end,

		getModelsFn = function(params)
			return {
				{
					-- id = 'lollo_freestyle_train_station/open_stairs/era_c_bridge_chunk_4m.mdl',
					id = 'lollo_freestyle_train_station/open_stairs/bridge_chunk_2m.mdl',
					transf = _constants.idTransf,
				},
				moduleHelpers.openStairs.getPreviewIcon(params),
			}
		end
	}
end
